### ISSUE TITLE
a *Queries, with Close() functionality

### ISSUE THREAD

**Issue by kevinburkemeter** [kyleconroy/sqlc#100]
In tests, I would like to open a handle to a database, make some queries, and then close it. Right now this requires holding handles to both the *sql.DB and the *db.Queries structs, and adding two layers of error checks. This is cumbersome in exactly the place where I want to use this - in tests.

Further, it would be nice to enforce that callers are not using the raw `db` handle.

Could we add .BeginTx() and Close() error to the *Queries struct?

Or introduce a concept of a ManagedDB that has both of those functions, plus either a handle Queries or exports its functions?

**Comment by kevinburkemeter** [comment]
here is how I ended up managing this, FYI

```
type ManagedDB struct {
	*Queries
	db *sql.DB
}

type ManagedTx struct {
	*Queries
	tx *sql.Tx
}

func (m *ManagedDB) Close() error {
	return m.db.Close()
}

func (m *ManagedDB) BeginTx(ctx context.Context, opts *sql.TxOptions) (*ManagedTx, error) {
	tx, err := m.db.BeginTx(ctx, opts)
	if err != nil {
		return nil, err
	}
	return &ManagedTx{
		Queries: m.Queries.WithTx(tx),
		tx:      tx,
	}, nil
}

func (m *ManagedTx) Commit() error {
	return m.tx.Commit()
}

func (m *ManagedTx) Rollback() error {
	return m.tx.Rollback()
}
```

**Comment by kyleconroy** [comment]
Closing this in favor of #101
