### ISSUE TITLE
column does not exist

### ISSUE THREAD

**Issue by Git-me-outta-here** [kyleconroy/sqlc#1002]
I have four insert into statements. They work fine with v1.7.0.

```sql
-- name: CreateNeuron :exec
INSERT INTO public.neurons
(neuron_id, col1, col2)
VALUES($1, $2, $3);
```

In v1.8.0 sqlc generate gives this error:
column "neuron_id" does not exist

Happens with all four insert into statements. Please help! Until then, I'm back to using v1.7.0

**Comment by kyleconroy** [comment]
Confirmed the regression [here](https://play.sqlc.dev/p/3ebfc987af81fee1677d2fdca6c752b4a0aa3f46c398dacaebda67b138d36d96). It looks like it has something to do with the `public` namespace.

In the meantime, the workaround is to [remove the `public` prefix](https://play.sqlc.dev/p/7b6663a881a7ef5ceaddde9513b55e4aa400f1e17d6f7074d8fd6b2881444ba8).
