### ISSUE TITLE
BUG: v1.8.0 breaks queries with Postgis functions

### ISSUE THREAD

**Issue by friend0** [kyleconroy/sqlc#1004]
I noticed some issues with generation after inadvertently upgrading to v1.8.0 from v1.7.0. We use a number of Postgis function in our queries, and they had otherwise worked fine, so I was surprised to see these messages about missing functions 
```
/src/containers/XXX/sql/query/XXX.sql:1:1: function not found: st_dwithin
/src/containers/XXX/sql/query/XXX.sql:26:1: function not found: st_intersects
/src/containers/XXX/sql/query/XXX.sql:52:1: function not found: st_intersects
/src/containers/XXX/sql/query/XXX.sql:76:1: function not found: st_intersects
.
.
.
```
Are there missing configs I need to update for these? Rolling back to v1.7.0 seems to have resolved the issues. I'm on ubuntu.
Let me know if there are more details I can provide

**Comment by polastre** [comment]
I have the same problem with `ST_*` functions in v1.8.0. Rolling back to v1.7.0 fixes for me too.

**Comment by kyleconroy** [comment]
@friend0 Can you provide a complete example of your failing queries?

**Comment by kyleconroy** [comment]
This appears to a be a bug with the implementation of https://github.com/kyleconroy/sqlc/pull/964
