### ISSUE TITLE
Missing struct in generated file

### ISSUE THREAD

**Issue by NeverVane** [kyleconroy/sqlc#1009]
Hi, I'm having some issue with `sqlc generate` command.
Reading from the documentation I'd expect to have a query.sql.go file with a bunch of funds and structs, one of these should be something like:

```
type CreateAuthorParams struct {
	Name string
	Bio  sql.NullString
}

func (q *Queries) CreateAuthor(ctx context.Context, arg CreateAuthorParams) (Author, error) {
	row := q.db.QueryRowContext(ctx, createAuthor, arg.Name, arg.Bio)
	var i Author
	err := row.Scan(&i.ID, &i.Name, &i.Bio)
	return i, err
}
```

but I only get 

```
func (q *Queries) CreateAuthor(ctx context.Context, arg CreateAuthorParams) (Author, error) {
	row := q.db.QueryRowContext(ctx, createAuthor, arg.Name, arg.Bio)
	var i Author
	err := row.Scan(&i.ID, &i.Name, &i.Bio)
	return i, err
}
```

I haven't any of the params structs related to the specified tables, I could create myself but that should be repeated every time I `sql generate`

I have a big table with around 160 columns and I thought that could be the problem, but also trying with a small table will produce the same effect.

I'm running 

MacOS 11.2.3
Sqlc -v 1.6
DB: Mysql

**Comment by kyleconroy** [comment]
Can you upgrade to v1.8.0 and try again? v1.6.0 is a few versions behind at this point.

**Comment by buschjost** [comment]
I had this issue when I failed to write proper MySQL queries. In my case I had the $1, $2 Postgres style placeholders (like in the examples) instead of MySQL ?, ? ones. 

So I had like

```-- name: CreateRedirect :exec
INSERT INTO Redirect (
  origin, target
) VALUES (
  $1, $2
);
```

instead of 

````
-- name: CreateRedirect :exec
INSERT INTO Redirect (
  origin, target
) VALUES (
  ?, ?
);
```

Do you maybe have a similar issue?

**Comment by NeverVane** [comment]
> I had this issue when I failed to write proper MySQL queries. In my case I had the $1, $2 Postgres style placeholders (like in the examples) instead of MySQL ?, ? ones.
> 
> So I had like
> 
> ```
> INSERT INTO Redirect (
>   origin, target
> ) VALUES (
>   $1, $2
> );
> ```
> 
> instead of
> 
> ```
> -- name: CreateRedirect :exec
> INSERT INTO Redirect (
>   origin, target
> ) VALUES (
>   ?, ?
> );
> ```
> 
> Do you maybe have a similar issue?

Oh man ... what such a stupid mistake I had ! You made my day :D
