### ISSUE TITLE
Support jsonb functions

### ISSUE THREAD

**Issue by pcriv** [kyleconroy/sqlc#1018]
Currently when using `jsonb_build_object` on a select clause

I get the following error:

```
function jsonb_build_object(unknown, unknown) does not exist
```

A workaround that I'm using atm is:

```
json_build_object('foo', 'bar')::jsonb
```

**Comment by elvizlai** [comment]
any progress?

**Comment by kyleconroy** [comment]
This has been fixed https://play.sqlc.dev/p/f3ec71909782550b9cd6d7bcce3902b749f4f753ac36968e3ee7fcfd5db460a4
