### ISSUE TITLE
consider stripping comments

### ISSUE THREAD

**Issue by kevinburkemeter** [kyleconroy/sqlc#102]
I have a long comment above a query that's explaining what it's doing. Unfortunately this gets included in the Queries file and sent to Postgres every time, which seems unnecessary. Stripping comments might be a good idea, or permitting comments to be included if they have a metadata tag.

**Comment by kyleconroy** [comment]
Instead of stripping them, let's convert them into Go comments. For example, this query

```sql
-- name: GetAuthor :one
-- fetch a single author from the database
-- based on that author's numeric ID
SELECT * FROM authors
WHERE id = $1 LIMIT 1;
```

would become

```go
const getAuthor = `-- name: GetAuthor :one
SELECT id, name, bio FROM authors
WHERE id = $1 LIMIT 1
`
// fetch a single author from the database
//based on that author's numeric ID
func (q *Queries) GetAuthor(ctx context.Context, id int64) (Author, error) {
	...
}
```
```
