### ISSUE TITLE
CASE in WHERE clause yields "no column reference found"

### ISSUE THREAD

**Issue by maxhawkins** [kyleconroy/sqlc#1024]
Apparently this is a valid query in Postgres:

```sql
SELECT name
FROM users
WHERE
    CASE
      WHEN $1 != '' THEN user_id = $1
      WHEN $2 != '' THEN title = $2
    END
```

But when I try to use this query with sqlc I get the error "no column reference found"

**Comment by kyleconroy** [comment]
This has been fixed: https://play.sqlc.dev/p/d6cd820101a6f1e151da3621aa3d541372c863925961e8191aa3e9aa1e6d74ed

The parameter types are `interface{}`, but the query does compile.
