### ISSUE TITLE
Panic??? Need help

### ISSUE THREAD

**Issue by basilex** [kyleconroy/sqlc#1038]
Hi, all!
SQLC docker image:

docker run --rm -v /Users/XXX/Workspace/src/gitlab.com/project/be:/src -w /src kjconroy/sqlc generate
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0xcfe8a8]

goroutine 1 [running]:
github.com/kyleconroy/sqlc/internal/compiler.resolveCatalogRefs(0xc0004c0230, 0xc00012a648, 0x1, 0x1, 0xc00094c0f0, 0x5, 0x5, 0xc0009cd830, 0x0, 0xc000b90d30, ...)
	/workspace/internal/compiler/resolve.go:301 +0x16c8
github.com/kyleconroy/sqlc/internal/compiler.(*Compiler).parseQuery(0xc0003cc800, 0x12ecb20, 0xc0008f98e0, 0xc000c95900, 0x4d0, 0x0, 0x0, 0x0, 0x0)
	/workspace/internal/compiler/parse.go:90 +0x565
github.com/kyleconroy/sqlc/internal/compiler.(*Compiler).parseQueries(0xc0003cc800, 0x1000000, 0xc0004c0230, 0xc0005233a0, 0x1)
	/workspace/internal/compiler/compile.go:109 +0x599
github.com/kyleconroy/sqlc/internal/compiler.(*Compiler).ParseQueries(...)
	/workspace/internal/compiler/engine.go:49
github.com/kyleconroy/sqlc/internal/cmd.parse(0xc0000dd600, 0xc00052712c, 0x3, 0xc000526edc, 0x4, 0xc000527176, 0xa, 0xc0005233a0, 0x1, 0x1, ...)
	/workspace/internal/cmd/generate.go:223 +0x145
github.com/kyleconroy/sqlc/internal/cmd.Generate(0x19d2300, 0xc000526edc, 0x4, 0x0, 0x0, 0x12f10e0, 0xc000010020, 0x0, 0x10a0b77, 0x32)
	/workspace/internal/cmd/generate.go:167 +0xce9
github.com/kyleconroy/sqlc/internal/cmd.glob..func3(0x19d23a0, 0x1f2a160, 0x0, 0x0)
	/workspace/internal/cmd/cmd.go:120 +0x17d
github.com/spf13/cobra.(*Command).execute(0x19d23a0, 0x1f2a160, 0x0, 0x0, 0x19d23a0, 0x1f2a160)
	/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:856 +0x2c2
github.com/spf13/cobra.(*Command).ExecuteC(0xc00056c780, 0xc0000ddf10, 0x1, 0x1)
	/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:960 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
	/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:897
github.com/kyleconroy/sqlc/internal/cmd.Do(0xc00003c050, 0x1, 0x1, 0x12f10a0, 0xc000010010, 0x12f10e0, 0xc000010018, 0x12f10e0, 0xc000010020, 0xc000096058)
	/workspace/internal/cmd/cmd.go:34 +0x317
main.main()
	/workspace/cmd/sqlc/main.go:10 +0xb5
make: *** [generate-dbs] Error 2

**Comment by wasaga** [comment]
sqlc has little tolerance to errors like referencing a table or a field that was not part of a schema. 

check your schema and queries first against an actual database engine, before feeding them to sqlc - you'll get a more comprehensive error message.

**Comment by kyleconroy** [comment]
@basilex Can you please include your schema and queries? You can also create an example of the failing case here: https://play.sqlc.dev
