### ISSUE TITLE
delete generated Go files

### ISSUE THREAD

**Issue by kevinburkemeter** [kyleconroy/sqlc#105]
I dropped a table and removed the corresponding `db/query/<table>.go` file. However, `src/internal/db/<table>.sql.go` file was not deleted. I expected it to be deleted.

**Comment by kyleconroy** [comment]
Does `protoc` do this? I'm tempted to close this out as `wontfix`.

**Comment by kevinburkemeter** [comment]
Good question, I'm not sure.

**Comment by kyleconroy** [comment]
I've tested the behavior of `protoc`. The generated files are not deleted. I'm content to do the same.

**Comment by toqueteos** [comment]
> I've tested the behavior of `protoc`. The generated files are not deleted. I'm content to do the same.

I just renamed a table and discovered this behavior of sqlc, could we add a note somewhere in the docs that the `out` folder contents are not cleared upon calling `sqlc generate`? (although having an optional flag to do so would be a wonderful addition)
