### ISSUE TITLE
Up to date docker release for sqlc

### ISSUE THREAD

**Issue by breml** [kyleconroy/sqlc#1050]
We use sqlc in our ci pipeline where it is executed in a docker container of ours, containing all the necessary tooling including sqlc.

In order to update our tooling container, we use the sqlc binary from the docker container `kjconroy/sqlc` mentioned in the [official documentation](https://docs.sqlc.dev/en/latest/overview/install.html).

It looks to me, that this docker container is unfortunately not updated at the same time as the rest of the releases (e.g. Github).

Therefore I have two requests:

1. Would it be possible to provide the "docker compatible" release binary as Github release as well (the regular linux amd64 binary does not work in `FROM scratch` or alpine linux docker containers)?
2. Would it be possible to update the docker container `kjconroy/sqlc` at the same time as the other releases.

Thanks for this great tool.

**Comment by kyleconroy** [comment]
The `kjconroy/sqlc` repository should contain every release. It looks like 1.8.0 somehow didn't make it in.

**Comment by kyleconroy** [comment]
Fixed!
