### ISSUE TITLE
error if two queries under a single banner

### ISSUE THREAD

**Issue by kevinburkemeter** [kyleconroy/sqlc#1056]
A coworker tried to do this:

```
-- name: Query12 :execrows
DELETE FROM table1 WHERE ...

DELETE FROM table2 WHERE ...
```

And expected since there was no magic comment that both queries would run. Unfortunately sqlc only finds/adds the first query and not the second.

Could we make the parser error out in this case?

**Comment by kyleconroy** [comment]
sqlc ignores queries that aren't annotated. It would be a larger change to error on these types of queries. Did your coworker expect both queries to be included in the query string? By default, the Go MySQL driver doesn't execute multiple statements in a query. I don't know about PostgreSQL

**Comment by kevinburkemeter** [comment]
>  Did your coworker expect both queries to be included in the query string?

Yes that's exactly what happened. I would have expected non-annotated queries to error, I'm surprised that they're ignored.
