### ISSUE TITLE
sql where conditions are uncertain， how to deal with

### ISSUE THREAD

**Issue by nobody05** [kyleconroy/sqlc#1063]
like this 
there is some uncertain conditions, you can search use : name, id ,or other fields
eg: select * from user where {name = "jack " or id = 1 ..}
can i custom sqlc

**Comment by aitva** [comment]
Hi @nobody05,

I answered a similar question in #1062. Can you have a look at it and tell me if it answers your problem?

**Comment by nobody05** [comment]
thanks
