### ISSUE TITLE
Generated Params JSON tags not in Snake Case 

### ISSUE THREAD

**Issue by Mrcampbell** [kyleconroy/sqlc#108]
When the Params are Generated by sqlc, the tags are in camel case rather than snake case (as in the `models.go` when we have the `emit_json_tags` set to true.

Here is the sqlc.json:

```json
{
  "packages": [
    {
      "name": "sqlc",
      "emit_json_tags": true,
      "emit_prepared_queries": false,
      "path": "./internal/sqlc",
      "queries": "./dbconfig/query/",
      "schema": "./dbconfig/migrations"
    }
  ],
  "overrides": null,
  "rename": null
}
```

The Query: 
```sql
-- name: CreateAgreement :one
INSERT INTO insys_agreements.agreements
    (id, user_id, user_email, first_name, last_name, location_id, created_at, agreement_content_id)
VALUES ($1, $2, $3, $4, $5, $6,now(), $7)
RETURNING id, user_id, user_email, first_name, last_name, location_id, created_at, agreement_content_id;
```

The Params generated by sqlc:
```go
type CreateAgreementParams struct {
    ID                 uuid.UUID      `json:"id"`
    UserID             uuid.UUID      `json:"userID"`
    UserEmail          sql.NullString `json:"userEmail"`
    FirstName          sql.NullString `json:"firstName"`
    LastName           sql.NullString `json:"lastName"`
    LocationID         uuid.UUID      `json:"locationID"`
    AgreementContentID uuid.UUID      `json:"agreementContentID"`
}
```

And the Model generated by sqlc:

```go
type InsysAgreementsAgreement struct {
    ID                 uuid.UUID      `json:"id"`
    UserID             uuid.UUID      `json:"user_id"`
    UserEmail          sql.NullString `json:"user_email"`
    FirstName          sql.NullString `json:"first_name"`
    LastName           sql.NullString `json:"last_name"`
    LocationID         uuid.UUID      `json:"location_id"`
    CreatedAt          time.Time      `json:"created_at"`
    AgreementContentID uuid.UUID      `json:"agreement_content_id"`
}
```

I would expect the json tags on the Model to match the Params, but they aren't.

**Comment by kyleconroy** [comment]
I would expect the JSON tags to be the same as well! I'll get started on a fix

**Comment by euller88** [comment]
Wow, I've never realized that happened. Having a flag in the config file, making all tags either snake- or camel-case be a desirable behavior.

**Comment by kyleconroy** [comment]
@euller88 we can discuss adding such a flag, but the issue right now is that the tags aren't consistent. The intended behavior is that the JSON tag value is the name of the column.

**Comment by kyleconroy** [comment]
@Mrcampbell this should now be fixed in the latest version of sqlc. Please update and let me know if it's still broken.

**Comment by kyleconroy** [comment]
Also, curious how you found out about the project

**Comment by Mrcampbell** [comment]
My manager found it on a HackerNews comment.  We love this project and it's really helped!  We were thinking of writing our own, but this is better than anything we could have done.

**Comment by Mrcampbell** [comment]
And that worked like a charm!  Thank you for the fix and an extra thanks for the speed!

**Comment by kyleconroy** [comment]
Great! I'd love to chat a bit more about how you're using sqlc and how I can make it better. Could you send me an email at kyle@conroy.org? Thanks

**Comment by Mrcampbell** [comment]
Yeah!  Sorry I missed this!
