### ISSUE TITLE
Windows support for MySQL not accepting ? identifier (like $1 in postgress)

### ISSUE THREAD

**Issue by arc2501** [kyleconroy/sqlc#1080]
Hi,

I tried experimenting with sqlc support of MySQL on windows turns out the query.sql file is not recognizing "?" symbol (as illustrated in examples). While using sqlc (sqlc generate), as soon as it is encountering "?" sign, error is generated that 1st column name of the table (like name in author) "does not exist". :/
Its working fine if the expected data type values are being supplied in INSERT or WHERE clauses but as soon as sample of expected data values are filled in, sqlc works but  as a result no struct are being created in .sql.go files.

![sql_query](https://user-images.githubusercontent.com/60605782/125203110-b551b480-e294-11eb-9d4a-a351867bcdb8.PNG)
![error](https://user-images.githubusercontent.com/60605782/125203115-bb479580-e294-11eb-8c68-aa95bb5a4d6b.PNG)

**Comment by kyleconroy** [comment]
@arc2501 Can you please provide a complete example? And include the version of sqlc that you're using?
