### ISSUE TITLE
Windows - Docker Run: error parsing sqlc.json: file does not exist

### ISSUE THREAD

**Issue by LarryEitel** [kyleconroy/sqlc#1099]
I am trying to run using Docker. After various incarnations, my latest attempt:

```
MSYS_NO_PATHCONV=1 docker run --rm -v "G:\My Drive\go\play\simplebank"://src -w /src kjconroy/sqlc gener
ate
```

Returns:
```
error parsing sqlc.json: file does not exist
make: *** [sqlc] Error 1
```

I have both sqlc.[yaml and json] in this directory.

I populated sqlc.json with sample from this repo.

I have tried running from Powershell, CMD and Gitbash.

Any suggestions please?

**Comment by OfficialBoyfriend** [comment]
```bash
docker run --rm -v "G:\My Drive\go\play\simplebank":/src -w /src kjconroy/sqlc:1.9.0-beta1 generate
```
Try kjconroy/sqlc:1.9.0-beta1 image

**Comment by kyleconroy** [comment]
v1.9.0 has been released, so I'm going to mark this as fixed.
