### ISSUE TITLE
"sqlc generate" panics when schema file have wrong suffix.

### ISSUE THREAD

**Issue by Bogeyduffer** [kyleconroy/sqlc#1120]
I somehow ended up with migration file names that ended with commas. i.e. "000001_init-schema.up.sql,”.

The syntax error produced the following message: 
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x48ffd88]

This was difficult for someone who is new to go, sqlc, and sql to figure out. Hopefully, you can create a more graceful way to handle this.

Thanks.

**Comment by kyleconroy** [comment]
I can't reproduce this locally. sqlc will ignore files that do not have a `.sql` file extension. In this case, sqlc is skipping over the `init-schema.up.sql` file which causes a panic somewhere else. Can you include the full panic error message?
