### ISSUE TITLE
No longer able to retrieve enum array in v1.9.0 using pgx

### ISSUE THREAD

**Issue by rhodee** [kyleconroy/sqlc#1126]
Prior to `1.9.0` sqlc was able to return an `([]interface{}, error)` for the following kind of query:

My code sets up the following query:

```sql
-- name: LotAltitude :many
SELECT unnest(enum_range(null::lot_altitude_designation))
```

I get the following error:

`can't scan into dest[0]: unknown oid 20450 cannot be scanned into *interface {}`

So I did some research and found the `RegisterDataType` [method](https://pkg.go.dev/github.com/jackc/pgtype#ConnInfo.RegisterDataType). This however has raised more questions of how to provide the pointer value to satisfy the `pgtype.Value`.

When I revert to `1.6.0` the issue is no longer present. Is there any guidance you can provide for getting unblocked? 

Awesome work team and I appreciate you helping me level up my pgx knowledge -

**Comment by kyleconroy** [comment]
How are you using pgx with 1.6.0? Official support just landed in the latest release

**Comment by rhodee** [comment]
Hi @kyleconroy apologies. The versions (1.9.0/1.6.0) I referred to are for `sqlc`, not `pgx`. 

My `go.mod` file contains these entries:

```sh
github.com/jackc/pgconn v1.10.0
github.com/jackc/pgx/v4 v4.13.0
```

**Comment by kyleconroy** [comment]
Can you include a code sample that shows how you're using sqlc 1.6.0 with pgx? It wasn't support before, so I'm not sure how it was working.

**Comment by rhodee** [comment]
Hi @kyleconroy - let me restate the problem.

Starting with `sqlc` v1.9.0 I am not longer able to return an enumerated list. I have created two repos that return two different results based on the driver, although the SQL is identical. 

In summary:

1. In all previous sqlc versions (using the config and query in `enum_array_sqldb`) returned values. 
2. When moving to pgx_v4 as the sql_package no values are returned.

Repos:

https://github.com/rhodee/enum_array_pgxv4
https://github.com/rhodee/enum_array_sqldb

Thank you for your patience.

**Comment by kyleconroy** [comment]
@rhodee Those repositories are sadly 404ing for me. If you're still having issues, cold you try using the latest version of sqlc (1.17.2) with pgx/v5? If things are still broken, please open up a new issues with a complete repro and a link to play.sqlc.dev.
