### ISSUE TITLE
Feature request: Return last inserted ID for MySQL INSERT

### ISSUE THREAD

**Issue by mportugal** [kyleconroy/sqlc#1136]
It would be really nice if there was some way where, using MySQL as the database of choice, the `sql.Result` struct was returned when INSERT queries are executed. Currently, the `sql.Result` struct is being ignored.

**Comment by dee-el** [comment]
do you use anotation `:exec` ? if it yes, you should change it with `:execresult`. `execresult` will return `(sql.Result, error)`

**Comment by kyleconroy** [comment]
Thanks for the answer @dee-el. The `:execresult` command is meant for this exact situation.

**Comment by mportugal** [comment]
Thank you everyone
