### ISSUE TITLE
Allow passing a single filename for "query" or "schema"

### ISSUE THREAD

**Issue by inconshreveable** [kyleconroy/sqlc#115]
The sqlc json file requires that the `schema` and `queries` options must be directories, but in some cases I'd like to be specific and pass a particular file, e.g.:

```
			"schema": "./postgres/flags.sql"
```

**Comment by kyleconroy** [comment]
What was the error when you tried a file? Both [`ParseCatalog`](https://github.com/kyleconroy/sqlc/blob/master/internal/dinosql/parser.go#L60) and [`ParseQueries`](https://github.com/kyleconroy/sqlc/blob/master/internal/dinosql/parser.go#L171) should work with single files.

**Comment by euller88** [comment]
Back when I started using sqlc I was facing a similar situation and I thought it was due misinterpretation of the docs. Now it seems that is truly a issue, I will try to investigate.

**Comment by inconshreveable** [comment]
Configuration file:
`                        "schema": "./postgres/flags.sql"`

```sqlc generate
# package query
postgres/flags.sql/flags.sql:1:1: open postgres/flags.sql/flags.sql: not a directory
```
