### ISSUE TITLE
Mark query parameters as nullable

### ISSUE THREAD

**Issue by kyleconroy** [kyleconroy/sqlc#1155]
For the following query, sqlc will generate a function signature with a string for parameter $1.

```sql
CREATE TABLE users ( name TEXT NOT NULL );

-- name: ListUsers :many
SELECT *
FROM users
WHERE name = $1;
```

```go
func (q *Queries) ListUsers(ctx context.Context, name string) ([]string, error) {
    // ...
}
```

How should we indicate that parameter $1 should be nullable?

### Option 1: Add a parameter to the `sqlc.arg` function

```sql
CREATE TABLE users ( name TEXT NOT NULL );

-- name: ListUsers :many
SELECT *
FROM users
WHERE name = sqlc.arg('name', nullable => true);
```

Originally reported in #200

**Comment by imraan-go** [comment]
Option 1 seems to be the best way to implement this feature.

**Comment by mrsufgi** [comment]
how would you go about the shorthand for `@param`? new syntax? no shorthand?

**Comment by kyleconroy** [comment]
@mrsufgi the shorthand syntax is problematic (see #605), so for now this would only work when using `sqlc.arg`.

**Comment by kyleconroy** [comment]
Fixed by https://github.com/kyleconroy/sqlc/pull/1536
