### ISSUE TITLE
document: supported database types

### ISSUE THREAD

**Issue by huyennbl** [kyleconroy/sqlc#1159]
Please update the documentation about the supported database types. I wander around 15 minutes, still cannot find any information of that. 
All I can see is `Planned Database Support`, but how about `Current Database Support`?

**Comment by kyleconroy** [comment]
A language and database support table exists here: https://github.com/kyleconroy/sqlc/blob/main/docs/reference/language-support.rst

It appears that table syntax is wrong because it's not showing up in the docs.
