### ISSUE TITLE
when using pgx Ltree type is not supported

### ISSUE THREAD

**Issue by eborst** [kyleconroy/sqlc#1196]
### Version

1.10.0

### What happened?

Added a column with type ltree.

Generation seems working fine, but when using a query with ltree type I'm getting the following error:
can't scan into dest[16]: unknown oid 22546 cannot be scanned into *interface {}
dest[16] in this case is the ltree column

### Database schema

```sql
create extension if not exists ltree;

ALTER TABLE relation.organization
    ADD COLUMN organization_path public.ltree;
```

### What operating system are you using?

macOS

### What database engines are you using?

PostgreSQL

### What type of code are you generating?

Go

**Comment by kyleconroy** [comment]
Are you using pgx or database/sql? If you don't know, can you include your sqlc configuration file?

**Comment by eborst** [comment]
Sorry I forgot to include that. I'm using pgx.

**Comment by kyleconroy** [comment]
Can you also include the query you're trying to run and the configuration file? pgx doesn't have explicit support for ltree, but it should just work with string types.

**Comment by eborst** [comment]
I have recreated the scenario, but cannot reproduce the issue anymore.
The type is now generated as sql.Nullstring and not as interface{} anymore. 
I'm feeling stupid now... 🙈 
I will setup the whole scenario again and if I can reproduce I will report back. 
Sorry for bothering you... Keep up the good work!
