### ISSUE TITLE
Omitting not-null parameters inserts zero value instead of an error

### ISSUE THREAD

**Issue by inconshreveable** [kyleconroy/sqlc#120]
sqlc promises type-safety in its generated code. Unfortunately it runs into the same problem that all Go programs do which is the inability to distinguish between a non-present value and a zero value.

I defined a table like so:

```
CREATE TABLE foo (
        id VARCHAR(27) NOT NULL,
        val INTEGER NOT NULL,
);
```

An insert statement like so:
```
-- name: CreateFoo :one
INSERT INTO foo
(id, val)
VALUES
($1, $2)
RETURNING *
```

And then called it like so:

```
query.CreateFoo(query.CreateFooParams{
    Val: 42,
})
```

I expect that this call will fail. In a perfect world it would fail at compile-time. It a better world it would fail at runtime when the database says "you tried to insert a row but did not specify the NOT NULL parameter `id`.

What I observed is that the call *succeeds* and that the database simply contains an empty string for the `id` value.

Mitigations:

There are two reasonable mitigations I can imagine, but they both have tradeoffs:

1) Make all non-null columns be pointer fields in the generated parameters structs. e.g. 

```
type CreateFooParams struct {
        ID        *string
        Val      *int32
}
```

(these could be columns like `sql.NullString` instead of pointer values if you'd like, it makes little difference)

And then provide convenience functions to make the interface less gross. This is the approach taken by the AWS libraries. e.g.

```
query.CreateFoo(query.CreateFooParams{
    Val: sqlc.Int32(42),
})
```

or if it's generated using `sql.NullInt32`:

```
query.CreateFoo(query.CreateFooParams{
    Val: sql.NullInt32{Int32: 42, Valid: true},
})
```

Presumably this could be a tunable option that callers could choose on a query-by-query basis with another argument on the query (and could be set globally in `sqlc.json` as well):

```
-- name: CreateFoo :one udefcol: nil|zero
INSERT INTO foo
(id, val)
VALUES
($1, $2)
RETURNING *
```

2) Make all arguments to not null columns be standalone function arguments. e.g. generate code that looks like:

```
func (q *Queries) CreateFoo(ctx context.Context, id string, val int32) (Foo, error) {
}
```

This makes the call site far less readable, especially when working with many parameters but it enforces the type-safe *at compile time* which is nice. sqlc currently uses a heuristic that it takes that approach if there is a single argument (and generates a structure if there are 2+ arguments). It's possible that sqlc could make that a tunable argument of the query, e.g.

```
-- name: CreateFoo :one funcsig: struct|args
INSERT INTO foo
(id, val)
VALUES
($1, $2)
RETURNING *
```

If you specify `struct`, it generates a struct of all parameters, but if you specify `args` it generates a function call where each parameter is a separate argument to the function. This would allow the library user to trade off safety for readability.

**Comment by andrewmbenton** [comment]
I just ran into this issue in a project using tables with `<name> uuid NOT NULL;` columns. It was frightening to see zero-valued UUIDs in the database and I had a similar reaction to @inconshreveable in that I expected sqlc to protect me from myself here somehow.

I think @kyleconroy has the right solution for types that map to `sql.Null*` structs. Perhaps that's implemented now (I didn't check). If not I think it's a good path forward.

For types outside of `sql.Null*` I think it would be nice to have sqlc generate those and then use them in `query.Create*Params` structs to enforce usage. I think it should be possible to do this automatically but I may not have thought it through entirely.
