### ISSUE TITLE
Missing package 'embed' referenced in template.go -- can not compile.

### ISSUE THREAD

**Issue by zoranembroker** [kyleconroy/sqlc#1203]
### Version

1.10.0

### What happened?

Can not compile with make (build). Looks like a package is missing.

### Relevant log output

```shell
internal/codegen/golang/template.go:3:8: package embed is not in GOROOT (/usr/local/go/src/embed)
```

### What operating system are you using?

Linux

### What database engines are you using?

PostgreSQL

### What type of code are you generating?

Go

**Comment by kyleconroy** [comment]
Please upgrade to a recent version of Go. sqlc now requires 1.26 or higher to compile.
