### ISSUE TITLE
Computed columns do not generate a field

### ISSUE THREAD

**Issue by nzoschke** [kyleconroy/sqlc#122]
If I have a query like:

```sql
-- name: ListUsageQuotas :many
SELECT *, bytes_downloaded / 1024 as mb_downloaded FROM usages;
```

I expect to have a `MbDownloaded` field on the ListUsagesTestRow struct. But there is no extra field there.

This seems related to https://github.com/kyleconroy/sqlc/issues/103, which helped me discover a workaround by wrapping it in parens and adding an explicit type:

```sql
-- name: ListUsagesTest :many
SELECT *,(bytes_downloaded / 1024)::float AS mb_downloaded FROM usages;
```

**Comment by inconshreveable** [comment]
I just ran into a similar issue. Here's the query which is used to determine whether an insert would put the number of inserted rows matching a condition over a limit:

```
INSERT INTO foo (bar)
SELECT $1
FROM foo
WHERE tenant_id = $2
HAVING count(*) < $3
RETURNING *;
```

# package query
test.sql:14:17: no column reference found

@nzoschke's workaround works somewhat in that this query works:

```
INSERT INTO foo (bar)
SELECT $1
FROM foo
WHERE tenant_id = $2
HAVING (count(*)::INTEGER) < $3
RETURNING *;
```

but it has two problems:
1. that's unintuitive
2. (more importantly) the generated column name is `Column3` which is both confusing and also will cause the code to break in an unexpected way if the parameter ordinals get changed

**Comment by kyleconroy** [comment]
@nzoschke thanks for the report. `mb_downloaded` was being left out because I hadn't added support for mathematical operators. I'm fixing that now.

@inconshreveable your problem appears to be different. I can't reproduce it. Can you open a new issue with a self-contained example? I tried the following SQL but couldn't get it to generate code. It failed with an `no column reference found`.

```sql
CREATE TABLE foo (id text not null);
INSERT INTO foo (id)
    SELECT $1 FROM foo
    HAVING count(*) < $2
RETURNING *;
```
