### ISSUE TITLE
Python reserved words

### ISSUE THREAD

**Issue by Hendler** [kyleconroy/sqlc#1241]
### Version

1.10.0

### What happened?

Python output looks good! 

Minor issue. 

I had a column name named `class`. This generated a python dataclass that did not escape the reserved word. Not sure if the solution is to 
 - not name things "class" (my workaround)
 - quote class in the dataclass (like type hinting can do in python)
 - warn user and reject reserved words as column names/dataclass field names

(I have seen this in mysql with `type` as column name too.)

### What operating system are you using?

macOS

### What database engines are you using?

MySQL

### What type of code are you generating?

Python

**Comment by kyleconroy** [comment]
Migrated to https://github.com/tabbed/sqlc-gen-python/issues/2
