### ISSUE TITLE
docker kjconroy/sqlc generate does not find sqlc.yaml

### ISSUE THREAD

**Issue by Git-me-outta-here** [kyleconroy/sqlc#1244]
### Version

Other

### What happened?

I'm running
`sudo docker run --rm -v $(pwd):/src -w /src kjconroy/sqlc generate`

but it does not use my sqlc.yaml file. instead I get:

`Unable to find image 'kjconroy/sqlc:latest' locally
latest: Pulling from kjconroy/sqlc
38b20663bd7b: Pull complete 
Digest: sha256:b8f7c468952984fc8cfa67e80fe0dcd44537c444f8b38357c4753c60fae0fad1
Status: Downloaded newer image for kjconroy/sqlc:latest
error parsing sqlc.json: file does not exist`

**Comment by amirrmonfared** [comment]
Hi,
Do you find a way to solve this problem?

**Comment by kyleconroy** [comment]
Is this still an issue with 1.12.0?
