### ISSUE TITLE
Try fuzzing the parser and see if we get any crashes

### ISSUE THREAD

**Issue by kevinburke** [kyleconroy/sqlc#1257]
### Version

1.10.0

### What happened?

Go 1.18 adds native support for fuzzing. It would be cool to pass various inputs to the sqlc query parser and see if we can find any errors or crashes in the program.

**Comment by kyleconroy** [comment]
Okay so I did this for the config and overrides section. Didn't find anything! I may try to add fuzzing support to pg_query_go at some point.
