### ISSUE TITLE
json.RawMessage does not support NULL

### ISSUE THREAD

**Issue by kyleconroy** [kyleconroy/sqlc#129]
```
sql: Scan error on column index 5, name "xxx": unsupported Scan, storing driver.Value type <nil> into type *json.RawMessage
```

**Comment by kyleconroy** [comment]
I believe we can generated the following type to fix this issue


```go
// NullRawMessage represents a json.RawMessage that may be null.
// NullRawMessage implements the Scanner interface so
// it can be used as a scan destination, similar to NullString.
type NullRawMessage struct {
	RawMessage json.RawMessage
	Valid bool // Valid is true if JSON is not NULL
}

// Scan implements the Scanner interface.
func (n *NullRawMessage) Scan(value interface{}) error {
	n.RawMessage = json.RawMessage{}
	if value == nil {
		n.Valid = false
		return nil
	}
	n.Valid = true
	return n.RawMessage.Scan(value)
}

// Value implements the driver Valuer interface.
func (n NullRawMessage) Value() (driver.Value, error) {
	if !n.Valid {
		return nil, nil
	}
	return n.RawMessage.Value()
}
```

**Comment by kyleconroy** [comment]
It appears that `json.RawMessage` does not implement the `Scanner` interface.

```
# command-line-arguments
./foo.go:24:21: n.RawMessage.Scan undefined (type json.RawMessage has no field or method Scan)
./foo.go:32:2: not enough arguments to return
./foo.go:32:21: n.RawMessage.Value undefined (type json.RawMessage has no field or method Value
```

**Comment by Mrcampbell** [comment]
We ran into this issue earlier, but this isn't really anything wrong with sqlc.  We just added a null check in our code and if it was nil, we put in an empty array.

```
	if params.SalesforceProducts == nil {
		params.SalesforceProducts = json.RawMessage([]byte("[]"))
	}
```

Definitely not ideal, but like Kyle said, no Scanner.

**Comment by Mrcampbell** [comment]
But if you find a fix, I'd love to see it!  I'll keep an eye out as well.

**Comment by zdunecki** [comment]
@mrcampbell, you can do something like this:

```go
func (n *NullRawMessage) Scan(value interface{}) error {
	if value == nil {
		n.RawMessage, n.Valid = json.RawMessage{}, false
		return nil
	}
	buf, ok := value.([]byte)

	if !ok {
		return errors.New("canot parse to bytes")
	}

	n.RawMessage, n.Valid = buf, true

	return nil
}
```

**Comment by duyker** [comment]
Not sure if it is the best way, but I was able to work around the issue by adding a `coalesce` statement in the `query.sql`

```
// query.sql

-- name: GetSomething :one
select
  t."id",
  coalesce(t."data", '[]') as "data"
from
  "public"."something" t
where
  t.id = $1
limit 1;
```

**Comment by ludusrusso** [comment]
Hi! Is someone working on this? I'm getting the same error when reading a jsonb value that can be null.

**Comment by eborst** [comment]
Would also love to see a fix for this. I'm having this issue when reading json data from postgres.

**Comment by koolay** [comment]
There is the same problem on mysql.

**Comment by idan-stripe** [comment]
@koolay I solved this for mysql using [overrides](https://docs.sqlc.dev/en/stable/reference/config.html#overrides) in sqlc.yaml:
```
overrides:
  - db_type: "json"
    go_type:
      type: "[]byte"  # workaround sqlc bug when reading null json columns
    nullable: true
```

Note that the documentation is not up to date - `go_type` [is a struct](https://github.com/kyleconroy/sqlc/issues/785) and not a string.

**Comment by GetPsyched** [comment]
Hey, @idan-stripe. I tried your fix but I still seem to be getting the same error as I was before. Have you changed anything else other than `sqlc.yaml`?

**Comment by ravayak** [comment]
Bug still not resolved in 08/13/2023.

**Comment by geertjanvdk** [comment]
I did try the `main` with #129 fix, but no luck. The `override` works nicely.

**Comment by slavapashaliuk** [comment]
I'm on v1.27.0, the `override` approach seems to not work with aggregated queries, any suggested workaround?
