### ISSUE TITLE
run sqlc via go run without install

### ISSUE THREAD

**Issue by tobiges** [kyleconroy/sqlc#1297]
Is it possible to add the option to run sqlc via `go run github.com/kyleconroy/sqlc generate`?
Similar to the way gqlgen can be used (https://github.com/99designs/gqlgen#quick-start).
This has the advantage that everyone working on the project has uses the same version (added to the go.mod file) and no installation is needed.

**Comment by hariprasadrajaram** [comment]
You can use **go:generate** in your dependent go file and run go `generate && go build`

`//go:generate sqlc generate`

**Comment by tobiges** [comment]
I know, that it is possible like this, but this way you still need to install sqlc manually.
The advantage the way gqlgen is using has, is that everybody working on the project uses the same version of sqlc and no installation is required.
I would also use it with go:generate like this:
`//go:generate go run github.com/kyleconroy/sqlc generate`

and add a "_ import" in my tools.go

**Comment by kyleconroy** [comment]
You can do this today, but you need to use the correct import path.

```
go run github.com/kyleconroy/sqlc/cmd/sqlc@latest generate
```
