### ISSUE TITLE
update function missing arguments after generate if use mysql engine 

### ISSUE THREAD

**Issue by Chenghu-w** [kyleconroy/sqlc#1320]
### Version

1.11.0

### What happened?

works fine when use postgresql
but mysql not

check the playground url

### Playground URL

https://play.sqlc.dev/p/e2215212bd066df0e7266883a198985c67a570b07b744fa9d85467a336f80afc

### What operating system are you using?

Windows

### What database engines are you using?

MySQL

### What type of code are you generating?

Go

**Comment by kyleconroy** [comment]
MySQL does not support the dollar sign parameters syntax ($N). You need to use question marks instead (?)

https://play.sqlc.dev/p/94ad04ec11dc4f7147b0894f0b8cca89098329568f5d250655e5d6758829de2c
