### ISSUE TITLE
Add support for pgx prepared statements

### ISSUE THREAD

**Issue by Yamakaky** [kyleconroy/sqlc#1351]
### Version

1.11.0

### What happened?

The code generated using the "database/sql" backend uses prepared statements while "pgx/v4" does not. Is this a missing feature?

https://github.com/kyleconroy/sqlc/blob/768ccb6cf2090706920282ad6fe0a397034d5a14/internal/codegen/golang/templates/pgx/dbCode.tmpl

https://github.com/kyleconroy/sqlc/blob/768ccb6cf2090706920282ad6fe0a397034d5a14/internal/codegen/golang/templates/stdlib/dbCode.tmpl

**Comment by Jille** [comment]
pgx automatically prepares statements on first use: https://github.com/jackc/pgx#features

**Comment by Yamakaky** [comment]
oooh, nice, I have to test this! Maybe add a comment to `emit_prepared_queries`?
