### ISSUE TITLE
Add capability to generate go-admin data model

### ISSUE THREAD

**Issue by mohammadVatandoost** [kyleconroy/sqlc#1356]
I want to add go-admin data model generator to sqlc.
Do you have any suggestion? 
I think the best way is : add another generate method to `codegen/golang/gen.go`

Do you like to add this feature to sqlc? Is it alright to send pull request for the feature?

**Comment by kyleconroy** [comment]
This is a great example of a feature that should live as a plugin outside of the main sqlc codebase. I'm going to close this for now, but will comment here once plugin support has been added.
