### ISSUE TITLE
Create Interface for better testing and easier isolation of methods

### ISSUE THREAD

**Issue by Xeoncross** [kyleconroy/sqlc#1358]
A concrete class of *Queries is created and populated with all the method receivers that actually do the database queries.

```
type Queries struct {
	db DBTX
}
...

func (q *Queries) DeleteAuthor(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteAuthor, id)
	return err
}
```

However, in order to more easily mock and test the calling code using the `*Queries` (or to follow SOLID design), can we auto generate the interface as well?

```
type Query interface {
    DeleteAuthor(ctx context.Context, id int64) error
    ....
}
```

This would make it much easier to construct in-memory or mock instances of something I can pass to my services when running tests. 

It also helps remove the tight dependency on a concrete class of `Queries` if I have many hundreds of methods. Instead I can break them down easier by purpose without having to implement all 100 'filler' methods.

So something like 
```
type Query interface {
    DeleteAuthor(ctx context.Context, id int64) error
    GetPost(ctx context.Context, id int64) error
    ....
}
```

Could become 

```
type QueryAuthor interface {
    DeleteAuthor(ctx context.Context, id int64) error
}

type QueryPost interface {
    GetPost(ctx context.Context, id int64) error
}
```

That way I can limit what I'm testing to just use `q QueryPost` without having to mock out `DeleteAuthor` and friends. If I need multiple query classes in a single test I can just use composition.

```
type QueryBlog interface {
	QueryAuthor
	QueryPost
}
```

**Comment by aaronschweig** [comment]
Hello @Xeoncross,

there actually already is such an option!

In your `sqlc.yaml` (or `sqlc.json`) you can set the `emit_interface` option to true as described [in the docs](https://docs.sqlc.dev/en/latest/reference/config.html).

I hope this helps, at least it did for me and made it testable!

**Comment by Xeoncross** [comment]
Thank you! Christmas came early!

**Comment by Xeoncross** [comment]
Actually @aaronschweig, I'd love to split up queries by FROM table so that I didn't have to [manually copy the interface methods in Querier](https://play.sqlc.dev/p/82caeabb9b4aa480f1b79e646601dd9db2347eef5e8d76301b494df7d47f54f5) since I often have a large number of methods to implement.

But this is a great start.

**Comment by erkattak** [comment]
It would be nice to be able to have separate interfaces per query file. 

For example, if I had queries in separate `.sql` files, an interface for each would be great so that I don't either have one giant interface (still fine overall), or have to manually copy individual methods from the Querier interface.
