### ISSUE TITLE
No precompiled binaries for v1.12.0

### ISSUE THREAD

**Issue by dclipca** [kyleconroy/sqlc#1422]
### Version

1.12.0

### What happened?

There are no precompiled binaries for v1.12.0.

### Playground URL

https://docs.sqlc.dev/en/stable/overview/install.html

### What operating system are you using?

Windows

### What database engines are you using?

PostgreSQL

### What type of code are you generating?

Go

**Comment by kyleconroy** [comment]
Whoops, my bad. Ran the release process and forgot to download the binaries and upload them to the GitHub release. Might be time for some more automation...
