### ISSUE TITLE
Update query builder

### ISSUE THREAD

**Issue by kevinburkemeter** [kyleconroy/sqlc#143]
A common-ish pattern is to allow three or four fields to be updated, and then issue an UPDATE query that only modifies the ones the user actually wants to set. Generally people do this by manually building a string - keeping track of $1, $2, etc. and then executing it. 

I'm wondering if sqlc could help automate this process or at least make it less error prone.

**Comment by kyleconroy** [comment]
There are two ways to accomplish this today with sqlc. 

The first is to have individual UPDATE queries and execute them in a transaction.

The other option is to use a CASE statement per field

```
UPDATE SET
  field1 = CASE update_field1 THEN value1 ELSE field1
```

Since sqlc will not generate SQL for you at runtime, these are the only two real options.
