### ISSUE TITLE
If `name` field is `NAME` no error reported and no code generated

### ISSUE THREAD

**Issue by aastein** [kyleconroy/sqlc#1441]
### Version

1.12.0

### What happened?

The the file where queries are written, I had queries like 

```
-- NAME: InsertCommentsRollupComments :exec
INSERT INTO comments_rollup_comments (comment_id, comments_rollup_id)
VALUES ($1, $2);
```

when running sqlc, sqlc did not generate the query and did not output any errror

### SQL queries

```sql
-- NAME: InsertCommentsRollupComments :exec
INSERT INTO comments_rollup_comments (comment_id, comments_rollup_id)
VALUES ($1, $2);
```

### Playground URL

https://play.sqlc.dev/p/1f1ac6adeb1a9d1efc2b01bc4e65ad20cdbda25f01f781e48cafc015700c30ba

**Comment by raymond-design** [comment]
@kyleconroy Quick question! The all-caps here shouldn't matter and should still generate a query right?

**Comment by kyleconroy** [comment]
Query annotations must start with `--name: `, not `--NAME:`
