### ISSUE TITLE
Circuit Breaker support

### ISSUE THREAD

**Issue by pooyarezaie** [kyleconroy/sqlc#1442]
I want to add optional circuit breaker support for each query function. 
Do you have any suggestions?
Do you have any plan to add this feature? 
Is it alright to send a pull request for this feature?

**Comment by kyleconroy** [comment]
No plans in the short term to support query middleware. If your using the database/sql package, you can use https://github.com/ngrok/sqlmw to implement circuit breakers.

Also, with Go 1.18 coming out soon, we may be able to use generics to more easily solve this issue.
