### ISSUE TITLE
The "sqlc.arg" doesn't accept "nullable => true"

### ISSUE THREAD

**Issue by saleh-rahimzadeh** [kyleconroy/sqlc#1446]
### Version

1.12.0

### What happened?

The `sqlc.arg` raises error when using with `nullable => true` argument:
```
sqlc.arg('user_id', nullable => true)
```
Error:
```
expected 1 parameter to sqlc.arg; got 2
```

### What operating system are you using?

Linux

### What database engines are you using?

PostgreSQL

### What type of code are you generating?

Go

**Comment by danielbprice** [comment]
Seems like https://github.com/kyleconroy/sqlc/issues/1155 is the same as this?
