### ISSUE TITLE
Proposal: add sqlc.uuid/sqlc.cuid to automatically generate id

### ISSUE THREAD

**Issue by ludusrusso** [kyleconroy/sqlc#1449]
In my use case I'm generating ID using cuid package, this is an example of code I write:

```sql
-- name: CreateStuff :exec
INSERT INTO stuff (id, field) VALUES( $1, $2);
```

```go
id := getCuid()

q.CreateStuff(ctx, db.CreateStuffParams{
    ID: id,
    Field: "xxxx"
})
```

I't would be nice a to have function to autogenerate the id stuff, something like this:

```sql
-- name: CreateStuff :exec
INSERT INTO stuff (id, field) VALUES(sqlc.cuid(), $2);
```

What do you think?

**Comment by kyleconroy** [comment]
@ludusrusso Thanks for the feature request. I'm not planning on adding any new `sqlc.` magic methods at the moment. My goal long-term is to create a true macro system so anyone can write their own extension. That's a few months await (at least) so I sadly don't have a good answer for you.
