### ISSUE TITLE
Enhancement: include sqlc version in generated files

### ISSUE THREAD

**Issue by zlymeda** [kyleconroy/sqlc#1456]
Currently, sqlc adds this comment to generated files:

```golang
// Code generated by sqlc. DO NOT EDIT.
```

It would be nice to include also the sqlc version, something like:

```golang
// Code generated by sqlc v1.12.0. DO NOT EDIT.
```

Why? If a developer is using an older version of sqlc, he/she would notice that before committing:

```diff
- // Code generated by sqlc v1.13.0. DO NOT EDIT.
+ // Code generated by sqlc v1.12.0. DO NOT EDIT.
// ...
```

What do you think?

**Comment by kyleconroy** [comment]
I don't think I'm going to add this. My main reason is that it will generate unnecessary diffs every time someone updates sqlc.

**Comment by kyleconroy** [comment]
I looked at the protoc output and realized it includes the version of protoc and the version of any plugins. I'm going to adopt that format

```
// Code generated by protoc-gen-go. DO NOT EDIT.$
// versions:$
// ^Iprotoc-gen-go v1.27.1$                                                                                                                                                                                            
// ^Iprotoc        v3.19.1$
// source: python/ast.proto$
```

**Comment by jonathangjertsen** [comment]
> I don't think I'm going to add this. My main reason is that it will generate unnecessary diffs every time someone updates sqlc.

Indeed. It would be nice to have a configuration to remove this information from the generated source for precisely this reason
