### ISSUE TITLE
MySQL/SQLite: support returning LastInsertId

### ISSUE THREAD

**Issue by housingdreams** [kyleconroy/sqlc#1459]
`:exec` only checks the error
`:execresult` returns the full [sql.Result](https://pkg.go.dev/database/sql#Result)
`:execrows` returns the sql.Result.`RowsAffected() (int64, error)`

We just need one more return type to support the full interface:

`:execlastinsertid` would just be a matter of calling `.LastInsertId()` rather than `.RowsAffected()` on the [sql.Result](https://pkg.go.dev/database/sql#Result).

This will avoid `sql.Result` database information leaking across the boundary of the `pkg.Querier` interface. It's not good for the service code to be handling DB specific method calls. This is a MySQL/SQLite issue as Postgres uses `RETURNING` so you can use `:one` instead.

Solution: [duplicate the template code used for :execrows](https://github.com/kyleconroy/sqlc/blob/4bbe1caf3744e00b6f0c92a5c75b69b08989e20b/internal/codegen/golang/templates/stdlib/queryCode.tmpl#L105-L125)

**Comment by lpintes** [comment]
Recent versions of MariaDB supports returning clause in insert statement. So perhaps fixing parser could be sufficient.

**Comment by housingdreams** [comment]
Unfortunately, there are a lot of companies still running older MySQL installs. In addition, using sqlc with products like TiDB or https://vitess.io/ would also require this.

**Comment by Jille** [comment]
(I requested this before in https://github.com/kyleconroy/sqlc/issues/1200. I agree it would be nicer to have a :execinsertid)
