### ISSUE TITLE
PostgreSQL substring() detect as wrong type

### ISSUE THREAD

**Issue by jamesli2021** [kyleconroy/sqlc#1487]
### Version

1.12.0

### What happened?

Found a bug.

PostgreSQL 14.1:
... SUBSTRING(title, 1, 10) ...

sqlc struct:
Title         []byte `json:"title"`

Could this be fix as string instead of detected as []byte data type?

### Relevant log output

```shell
See above
```

### What operating system are you using?

macOS

### What database engines are you using?

PostgreSQL

### What type of code are you generating?

Go

**Comment by kyleconroy** [comment]
Duplicate of #1450
