### ISSUE TITLE
Positional arguments in generated Go function

### ISSUE THREAD

**Issue by brentd** [kyleconroy/sqlc#1496]
The [docs](https://docs.sqlc.dev/en/stable/howto/update.html) have this example:

```sql
CREATE TABLE authors (
  id         SERIAL PRIMARY KEY,
  bio        text   NOT NULL
);

-- name: UpdateAuthor :exec
UPDATE authors SET bio = $2
WHERE id = $1;
```

Which is documented as generating the following function with positional parameters:

```go
func (q *Queries) UpdateAuthor(ctx context.Context, id int, bio string) error {
	_, err := q.db.ExecContext(ctx, updateAuthor, id, bio)
	return err
}
```

However the latest version of sqlc (v1.12.0) generates this:

```go
type UpdateAuthorParams struct {
	ID  int32
	Bio string
}

func (q *Queries) UpdateAuthor(ctx context.Context, arg UpdateAuthorParams) error {
	_, err := q.db.ExecContext(ctx, updateAuthor, arg.ID, arg.Bio)
	return err
}
```

[playground](https://play.sqlc.dev/p/8002b87d1f4b23f5fb3f0668f9bc9d81c167c3cfaf35c97892ee65e4b3a872a7)

Is this just a matter of outdated docs, or am I missing something? I prefer positional parameters in cases where there are 1-3 args; is there currently a way to get one vs. the other?

Thank you for this useful and satisfying project. :heart:

**Comment by kyleconroy** [comment]
> Is this just a matter of outdated docs, or am I missing something? 

The documentation is out dated, I'll make sure to update it before the next release.

> I prefer positional parameters in cases where there are 1-3 args; is there currently a way to get one vs. the other?

Positional arguments will be generated when there is a single argument. I'd be open to support a package-wide configuration parameter to pick this number.

**Comment by brentd** [comment]
> Positional arguments will be generated when there is a single argument. I'd be open to support a package-wide configuration parameter to pick this number.

@kyleconroy thanks! Sounds like a great opportunity to contribute as I'd like to see this.

**Comment by kyleconroy** [comment]
Discussing a solution here! https://github.com/kyleconroy/sqlc/issues/1498
