### ISSUE TITLE
Can we make WithTx input params as interface{}? 

### ISSUE THREAD

**Issue by elvizlai** [kyleconroy/sqlc#1502]
### What do you want to change?

for change generated code, `WithTx(tx *sql.Tx) *Queries`, can we change *sql.Tx same as `DBTX` or other related interface?

### What programming language backends need to be changed?

Go

**Comment by elvizlai** [comment]
@kyleconroy PTAL

**Comment by danielbprice** [comment]
@elvizlai, this may be a duplicate of #383.  There are some solutions illustrated there.
