### ISSUE TITLE
Use CockroachDB PostgreSQL parser

### ISSUE THREAD

**Issue by glerchundi** [kyleconroy/sqlc#151]
Fantastic idea & project @kyleconroy!

Just in case you find interesting, the people from CockroachDB created a pg-compatible SQL parser in pure go: https://github.com/cockroachdb/cockroach/tree/master/pkg/sql/parser.

The benefit of avoiding the cgo dependency is that it would open the project up to other platforms.

**Comment by kyleconroy** [comment]
I have two hesitations when it comes to using the CockroachDB query parser instead of [pg_query_go](https://github.com/lfittl/pg_query_go). First is incompatibilities between the two parsers. I'll need to do more investigating to make sure there aren't valid PostgreSQL queries the Cockroach parser can't handle.

The second issue is Cockroach's licensing. The query parser is licensed under the Business Source License (BSL), which is not an open-source license. I'm not entirely sure how that licenses interacts with a tool like sqlc.

**Comment by glerchundi** [comment]
> I have two hesitations when it comes to using the CockroachDB query parser instead of [pg_query_go](https://github.com/lfittl/pg_query_go). First is incompatibilities between the two parsers. I'll need to do more investigating to make sure there aren't valid PostgreSQL queries the Cockroach parser can't handle.

Maybe @mjibson or @knz have something more to say on this :) But AFAIK the parser should be fully compatible and when it comes to execute it they check the compatibility of the AST (pointing you to the specific issue in case whatever thing in query is not supported).

> The second issue is Cockroach's licensing. The query parser is licensed under the Business Source License (BSL), which is not an open-source license. I'm not entirely sure how that licenses interacts with a tool like sqlc.

That's a fair point, maybe they could told you how possible is to use freely.

**Comment by knz** [comment]
A couple points:

- cockroachdb's parser definitely does nog support all of postgres' grammar.

- you can't simply "adopt a parser". A parser is a function from text to an AST data structure. If you reuse a parser you're also choosing to reuse the AST it was made for. However, an AST is also tightly bound to the rest of the language analyzer. In particular CockroachDB (currently) hangs off type checking and scalar evaluation as methods of AST nodes, with different semantics from postgres. I doubt that's what's desired here.

- FWIW the CockroachDB tree is not 'go build'-compatible and the parsing code in particular uses a 4-step Makefile

(The licensing code is only a minor point, we can consider forking an Apache-licensed alternative for interested parties)
-- 
Verstuurd vanaf mijn Android apparaat met K-9 Mail. Excuseer mijn beknoptheid.

**Comment by kyleconroy** [comment]
I was going through older issues and noticed that I never responded to this one.

@knz thanks for the explanation. I think it solidifies my opinion that we should not be using the Cockroach parser at this time.
