### ISSUE TITLE
output_querier_file_name is broken

### ISSUE THREAD

**Issue by Indribell** [kyleconroy/sqlc#1510]
### Version

1.12.0

### What happened?

sqlc.yaml:

output_querier_file_name: "xxxx.go" 

The configuration option does not work and the compiler always picks the original queries filename.

Side note: output_db_file_name and output_models_file_name work without any issue, only output_**querier**_file_name is broken.

**Comment by kyleconroy** [comment]
The `output_querier_file_name` controls the name of the file for the querier interface, not the query files. You can see it working correctly [here](https://github.com/kyleconroy/sqlc/tree/main/internal/endtoend/testdata/output_file_names/stdlib/).

I think you want `output_files_suffix`. An example on how to use that can be found [here](https://github.com/kyleconroy/sqlc/blob/main/internal/endtoend/testdata/output_files_suffix/stdlib/sqlc.json).
