### ISSUE TITLE
Add query annotation for zero or one

### ISSUE THREAD

**Issue by skabbes** [kyleconroy/sqlc#1540]
### What do you want to change?

**Problem**
There are query annotations for exactly 1 row `:one`, or 0..n rows `:many`.  I think a query annotation that was meant to deal with 0..1 queries would also make sqlc generated code possibly a lot more ergonomic / idiomatic.  Consider the following query:

```sql
-- thing.name is unique (either by application defined uniqueness, or by unique constraints in the database)

-- name: ThingByName :one
SELECT * FROM thing
WHERE
 "name" = sqlc.arg('name');
```

This generates a query something more or less like this:
```go
func (q *Queries) ThingByName(ctx context.Context, db DBTX, name string) (Thing, error) {
    // ... omitted ...
}
```

And if "thing with name does not exist" is not an unexpected state (as defined by the application), then the code would probably use it something like this.

```go
err, thing := queries.ThingByName(ctx, db, "name")
if err == sql.ErrNoRows {
  // a thing with name does not yet exist
} else if err != nil {
  return err
} else {
  // a thing with name _does_ exist
}
```

**Possible Solution**
I think if there was a way to tell sqlc that this was expected to be zero or 1 result (a query annotation), more idiomatic code could be generated.  I believe this only affects Go.

```sql
-- name: ThingByName :oneorzero
SELECT * FROM thing
WHERE
 "name" = sqlc.arg('name');
```

This could possibly generate one of 2 APIs that might be more idiomatic
```go
// do _not_ return ErrNoRows, and return a nil pointer to Thing if it was not found
func (q *Queries) ThingByName(ctx context.Context, db DBTX, name string) (*Thing, error) 

// And maybe a Go Generics version using option / optional / maybe type.
func (q *Queries) ThingByName(ctx context.Context, db DBTX, name string) (Option[Thing], error) 
```

In my (extremely limited) knowledge of Kotlin, this would be the difference between returning `Thing` vs `Thing?`.

### What programming language backends need to be changed?

Go, Kotlin

**Comment by skabbes** [comment]
I forgot to mention that I would be more than happy to write the code for this (if needed) if it is OK / approved / aligned with the project goals.

**Comment by kyleconroy** [comment]
@skabbes Apologies for not reviewing this proposal earlier! I should have rewarded you for writing a thoughtful and thorough proposal. 

I personally don't think the difference between `:oneorzero` and `:one` is big enough to warrant a new query type. That said, I'd love to work with you on figuring out how to support these types of new query types via plugins.

**Comment by skabbes** [comment]
Ya - more and more as I think about sqlc - I kind of think the code generation part should be decoupled completely from the "core engine".  The work you did on the wasm plugins should help that quite a bit, but "sqlc core" still needs to a mechanism to annotate queries, parameters, or output types (in my opinion, I know that would be a heated debate haha)

Thanks for the feedback regardless.

**Comment by JamesArthurHolland** [comment]
Was there any movement on this? It's a feature I'd like also

**Comment by skabbes** [comment]
I'm afraid not :(

**Comment by skabbes** [comment]
Alright, @JamesArthurHolland I have a bit of an update here.   FYI @kyleconroy too, I think this might help out some people wresting with migrating from systems that returned nil rows for `:maybeone` type of queries ( in case you want to mention in the docs perhaps).

I've been playing with a pattern that might be useful, the idea is to write a `Nullable` function that takes 2 parameters, and it checks specifically for the 2 types of errors that could indicate an error (depending on what driver you use).

First, here is how it would be used:

```go
row, err := Nullable(queries.New().MyTableByID(sqlConn, id))
if err != nil {
  // a sql error occurred
  return err
}
 if row == nil {
   // a row with id = `id` does not exist, this is not an error
 }
```

And here is the non-generic, and generic implementations of `Nullable`.

```go
// Nullable is meant to wrap around ':one' queries in sqlc, and make it nullable
func Nullable(row queries.MyTable, err error) (*queries.MyTable, error) {
	if err == nil {
		return &row, nil
	}

	if err == pgx.ErrNoRows || err == sql.ErrNoRows {
		return nil, nil
	}

	return nil, err
}

// A generic (go 1.18 and higher) version of the same function, so you don't have to write one of these per-table
func Nullable[T any](row T, err error) (*T, error) {
	if err == nil {
		return &row, nil
	}

	if err == pgx.ErrNoRows || err == sql.ErrNoRows {
		return nil, nil
	}

	return nil, err
}
```
