### ISSUE TITLE
JSON intermediate output for standalone codegen executables?

### ISSUE THREAD

**Issue by dstrelau** [kyleconroy/sqlc#1544]
Would you be open to a PR that adds a JSON output in the manner @skabbes suggests in [this comment](https://github.com/kyleconroy/sqlc/issues/1470#issuecomment-1086681778)?

It looks like outputting the `plugin.CodeGenRequest` as JSON would be pretty trivial and provide all the relevant info you'd need to write a standalone generator.

**Comment by kyleconroy** [comment]
I think this is a great idea and should probably be our first official plugin. Sadly, plugin support probably won't make it into 1.14, as we're still waiting on wasmtime-go to ship with native M1 support. In the meantime, we could implement this as an experimental codegen backend, similar to the Python support, and remove it once plugins have shipped.

**Comment by dstrelau** [comment]
Closed by https://github.com/kyleconroy/sqlc/pull/1565! Thanks @kyleconroy!
