### ISSUE TITLE
Query Result Iterator

### ISSUE THREAD

**Issue by ebonetti** [kyleconroy/sqlc#155]
Hello sqlc folks, this package does really give a peace of mind, thanks!! :+1: 

I noticed that you are tagging query return cardinality: :exec (aka none), :one, :many. In the latter, :many, have you ever considered the case in which the whole result doesn't fit in memory? Apart from using DB.QueryContex is there any typed work-around?

Keep up the great work,
Enrico Bonetti Vieno

**Comment by kyleconroy** [comment]
I haven't tackled the case where query results don't fit into memory. If I was writing the queries, I'd fix it by doing paging myself with filtering and limits. However, I get that there are times when you'd rather just stream the results.

I could imagine a world where tag a query `:iter` and generate code like this:

```sql
-- name: StreamAuthors :iter
SELECT * from authors;
```

```go
package db

const listAuthors = `-- name: StreamAuthors :many
SELECT id, name, bio FROM authors
ORDER BY name
`

type AuthorStream struct {
  rows *sql.Rows
}

func (s *AuthorStream) Next() bool {
    return s.rows.Next()
}

func (s *AuthorStream) Close() error {
    return s.rows.Close()
}

func (s *AuthorStream) Err() error {
    return s.rows.Err()
}

func (s *AuthorStream) Scan() (Author, error) {
    var i Author
    return i, rows.Scan(&i.ID, &i.Name, &i.Bio)
}

func (q *Queries) StreamAuthors(ctx context.Context) (*AuthorStream, error) {
    rows, err := q.db.QueryContext(ctx, listAuthors)
    if err != nil {
        return nil, err
    }
    return &AuthorStream{rows}, nil
}
```

**Comment by ebonetti** [comment]
Paging, I didn't think about it.. 🤔 As for our parallel world, maybe even a closure iterator could work:

```
package db

const streamAuthors = `-- name: StreamAuthors :iter
SELECT id, name, bio FROM authors
ORDER BY name
`

func (q *Queries) StreamAuthors(ctx context.Context) func() (Author, error) {
	rows, queryErr := q.db.QueryContext(ctx, streamAuthors)
	if queryErr != nil {
		return func() (Author, error) {
			return Author{}, queryErr
		}
	}

	return func() (a Author, err error) {
		if !rows.Next() {
			return Author{}, rows.Err()
		}

		return a, rows.Scan(&a.ID, &a.Name, &a.Bio)
	}
}
```

**Comment by kyleconroy** [comment]
The closure iterator won't work as written since you need to expose a `Close` method. Maybe you could return two funcs?

**Comment by ebonetti** [comment]
Yesterday I [checked](https://golang.org/pkg/database/sql/#Rows.Close): it doesn't really say "Close must be called".. 😜

To close prematurely I would use the context: to me this context use feels right since the closure is a way to iteratively explore the context call results. How do you feel about it?

```
package db

const streamAuthors = `-- name: StreamAuthors :iter
SELECT id, name, bio FROM authors
ORDER BY name
`

func (q *Queries) StreamAuthors(ctx context.Context) func() (Author, error) {
	rows, queryErr := q.db.QueryContext(ctx, streamAuthors)
	if queryErr != nil {
		return func() (Author, error) {
			return Author{}, queryErr
		}
	}

	ctx, cancel := context.WithCancel(ctx)
	go func() {
		<-ctx.Done()
		rows.Close() //Close is safe for concurrent use.
	}()

	return func() (a Author, err error) {
		if !rows.Next() {
			//Cancel used to terminate child context, Close already called by Next.
			cancel()
			return Author{}, rows.Err()
		}

		return a, rows.Scan(&a.ID, &a.Name, &a.Bio)
	}
}
```

**Comment by kyleconroy** [comment]
The above code snippet still has concurrency issues. Since the cancel function isn't returned, a caller would need to continue to call the returned function until `rows.Next` returns `false`. The complexity of the returned closure leads me to believe sqlc shouldn't generate this type of code right now. 

If more people need this functionality, we can revisit this in the future.

**Comment by ebonetti** [comment]
I probably would not use it in production myself: even if Rows itself owns a connection to the database, so it's not really lightweight, still using the goroutine feels like an overkill.

There was a problematic corner case: say Scan returns an error, the caller would stop calling the iterator, then the goroutine would become a zombie until context cancellation, which wouldn't be otherwise required. Thanks for noticing.


```
package db

const streamAuthors = `-- name: StreamAuthors :iter
SELECT id, name, bio FROM authors
ORDER BY name
`

func (q *Queries) StreamAuthors(ctx context.Context) func() (Author, error) {
	rows, queryErr := q.db.QueryContext(ctx, streamAuthors)
	if queryErr != nil {
		return func() (Author, error) {
			return Author{}, queryErr
		}
	}

	ctx, cancel := context.WithCancel(ctx)
	go func() {
		<-ctx.Done()
		rows.Close()
	}()

	return func() (a Author, err error) {
		if !rows.Next() || rows.Scan(&a.ID, &a.Name, &a.Bio) != nil {
			cancel()
		}
		return a, rows.Err()
	}
}
```

Given that Rows is concurrent safe, I don't see any other concurrency issues, so this code should work like a charm:

```
	ctx, cancel := context.WithCancel(context.Background())
	defer cancel()

	next := q.StreamAuthors(ctx)

	var a Author
	var err error
	for a, err = next(); err != nil; a, err = next() {
		//Do something with a
		if stopCondition {
			break
		}
	}
```

If more people need this functionality, I'm more than happy to help with the interface design.

Keep up the great work,
Enrico Bonetti Vieno

**Comment by eivindr** [comment]
Hi, sorry for bumping a closed issue. What if :iter generated something like

```
const streamAuthors = `-- name: StreamAuthors :iter
SELECT id, name, bio FROM authors
ORDER BY name
`

type streamAuthorsIter func(author Author) error

func (q *Queries) StreamAuthors(ctx context.Context, iter streamAuthorsIter) error {
	rows, err := q.db.QueryContext(ctx, streamAuthors)
	if err != nil {
		return err
	}
	defer rows.Close()

	for rows.Next() {
		var a Author
		if err := rows.Scan(
			&a.ID,
			&a.Name,
			&a.Bio,
		); err != nil {
			return err
		}

		err = iter(a)
		if err != nil {
			return err
		}
	}
	if err := rows.Close(); err != nil {
		return err
	}
	if err := rows.Err(); err != nil {
		return err
	}
	return nil
}
```

Compared to :many its basically adding a func type and calling the passed iter function instead of appending.

**Comment by pcriv** [comment]
@eivindr maybe you can just open the PR and we can continue the discussion there?
