### ISSUE TITLE
Don't generate  sql.NullString or sql.NullInt64  and so on

### ISSUE THREAD

**Issue by DiegoFelipe** [kyleconroy/sqlc#1552]
### What do you want to change?

I saw that when a column on a table is null, has no default value, sqlc generates the model with these type: sql.NullString, sql.NullInt64 and others

there are some columns in my db that I want to leave it  nullable, but I don't want the generate type on the model to be sql.null

how can I achieve it?

### What database engines need to be changed?

PostgreSQL

### What programming language backends need to be changed?

Go

**Comment by egtann** [comment]
You can override the type in your sqlc configuration file. For instance, I have:

```
"overrides": [
		{
			"db_type": "pg_catalog.int8",
			"go_type": {
				"import": "github.com/volatiletech/null/v9",
				"package": "null",
				"type": "Int64",
				"pointer": false
			},
			"nullable": true
		}, {
			"db_type": "pg_catalog.int4",
			"go_type": {
				"import": "github.com/volatiletech/null/v9",
				"package": "null",
				"type": "Int32",
				"pointer": false
			},
			"nullable": true
		}, {
			"db_type": "pg_catalog.int2",
			"go_type": {
				"import": "github.com/volatiletech/null/v9",
				"package": "null",
				"type": "Int16",
				"pointer": false
			},
			"nullable": true
		}
               ...
```

The docs describe the options.

**Comment by kyleconroy** [comment]
@egtann Thanks for the help. You can learn more about type overrides here: https://docs.sqlc.dev/en/stable/reference/config.html#type-overrides
