### ISSUE TITLE
Possible support for pgx v5 and compatibility with v4

### ISSUE THREAD

**Issue by thulasi-ram** [kyleconroy/sqlc#1555]
### What do you want to change?

I recently tried out sqlc with pgx v5 which is currently in [alpha](https://github.com/jackc/pgx/issues/1169). 

**I want to enquire on the path forward for v5 upgrade and if there's a plan to accommodate the changes.** 
If there is none kindly consider this as a placeholder. Feel free to close this issue if it is in the works already. 

I will jot down a few things that I noticed that needed to be changed. 
1. [Line 120 in codegen.golang.imports](https://github.com/kyleconroy/sqlc/blob/aade08708ea0c4aa88fe7b5dbe929e325c323ccd/internal/codegen/golang/imports.go#L120) must change to import from v5/pgconn since pgconn inside the v5 package itself as described in [pgx changelog](https://github.com/jackc/pgx/blob/v5-dev/CHANGELOG.md).
2. Currently we have provision for one pgx package only [here](https://github.com/kyleconroy/sqlc/blob/56d7417836643aa510e9a45b3ad558d0de3896d7/internal/codegen/golang/sql_package.go#L6). We will need to alter it if compatibility with v4 must be maintained.
3. pgtype imports and enhancements

### What database engines need to be changed?

PostgreSQL

### What programming language backends need to be changed?

Go

**Comment by kyleconroy** [comment]
> We will need to alter it if compatibility with v4 must be maintained.

Compatibility is the most important thing; we;ll need to continue to support `v4`. Thankfully we named the pgx `sql_package` identifier `pgx/v4`, so it should be straightforward to add support under `pgx/v5`.

**Comment by thulasi-ram** [comment]
Sure makes sense.
