### ISSUE TITLE
please support raw str interpolation

### ISSUE THREAD

**Issue by elvizlai** [kyleconroy/sqlc#1564]
### What do you want to change?

Like mybatis, the sqlc variable are all `@var`, like mybatis `#{var}`. But sometimes we need raw str injection, working samiliar as mybaits `${}`.

For example `order by`, we have some code that can generate sql safely, we want just inject the generated sql to query.

```
select * from a order by #sort;

or

select * from a order by @sort::raw; -- with ::raw suffix means raw str injection;
```

**Comment by kyleconroy** [comment]
Thanks for the feature request. Supporting something like mybaits isn't currently planned. I may add something to support this in the future, but not for now.
