### ISSUE TITLE
Generate null types that support JSON marshalling/unmarshalling

### ISSUE THREAD

**Issue by saheljalal** [kyleconroy/sqlc#1593]
### What do you want to change?

First off, thanks for making this amazing project. It's really great and super useful.

One of the things that's not ideal for my workflow is after generating all the models, queries, and params, etc., they are using the default go `sql` null types. Unfortunately, that means I can't use these directly in request and response paths without transforming to intermediate types.

For example, this is generated with `sql.NullString` and `sql.NullTime`:
```go
type Identity struct {
	ID                string         `db:"id" json:"id"`
	CreatedAt         time.Time      `db:"created_at" json:"createdAt"`
	UpdatedAt         time.Time      `db:"updated_at" json:"updatedAt"`
	DeletedAt         sql.NullTime   `db:"deleted_at" json:"deletedAt"`
	State             string         `db:"state" json:"state"`
	StateChangedAt    time.Time      `db:"state_changed_at" json:"stateChangedAt"`
	Traits            string         `db:"traits" json:"traits"`
	TraitsType        string         `db:"traits_type" json:"traitsType"`
	PublicMetadata    string         `db:"public_metadata" json:"publicMetadata"`
	ProtectedMetadata string         `db:"protected_metadata" json:"protectedMetadata"`
	CreatedByID       sql.NullString `db:"created_by_id" json:"createdByID"`
}
```

Is there any possibility to add a configuration option to use custom null types from another package which support JSON transformations like these:
- https://github.com/gobuffalo/nulls
- https://github.com/guregu/null

I hacked a post generation script that basically finds/replaces all the types to supported ones and imports the package but I feel dirty. Thanks for considering.

### What database engines need to be changed?

PostgreSQL, MySQL

### What programming language backends need to be changed?

Go

**Comment by RadhiFadlillah** [comment]
This is already doable by using [type overrides](https://docs.sqlc.dev/en/latest/reference/config.html#type-overrides) in config. For example, here is my configuration:

```json
{
  "version": 1,
  "packages": [
    {
      "engine": "mysql",
      "name": "sqldb",
      "path": "internal/sqldb",
      "schema": "./sql/schema",
      "queries": "./sql/query"
    }
  ],
  "overrides": [
    {
      "db_type": "varchar",
      "nullable": true,
      "go_type": "github.com/guregu/null.String"
    },
    {
      "db_type": "int",
      "nullable": true,
      "go_type": "github.com/guregu/null.Int"
    }
  ]
}
```

**Comment by saheljalal** [comment]
@RadhiFadlillah Thanks so much, let me try this out. I figured there had to be a way but couldn't quite figure out the overrides based on the documentation.

**Comment by hamza72x** [comment]
For `postgres`

```json
{
    "version": 1,
    "packages": [
        {
            "name": "db",
            "path": "./db/sqlc",
            "queries": "./db/query/",
            "schema": "./db/migration/",
            "engine": "postgresql",
            "emit_json_tags": true,
            "emit_prepared_queries": false,
            "emit_interface": true,
            "emit_exact_table_names": false,
            "emit_empty_slices": true
        }
    ],
    "overrides": [
        {
            "go_type": "github.com/gobuffalo/nulls.String",
            "db_type": "pg_catalog.varchar",
            "nullable": true
        }
    ]
}
```
