### ISSUE TITLE
Expose query strings

### ISSUE THREAD

**Issue by danthegoodman1** [kyleconroy/sqlc#1602]
### What do you want to change?

By having the variables starting with an uppercase, as an option, we can more easily create prepared statements.

For example with pgxpool running AfterConnect to prepare all the statement

### What database engines need to be changed?

PostgreSQL

### What programming language backends need to be changed?

Go

**Comment by yiplee** [comment]
https://docs.sqlc.dev/en/latest/reference/config.html

```emit_exported_queries``` & ```emit_prepared_queries``` are what you want.

**Comment by hexcowboy** [comment]
I'm curious how you're using pgxpool, I can't seem to figure out how to configure it without manually overwriting the file
