### ISSUE TITLE
`:many` query returns `nil` slice on empty result

### ISSUE THREAD

**Issue by gnuletik** [kyleconroy/sqlc#1618]
### Version

1.13.0

### What happened?

When executing a `:many` query that returns an empty slice, the returned slice is nil.

e.g.
With this query,
```sql
-- name: GetItems :many
SELECT * FROM items;
```

The following code is generated
```go
func (q *Queries) GetItems(ctx context.Context) ([]*Item, error) {
	rows, err := q.db.Query(ctx, getItems)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Item
	for rows.Next() {
		var i Item
		if err := rows.Scan(
			&i.ID,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
```

```go
func main() {
  items, err := db.GetItems(context.Background())
  fmt.Println("items is nil: ", items == nil) // true
  fmt.Println("err is nil: ", err == nil) // true
}
```

IMO, an empty array should be returned instead of `nil`.

For the usecase, it can be an issue when you want to serialize `items` as JSON because it gets serialized as `null` instead of an empty array (`[]`).

As a fix, it's possible to change the following line in the generated function: 

```diff
- 	var items []*Item
+	items := []*Item{}
```

I can open a PR if that sounds good to you.

Thanks!

**Comment by kyleconroy** [comment]
You can change this behavior by setting `emit_empty_slices` to true.

```
emit_empty_slices:
    If true, slices returned by :many queries will be empty instead of nil. Defaults to false.
```

**Comment by gnuletik** [comment]
Thanks for the fast answer @kyleconroy! Sorry, I missed that but it does exactly what I need.
Thanks for this great library also!
