### ISSUE TITLE
Proposal: :map=some_field output type

### ISSUE THREAD

**Issue by Jille** [kyleconroy/sqlc#1621]
### What do you want to change?

Hi.

I often find myself writing queries like `SELECT some_field, COUNT(*) FROM table GROUP BY some_field`, calling the generated sqlc function and then doing a loop to convert that to a map[string]int.

It would save my project a lot of boilerplate code if we could instead do something like this:

```
-- name: NumberOfSomeFields :map=some_field
SELECT some_field, COUNT(*) FROM table GROUP BY some_field
```

which would generate a function returning `map[typeof(a)]NumberOfSomeFieldsRow`.

If you approve this feature, I'll send a PR.

### What database engines need to be changed?

PostgreSQL, MySQL

### What programming language backends need to be changed?

Go

**Comment by kyleconroy** [comment]
I'd love to support something like this in the future, but right now I have no plans to implement it this.

**Comment by Jille** [comment]
Would you approve a PR if I send it?
