### ISSUE TITLE
How to use with pgx driver

### ISSUE THREAD

**Issue by LBK2K** [kyleconroy/sqlc#1635]
- I try to use pgx like this
![image](https://user-images.githubusercontent.com/99190855/169688021-7ce72863-4d93-483e-a4ba-2f707da3ea3a.png)

And a get this error
![image](https://user-images.githubusercontent.com/99190855/169687928-afeba0ec-67c9-48af-b990-97f1c1c60af4.png)

**Comment by topheruk** [comment]
have you looked at [this](https://github.com/kyleconroy/sqlc/blob/main/examples/batch/sqlc.json)?

if you haven't add `"sql_package": "pgx/v4"` to your config file

**Comment by LBK2K** [comment]
I have searched but don't see that
