### ISSUE TITLE
All Sequence/Index Relations Display "relation does <relation> does not exist" on Trunk

### ISSUE THREAD

**Issue by ryan-berger** [kyleconroy/sqlc#1639]
### Version

1.13.0

### What happened?

As I was trying to debug another sqlc issue to implement a fix, I built a development version with `make sqlc-dev`, and got:

```
relation "xxx_idx" does not exist
```

Which does not happen on 1.13. I don't have time to investigate this thoroughly tonight, but it looks like it comes from this commit: [dfe438](https://github.com/kyleconroy/sqlc/commit/dfe438611f77f1ce9dece3d2d7205796595dae5c)

~~It also seems that the metadata is always pointing that the compilation error is coming from 1:1 no matter where the error is coming from.~~ (EDIT: this happens no matter the version, so ignore this)

cc @jakoguta 

### Relevant log output

```shell
# package test
query.sql:1:1: relation "temp_idx" does not exist
query.sql:1:1: relation "temp_seq" does not exist
```

### Database schema

```sql
CREATE TABLE temp(a TEXT);

CREATE INDEX temp_idx ON temp(a);
ALTER INDEX temp_idx ATTACH PARTITION temp_partition_idx;


CREATE SEQUENCE temp_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

ALTER TABLE temp_seq OWNER TO a;
```

### SQL queries

```sql
N/A
```

### What operating system are you using?

Linux

### What database engines are you using?

PostgreSQL

### What type of code are you generating?

Go

**Comment by jakoguta** [comment]
Let me investigate this issue and report back.

**Comment by jakoguta** [comment]
@ryan-berger you were right the commit: [dfe438](https://github.com/kyleconroy/sqlc/commit/dfe438611f77f1ce9dece3d2d7205796595dae5c) introduced a bug. I have made a PR #1640 to fix the bug. I have also used your example in the endtoend test to ensure this fix is solid. Thank you for catching and investigating the bug.
