### ISSUE TITLE
Permission dennied

### ISSUE THREAD

**Issue by codernirmalnp** [kyleconroy/sqlc#1675]
### Version

1.14.0

### What happened?

Permission dennied while  sqlc generate

### Relevant log output

```shell
package db
db/migration/000001_add_user.up.sql:1:1: open /home/nirmal/Desktop/goauth/db/migration/000001_add_user.up.sql: permission denied
while sqlc generate
```

### Configuration
version: 1
packages:
  - name: "db"
    path: "./db/sqlc"
    queries: "./db/query/"
    schema: "./db/migration/"
    engine: "postgresql"
    emit_json_tags: true
    emit_prepared_queries: true
    emit_interface: false
    emit_exact_table_names: false

_No response_

### What operating system are you using?

Linux

### What database engines are you using?

PostgreSQL

### What type of code are you generating?

Go

**Comment by kyleconroy** [comment]
This appears to be a permissions error on your end. You should make sure that the user running sqlc has access to that directory on your computer.

**Comment by codernirmalnp** [comment]
Thanks the cause is i have run migrate by sudo command but sqlc doesnot run on sudo command thats a cause , Thanks for your respose, have a great development. Thanks for your contribution on this package

**Comment by GirishBhutiya** [comment]
I also have the same issue project is in another partition but provided all permission but still it not working.

**Comment by adiatma85** [comment]
Have same problem with guy above Me. The quick solution is to change the project directory to your main partition. Anyone know how to solve the permission issue without changing the project directory?

Thanks in advance

**Comment by GirishBhutiya** [comment]
Yes I have move project to main partition and do it.

**Comment by TuanChill** [comment]
I have same problem when i run "sqlc generate"
Log output:
```
/mnt/d/BackendGo/simple-bank/db/sqlc/account.sql.go: open /mnt/d/BackendGo/simple-bank/db/sqlc/account.sql.go: permission denied
Error: open /mnt/d/BackendGo/simple-bank/db/sqlc/account.sql.go: permission denied
```

Try adding sudo like this "sudo sqlc generate".
That work for me.
Good luck!!!
