### ISSUE TITLE
No release binaries for 1.14.0

### ISSUE THREAD

**Issue by alecthomas** [kyleconroy/sqlc#1679]
### Version

1.14.0

### What happened?

https://github.com/kyleconroy/sqlc/releases/tag/v1.14.0 does not contain any binaries.

### What operating system are you using?

macOS

### What database engines are you using?

MySQL

### What type of code are you generating?

Go

**Comment by kyleconroy** [comment]
Sorry about that, my release automation scripts don't upload the binaries automatically. This has been fixed.

**Comment by alecthomas** [comment]
Thank you! Love your work.
