### ISSUE TITLE
timestamptz support

### ISSUE THREAD

**Issue by Kale-Grabovski** [kyleconroy/sqlc#168]
I just tried to run `sqlc generate` for the first time and got an error "unknown Postgres type: timestamptz". I search through your repo and found only `pg_catalog.timestamptz` at case statement. What does that mean? Should I set my column type to that value?

**Comment by kyleconroy** [comment]
Sounds like a bug to me. Any chance you could include the CREATE TABLE
statement? Also the  column type as written in your DDL would also work.

**Comment by kyleconroy** [comment]
@Kale-Grabovski the latest version should be fixed. Let me know if you're still seeing the issue.

**Comment by Kale-Grabovski** [comment]
Just a simple table like this does not work.
```CREATE TABLE users (
    id uuid NOT NULL,
    name text NOT NULL,
    created timestamptz NOT NULL DEFAULT now(),
    updated timestamptz NULL,
    CONSTRAINT users_pk PRIMARY KEY (id)
)```

**Comment by Kale-Grabovski** [comment]
Thanks a lot Kyle!
