### ISSUE TITLE
TEXT[] does not support NULL

### ISSUE THREAD

**Issue by maxhawkins** [kyleconroy/sqlc#171]
```sql
CREATE TABLE foo (bar TEXT[])
```

Generates
```go
type Foo struct {
  Bar []string
}
```

Which fails to scan if `bar = NULL`. Instead, maybe it should be:

```go
type Foo struct {
  Bar pq.StringArray
}
```
which handles `NULL`.

**Comment by kyleconroy** [comment]
> Which fails to scan if bar = NULL.

This actually isn't true. If `bar` is NULL, Scan will return an empty slice.

```sql
CREATE TABLE foo (
        id text,
        tags text[]
);

INSERT INFO foo (id, tags) VALUES ('foo-array', NULL);

-- name: ListFoo :many
SELECT * FROM foo; 
```

Calling `ListFoo` will succeed and return a single row with an empty slice and null ID.

```go
rows, err := q.ListFoo(ctx)                                                                                                                                                           log.Println(rows)
$ 2019/12/16 13:51:41 [{{foo-array true} []}]
```

However, if the array contains a null item, the Scan will fail.

```
playground=# insert into foo (id, tags) values ('foo-array', array[NULL]);
INSERT 0 1
playground=# \q
$ ./sqlc-playground 
2019/12/16 13:54:07 []
2019/12/16 13:54:07 sql: Scan error on column index 1, name "tags": pq: parsing array element index 0: cannot convert nil to string
```

I've opened #185 to track the issue with NULL array elements.

**Comment by maxhawkins** [comment]
You're right, I was mistaken here. My issue was related to some old sqlx code that the sqlc code was interacting with that had the wrong types.

Switching it to sqlc revealed the type issue and fixed my problem.
