### ISSUE TITLE
SELECT pg_advisory_lock($1) (details: pq: unknown function: pg_advisory_lock()) in command line

### ISSUE THREAD

**Issue by lethienhoang** [kyleconroy/sqlc#1726]
### Version

1.14.0

### What happened?

Steps to Reproduce

Run "migrate -path internal/sqlc/migrations -database $(DB_URL) -verbose up"
I ran migrate with the following options and get SELECT pg_advisory_lock($1) (details: pq: unknown function: pg_advisory_lock())
I'm using CoakroachDB online
Expected Behavior
It should be apply new schemas to databases

### What operating system are you using?

macOS

### What database engines are you using?

PostgreSQL

### What type of code are you generating?

Go

**Comment by kyleconroy** [comment]
Cockroach DB does not support pg_advisory_lock. The error you're seeing is a runtime error, not a sqlc error.

https://github.com/cockroachdb/cockroach/issues/13546
