### ISSUE TITLE
passing empty slice to parameter become NULL in SQL

### ISSUE THREAD

**Issue by halwhite** [kyleconroy/sqlc#1731]
### Version

1.14.0

### What happened?

nil slice as array parameter is passed as NULL in SQL.

Expected behavior: nil slice should be passed as an empty array in SQL.

sample case:
SQL
```sql
-- name: TestIDs :one
SELECT '1' != ALL(@ids::text[]);
```

golang
```golang
package main

import (
	"fmt"
	"context"
	"database/sql"
	"log"
	"github.com/halwhite/id-test/db"
	_ "github.com/lib/pq"
)

func main() {
	conn, err := sql.Open("postgres", "postgres://root:root@localhost:5432?sslmode=disable")
	if err != nil {
		log.Fatal(err)
	}
	defer conn.Close()
	q := db.New(conn)
	
	var ids []string
	ret, err := q.TestIDs(context.Background(), ids)
	if err != nil {
		log.Fatal(err)
	}
	fmt.Println(ret)
}
```

Running this code emits error: 
```
2022/07/08 21:35:23 sql: Scan error on column index 0, name "?column?": sql/driver: couldn't convert <nil> (<nil>) into type bool
exit status 1
```

This is because `ids` is passed as `NULL`, and the query become `SELECT '1' != ALL(NULL)` and this returns `NULL`.

---
Changing `var ids []string` to `ids := make([]string, 0)` fixes this problem, but I wish sqlc to handle `nil slice` and `empty slice` equivalently.

### Relevant log output

```shell
sql: Scan error on column index 0, name "?column?": sql/driver: couldn't convert <nil> (<nil>) into type bool
```

### SQL queries

```sql
-- name: TestIDs :one
SELECT '1' != ALL(@ids::text[]);
```

### Configuration

```yaml
{
  "version": "1",
  "packages": [
    {
      "path": "db",
      "engine": "postgresql",
      "schema": "query.sql",
      "queries": "query.sql"
    }
  ]
}
```

### Playground URL

https://play.sqlc.dev/p/7287ce1722f498b7320eeb7a75602f7fe8318b247f651000494d2cfa91cc8fd8

### What operating system are you using?

macOS

### What database engines are you using?

PostgreSQL

### What type of code are you generating?

Go

**Comment by kyleconroy** [comment]
As you noted, the workaround here is to create a zero-length slice using `make`. 

This code is not part of sqlc. This is how`lib/pq` handles slices. You'll need to open up an issue there if you'd like to see this changed.
