### ISSUE TITLE
Golang own error handling

### ISSUE THREAD

**Issue by FlymeDllVa** [kyleconroy/sqlc#1742]
### What do you want to change?

Is there no way to make a decorator that handles errors now? I want the generated functions to immediately return an error, which can be caught through errors.Is.

### What programming language backends need to be changed?

Go

**Comment by danielbprice** [comment]
Could you give a concrete example?

**Comment by FlymeDllVa** [comment]
@danielbprice 

I would like to be able to create my own error handlers, for example put in store ErrNotFound and if there is an error sqlc itself will try to run it through my error handler function. Without it, I have to call the function myself after calling the handle. It's very inconvenient to do the same thing everywhere.
I would also like to be able to not generate db.go


```go
result1, err := store.Method1
if err != nil {
  err = store.HandleError(err)
  switch {
    case errors.Is(err, store.ErrNotFound):
    ...
  }
}

```
=>
```go
result1, err := store.Method1
switch {
  case errors.Is(err, store.ErrNotFound):
  ...
}
```

**Comment by kyleconroy** [comment]
@FlymeDllVa Sorry, right now this isn't going to be worked on. You can always [write a plugin](https://docs.sqlc.dev/en/stable/guides/plugins.html) to generate different error handling code.

**Comment by FlymeDllVa** [comment]
@kyleconroy 

I tried to make my own plugin, but I was faced with the fact that the import is done from internal, what am I doing wrong?
```use of internal package github.com/kyleconroy/sqlc/internal/plugin not allowed```

**Comment by Nikola-Milovic** [comment]
@flymedllva Have you succeeded in doing this? I also tried writing my own but couldn't quite figure it out

**Comment by blixenkrone** [comment]
I am also finding the error handling to be a bit awkward at times.
My first potentially naive thought was to implement a wrapper method in an SDK to the DBTX interface (postgres driver) to allow for custom query implementations, but I found no good way of swapping out the interface type to the `*Queries` struct that the generated method uses - example:

```go
var (
	ErrForeignKeyConstraintViolation = errors.New("foreign key constraint violation")
	ErrUniqueConstraintViolation     = errors.New("unique constraint violation")
	ErrCheckConstraintViolation      = errors.New("check constraint violation")

	// Returned from a QueryRow operation
	ErrNoRows = pgx.ErrNoRows
)

const (
	foreignConstraintPgErrCode = "23503"
	uniqueConstraintPgErrCode  = "23505"
	checkConstraintPgErrCode   = "23514"
)

func WrapPostgresError(err error) error {
	if err == nil {
		return nil
	}
	var pgErr *pgconn.PgError
	if errors.As(err, &pgErr) {
		switch code := pgErr.Code; code {
		case foreignConstraintPgErrCode:
			return fmt.Errorf("driver error: %v - mapped: %w", err, ErrForeignKeyConstraintViolation)
		case uniqueConstraintPgErrCode:
			return fmt.Errorf("driver error: %v - mapped: %w", err, ErrUniqueConstraintViolation)
		case checkConstraintPgErrCode:
			return fmt.Errorf("driver error: %v - mapped: %w", err, ErrCheckConstraintViolation)
		default:
			return fmt.Errorf("unhandled postgres error (code %q): %w", code, err)
		}
	}
	return err // Return the OG error - we dont know what it is
}
```
Which could then be returned from `QueryRow()` and friends.

@kyleconroy  you said this is not something being worked on a few years back. Is above something you've considered and turned down, or would you be open to PRs to have the generated types allow method implementations of the DBTX interface ie. to have more concrete errors being returned from queries? 

Appreciate this may be a bit offtopic.
