### ISSUE TITLE
Exposing the generated code as a grpc API or open API

### ISSUE THREAD

**Issue by gedw99** [kyleconroy/sqlc#175]
It would be really useful for non golanger coders if we could expose the generated API over grpc or open API 

Since this project already does the code gen it would not be that hard to also generate a protobuf etc. From there the protoc compiler takes over to gen all the code needed.

Wondering what you think ?

**Comment by kyleconroy** [comment]
Thanks for the feature request!

While I agree that would be cool, I think that functionality is currently out of scope for sqlc. There are just so many different ways to expose database methods as REST APIs or RPCs. I'll keep this in mind for the future, but going to close out for now.
