### ISSUE TITLE
Use caseInsensitive = true option for SQLiteLexer.g4

### ISSUE THREAD

**Issue by KvanTTT** [kyleconroy/sqlc#1757]
### What do you want to change?

Use [caseInsensitive](https://github.com/antlr/antlr4/blob/master/doc/options.md#caseinsensitive) option for [SQLiteLexer.g4](https://github.com/kyleconroy/sqlc/blob/8618c39830996cfde6d32096563eb8310beb9046/internal/engine/sqlite/parser/SQLiteLexer.g4) instead of fragments. It's available since ANTLR 4.10.

**Comment by kyleconroy** [comment]
@hakobera Do you think this is something we should do?

**Comment by hakobera** [comment]
@kyleconroy Current SQLite parser can handle both upper case and lower case characters correctly, so I don't have strong opnion to use the option just for removing fragments.

@KvanTTT Could you explain what is the benefit to introduce this change? I know we can remove fragments, but we need to update many places to use this option.

**Comment by KvanTTT** [comment]
It just simplifies grammar, with the option there is no need for fragments to describe case insensitive tokens. I.e. the following grammar:

```g4
lexer grammar L;
options { caseInsensitive = true; }
TOKEN: 'TOKEN';
```

is equivalent to

```g4
lexer grammar L;
TOKEN: T O K E N;
T: [Tt];
O: [Oo];
K: [Kk];
E: [Ee];
N: [Nn];
```

**Comment by kyleconroy** [comment]
I'll leave this up to @hakobera, as he's been doing the majority of the SQLite work. Going to close this out for now.
