### ISSUE TITLE
Add ability to exclude tables in `schema` from being generated in `models.go`

### ISSUE THREAD

**Issue by dhermes** [kyleconroy/sqlc#1770]
### What do you want to change?

For example, in an auxiliary join for the `widget` table:

```sql
SELECT
  w.id,
  w.price,
  w.description,
  p.full_name AS owner_full_name
FROM
  widget AS w
INNER JOIN
  person AS p
ON
  p.id = w.owner;
```

we may never need a type in `models.go` for the `person` table.

### What database engines need to be changed?

PostgreSQL, MySQL

### What programming language backends need to be changed?

Go

**Comment by kyleconroy** [comment]
In this specific example, you also don't need the `Widget` type. For now, sqlc will continue to generate models for all tables, as changing it would be a backwards-incompatible change.
