### ISSUE TITLE
How to generate nullable enum ?

### ISSUE THREAD

**Issue by dee-el** [kyleconroy/sqlc#1774]
Hi I want asking something about nullable enum.

Since some of my projects has nullable enum, I want try migrate some queries on those projects using `sqlc`.

So, I try it first on [playground](https://play.sqlc.dev/p/59cdb65541303c93cbd6bf887e18fbc623f33028d01f0e5ba8980cbb7f05a43d)

But the code generated not having nullable enum type, is there something i missed  here?

**Comment by eullerpereira94** [comment]
The current release (1.15) already generates nullable enums.

**Comment by kyleconroy** [comment]
The playground needed to be updated to v1.15.0. This link now has the correct output https://play.sqlc.dev/p/59cdb65541303c93cbd6bf887e18fbc623f33028d01f0e5ba8980cbb7f05a43d
