### ISSUE TITLE
Sass-like variables

### ISSUE THREAD

**Issue by ehfeng** [kyleconroy/sqlc#1776]
### What do you want to change?

I would like Sass-like variables to be written in sql so I can use the same value across both a column's default and a insert default (in the event of a null parameter). This is useful for being able to have [optional parameters for insert statements](https://www.ehfeng.com/optional-create-and-update-parameters-with-sqlc/).

```sql
create table plants(color text not null default :default_color);

insert into plants(color) values (coalesce(sqlc.narg(c), :default_color);
```

**Comment by kyleconroy** [comment]
@ehfeng Thanks for the feature request. This isn't something I'm looking to add to sqlc right now, but please feel free to write up a larger feature request if you'd really like something like this.
