### ISSUE TITLE
Generate table names and columns

### ISSUE THREAD

**Issue by FlymeDllVa** [kyleconroy/sqlc#1787]
### What do you want to change?

I would like to generate the names of the table and its fields from the database in addition to the generation of entities. It would allow to use them in some custom queries not created through sqlc, and the code would stop compiling when you change the schema.

### What database engines need to be changed?

PostgreSQL

### What programming language backends need to be changed?

Go

**Comment by kyleconroy** [comment]
This sounds like the perfect use case for a [plugin](https://docs.sqlc.dev/en/latest/guides/plugins.html). Can you provide an example of the code you'd like sqlc to generate?
