### ISSUE TITLE
Add support for queries against `information_schema` tables

### ISSUE THREAD

**Issue by yehudamakarov** [kyleconroy/sqlc#1800]
### Version

Other

### What happened?

I'm trying to generate a function from a query like this:

```
-- name: GetMyTableColumns :many
SELECT column_name,
       data_type
FROM information_schema.columns
WHERE table_name = 'my_table';
```

but I get the following error while generating:

`schema "information_schema" does not exist`

### Relevant log output

```shell
schema "information_schema" does not exist
```

### Database schema

```sql
information_schema, 
but in the sqlc.yaml I am using `schema: "migrations"` because I'm using `"github.com/golang-migrate/migrate/v4"`
```

### SQL queries

```sql
-- name: GetMyTableColumns :one
SELECT column_name,
       data_type
FROM information_schema.columns
WHERE table_name = 'my_table';
```

### Configuration

```yaml
see above
```

### What operating system are you using?

macOS

### What database engines are you using?

PostgreSQL

### What type of code are you generating?

Go

**Comment by kyleconroy** [comment]
sqlc currently doesn't support this queries, but I'd love to in the future. One person is working on adding some similar tables in https://github.com/kyleconroy/sqlc/pull/1748. Probably best to wait for that to be merged, as we're still working on a few issues.

**Comment by skabbes** [comment]
@yehudamakarov I put up a PR for this here: https://github.com/kyleconroy/sqlc/pull/1815 though you might have to write your query with casts for now.  LIke this:

```sql
SELECT column_name::text,
       data_type::text
FROM information_schema.columns;
```

That is to tell sqlc what datatypes you want to use, because the information_schema tables use a slightly _odd_ type, unless Kyle knows how to address that - I (currently) do not.
