### ISSUE TITLE
Support generating mocks with golang/mock

### ISSUE THREAD

**Issue by Xeoncross** [kyleconroy/sqlc#1804]
### What do you want to change?

The Go language has a library for creating mock objects (https://github.com/golang/mock). Using `go generate ./..` you can generate mocks throughout your project based on comments in the source code. 

```go
//go:generate mockgen -destination=../mocks/mock_querier.go
type Querier interface {
	GetUserByEmail(ctx context.Context, email string) (User, error)
	InsertUser(ctx context.Context, arg InsertUserParams) (int64, error)
}
```

Would it be possible to add a flag to sqlc that allows the querier interface (or the struct) to be mocked using something like this? Would help when doing unit testing to have a fake copy of the generated sqlc models.

### What programming language backends need to be changed?

Go

**Comment by kyleconroy** [comment]
Thanks for the feature request, but right now this isn't something that will be added. I've used `mock` in the past, and I think you can use it outside of `go:generate`. I think that's probably the best way to do it, especially since it supports a large number of flags.
