### ISSUE TITLE
Wanted: Pro License (1 Year + Free Updates)

### ISSUE THREAD

**Issue by coolaj86** [kyleconroy/sqlc#1812]
### What do you want to change?

Paid support.

This project is too important to be supported by donations alone.

I'd like a way to purchase a commercial license with one year of free upgrades. \
(I don't care about expansion as much as fewer bugs, quicker turnaround, and peace of mind that the project will still be maintained in 5 years)

Along with that, I'm disappointed that the project is becoming diluted by trying to be everything to everyone. I think paying users would benefit from a return to the Unix philosophy, which is echoed in the Go Proverbs and the Go community: "Do one thing, and do it well".

It seems like this would easily lend itself to a family of separately licensable products, such as

- [Database Parser] + [Code Generator]
- PostgreSQL -> JSON + JSON -> Go
- SQLite3 -> JSON + JSON -> Kotlin

I'd like to get a license for a database and a language, or perhaps a bundle that includes others.

From what I can see most businesses and projects:
- center around just one database, not several
- are forced to use multiple programming languages

On a current project I'm working on we happen to be using two different SQL databases and two programming languages, but I don't think that's common.

### What database engines need to be changed?

PostgreSQL

### What programming language backends need to be changed?

Go

**Comment by kyleconroy** [comment]
If you'd like to financially support the project, sponsorships are the best way to do that right now. The higher tiers include support as well.

If you aren't happy with the direction sqlc is taking, you are free to fork the project.
