### ISSUE TITLE
Unable to detect sqlc.yaml when running sqlc via Docker

### ISSUE THREAD

**Issue by SuriMarks** [kyleconroy/sqlc#1853]
### Version

1.15.0

### What happened?

I am trying to run sqlc from the official docker container, When I do, I get an error that the file sqlc.yaml does not exist (despite it being present), but preplexingly, if I add an sqlc.json file it complains that there are two files present (both the yaml and json). So clearly it can detect the files, but wont proceed when they are both there. I just need it to detect one and run with it.

In the log section I have put some terminal output which I believe illustrates the problem well, and also shows the docker command I am using.

### Relevant log output

```shell
// confirming sqlc.yaml file exists
$ ls -l sqlc.yaml
-rw-r--r--. 1 username username 176 Sep 18 21:15 sqlc.yaml

// running the sqlc docker container produces a file not found error
$ ./sqlc-run.sh
error parsing sqlc.yaml: file does not exist

// adding an sqlc.json file causes an error for the existence of two config files
$ touch sqlc.json
$ ./sqlc-run.sh
error: both sqlc.json and sqlc.yaml files present

// this is the source of the script to run above
$ cat sqlc-run.sh 
#!/bin/bash

docker run --rm \
-v .:/src \
-w /src \
kjconroy/sqlc:1.15.0 \
generate
```

### Configuration

```yaml
version: "2"
sql:
  - schema: "./db/schema/"
    queries: "./db/queries/"
    engine: "postgresql"
    strict_function_checks: true
    gen:
      go:
        out: "./db/sqlc"
```

### What operating system are you using?

Linux

### What database engines are you using?

PostgreSQL

### What type of code are you generating?

Go

**Comment by mikey247** [comment]
@SuriMarks I'm currently having this issue. What is the fix??

**Comment by SuriMarks** [comment]
@mikey247 
A fix has been implemented  (see above comments from Nov 10th). Make sure you are using the a current release of sqlc. If you are still having issues, you may need to submit your own bug report.

**Comment by joecroninallen** [comment]
@mikey247: 
Note the latest in DockerHub is 1.16. The fix is 1.17

**Comment by mikey247** [comment]
> @mikey247: 
> Note the latest in DockerHub is 1.16. The fix is 1.17

Oh I see, thanks

**Comment by mshero7** [comment]
can't find sqlc 1.17 how to install 1.17 version?

**Comment by fsobh** [comment]
Using latest version and still having this issue. My make file shows that the file exists but sqlc via docker isnt detecting it

**Comment by fsobh** [comment]
> Using latest version and still having this issue. My make file shows that the file exists but sqlc via docker isnt detecting it
I resolved it by using 
`docker run --rm -v $(PWD):/src -w /src kjconroy/sqlc generate` instead of `docker run --rm -v $(shell pwd) -w /src kjconroy/sqlc generate`

**Comment by kw2828** [comment]
If running in powershell, the following worked for me:

`docker run --rm -v ${PWD}:/src -w /src kjconroy/sqlc generate`
