### ISSUE TITLE
Add schema comments to models.go

### ISSUE THREAD

**Issue by maxhawkins** [kyleconroy/sqlc#187]
If I attach a comment to a table or column in the schema it should appear as a comment in the generated Go code.

```sql
CREATE TABLE foo ( bar INT );
COMMENT ON TABLE foo IS 'Foo is a table';
COMMENT ON COLUMN foo.bar IS 'Bar is a column';
```

```go
// Foo is a table
type Foo struct {
  // Bar is a column
  Bar int
}
```

**Comment by kyleconroy** [comment]
Do you mean a comment starting with two dashes or something else?

**Comment by maxhawkins** [comment]
Oops! I pressed return before my full comment went through.

What I'm talking about is the native SQL `COMMENT ON` functionality.

**Comment by kyleconroy** [comment]
https://www.postgresql.org/docs/current/sql-comment.html
