### ISSUE TITLE
Can it be used for some complex queries?

### ISSUE THREAD

**Issue by AllenDang** [kyleconroy/sqlc#188]
Here is my query, it will return top paid user list for last 10 days.

```
select
uid,
nickname,
paid::integer,
case when user_profile.extra_data->>'platform' = '0' then
	'android'
else
	'ios'
end as platform
from (
	select
	uid,
	round(sum(amount) / 100, 0) as paid
	from payment_order, account
	where payment_order.uid = account.id
	and role in (0, 30)
	and payment_order.created_at > current_date - interval '10d' + time '22:00:00'
	and status = 2
	and callback_data notnull
	and amount > 0
	group by uid having sum(amount) / 100 > 1000
) pu
left join user_profile on id = pu.uid
order by paid desc;
```

When I run sqlc generate on it, I got a error says 'Error: path ./sql/query/ contains no queries'.

This is a valid postgres query, and the project folder structure is good for simple query.

**Comment by kyleconroy** [comment]
> Error: path ./sql/query/ contains no queries

sqlc requires annotations on individual queries. You'll want to add the following comment to your query.

```sql
-- name: TopPaidUsers :many
select
uid,
...
```

As for your question, yes, sqlc can be used for any SQL query. If compilation fails after adding the comment, please include the full table schema for debugging purposes.

**Comment by AllenDang** [comment]
I already added the annottations, still failed. Blow screenshot should explain everything.
![截屏2019-12-18上午10 47 45](https://user-images.githubusercontent.com/18550/71051613-d5d28f00-2183-11ea-9b2a-9cde56392f39.png)

**Comment by kyleconroy** [comment]
I tried to compile this on my machine and got the following error:

```
query.sql:18:18: relation "payment_order" does not exist
```

This makes sense, as the query references three tables: `paid_users`, `payment_order` and `account`. However, your schema only includes a CREATE TABLE statement for paid_users.

**Comment by kyleconroy** [comment]
Allen, I haven't heard from you in a few weeks, so I'm going to mark this issues as resolved.

**Comment by euller88** [comment]
This issue is still not fixed. I've tried to do some queries from aliased subqueries and they don't work completely properly. I had to cheat by writing a unproper query that when compiled generated the proper fields and accepted the proper parameters. Here is an example:

```sql
-- name: ListRequests :many
SELECT
  request.id,
  request.user_id,
  request.created_at,
  request.solved_at,
  user.name,
  user.sector_code
FROM ( SELECT DISTINCT ON (request.user_id)
    request.id,
    request.user_id,
    request.created_at,
    request.solved_at,
    user.name,
    user.sector_code
  FROM
    request
    JOIN user ON user.id = request.user_id
  WHERE
    request.solved_at IS NULL
  ORDER BY
    request.user_id,
    request.created_at DESC) sub_query
ORDER BY
  request.solved_at;
```
Note the tool should have used `sub_query` instead of the name of the tables to properly generate code, but that is currently not possible.

**Comment by kyleconroy** [comment]
@euller88 I believe we're tracking that bug in #159. If not, please open up a new issue with a full schema / query to reproduce the issue.
