### ISSUE TITLE
Go Param Names in Complex Statements

### ISSUE THREAD

**Issue by joshuarubin** [kyleconroy/sqlc#189]
I've got a query that looks something like this (though there are multiple columns being set):

```sql
-- name: UpdateFoo :one
UPDATE foo
SET
  bar = CASE WHEN $1::bool
    THEN $2::bar_type
    ELSE bar
    END
RETURNING *;
```

This produces a params struct like this:

```go
type UpdateFooParams struct {
	Column1         bool           `json:""`
	Column2_2       bar_type       `json:"_2"`
}
```

The naming here isn't very helpful. Do you have any suggestions on how this can be improved? Either by using a different kind of query (that allows updating multiple fields, each one optional) or by somehow annotating things such that the params struct uses more helpful naming?

**Comment by kyleconroy** [comment]
> The naming here isn't very helpful.

Agreed. It also appears there's something strange going on with the names. There's not reason the second parameter should be `Column2_2`, it should just be `Column2`. That said, even the "correct" names are unhelpful.

> Do you have any suggestions on how this can be improved? 

I think I do. We already do inference of parameter names. It's how the query `UPDATE foo SET bar  = $1` gives you a parameter named `Bar`, not `Column_1`. It should be possible to recognize the pattern you're using a generate a struct that looks like this:

```
type UpdateFooParams struct {
	SetBar         bool           `json:"set_bar"`
	Bar       bar_type       `json:"bar"`
}
```

> by somehow annotating things such that the params struct uses more helpful naming?

We've talked about overriding parameters names in #71

**Comment by joshuarubin** [comment]
> It should be possible to recognize the pattern you're using and generate a struct that looks like this

Yeah, that's exactly what I'd like. That can be done already?

**Comment by kyleconroy** [comment]
I wish because then I wouldn't have to write it! Sadly it needs to be implemented. In the meantime, you're stuck with terrible parameter names :(

**Comment by kyleconroy** [comment]
@joshuarubin I just landed support for named parameters. Your original query can be rewritten like so:

```sql
-- name: UpdateFoo :one
UPDATE foo
SET
  bar = CASE WHEN @set_bar::bool
    THEN @bar::bar_type
    ELSE bar
    END
RETURNING *;
```
