### ISSUE TITLE
Tag a commit with a release beyond v0.0.0-dev

### ISSUE THREAD

**Issue by vinicio** [kyleconroy/sqlc#190]
This will help us to run sqlc as a `go run` command instead of downloading the binary.

Ex:

```
go run github.com/kyleconroy/sqlc/cmd/sqlc
```

Thank you very much!

**Comment by kyleconroy** [comment]
@vinicio Sorry that I've been ignoring this issue. I'm not sure that I'm ready to start tagging releases. Currently, sqlc is released automatically from tip. Until that changes, I don't think tags make sense.

I know that's going to make it more difficult to use sqlc, but I think it's the right choice for the project at this time.
