### ISSUE TITLE
Pgnation and filter

### ISSUE THREAD

**Issue by befika** [kyleconroy/sqlc#1908]
### What do you want to change?

I was trying to manage filters and paginations, for paginations simply i can add Ofsets and limit on the select query, but how can I manage filter parameters, and how do create scopes on sqlc

**Comment by kyleconroy** [comment]
Take a look at https://github.com/kyleconroy/sqlc/issues/1062

**Comment by befika** [comment]
thank you @kyleconroy 

is there any way to make a dynamic filter for all list views
