### ISSUE TITLE
CRUD methods

### ISSUE THREAD

**Issue by rubenv** [kyleconroy/sqlc#192]
I'm currently a `gorp` user, mainly to map queries to structs. Replacing that with `sqlc` would be a nobrainer.

However, for some use cases you don't need specific queries, just standard CRUD operations are fine.

Am I understanding it correctly that I'd need to write create/select/update/delete queries for all types manually? Or is there a way to generate these convenience methods for a table?

**Comment by kyleconroy** [comment]
> Am I understanding it correctly that I'd need to write create/select/update/delete queries for all types manually?

Yes, that it correct. While it may change in the future, sqlc does not generate SQL queries for you. It compiles existing SQL queries into type-safe Go.

> Or is there a way to generate these convenience methods for a table?
Convenience methods are not currently generated for tables

**Comment by rubenv** [comment]
Cool, thanks for the clarification.

Brilliant project by the way, really interesting approach. Keep it up :+1:

**Comment by kyleconroy** [comment]
Thanks! I'll ping this issue once progress is made on the CRUD front.

**Comment by fr3fou** [comment]
Any news?

**Comment by neverlink** [comment]
I've been dealing with the same thing, it's been a year, has there been any progress since?
