### ISSUE TITLE
COMMENT ON COLUMN returns error for view

### ISSUE THREAD

**Issue by kyleconroy** [kyleconroy/sqlc#194]
Related to #193, #191 

This breaks if one of your comments is on a view.

```sql
CREATE TABLE users (name TEXT);

CREATE VIEW harrys AS
  SELECT name
  FROM users
  WHERE name ILIKE '%harry%';

COMMENT ON harrys.name IS 'Harry's name';
```

`relation "harrys" does not exist`

_Originally posted by @maxhawkins in https://github.com/kyleconroy/sqlc/pull/191#issuecomment-566740910_

**Comment by kyleconroy** [comment]
I don't think this is a bug. `COMMENT ON` requires the object type before the comment.

```sql
-- invalid
COMMENT ON harrys.name IS 'Harry's name';

-- valid
COMMENT ON VIEW harrys.name IS 'Harry's name';
```

Currently, unimplemented object types are ignored, so `COMMENT ON VIEW` is ignored.

**Comment by maxhawkins** [comment]
Oops I forgot the `COLUMN`. I can reproduce this failure:

```sql
CREATE TABLE users (name TEXT);

CREATE VIEW harrys AS
  SELECT name
  FROM users
  WHERE name ILIKE '%harry%';

COMMENT ON COLUMN harrys.name IS 'Harry''s name';
```

`relation "harrys" does not exist`

**Comment by kyleconroy** [comment]
As of v1.9.0, I can no longer reproduce this issue. Take a look at [here](https://play.sqlc.dev/p/aed26756dcfb1c79fd3b6248abbe2da14ee2fb557bc703402faec28e646d6c39).
