### ISSUE TITLE
Query parameter missing from Params struct

### ISSUE THREAD

**Issue by jonleopard** [kyleconroy/sqlc#1964]
I'm not sure if this is a user error (I'm fairly new to PostgreSQL) or if the query is a little too abstract for sqlc to understand what my intent is.  I need `Expires` to be apart of the `CreateSnippetParams` struct. 

I converted the following MySQL query into PostgreSQL

```
INSERT INTO snippets (title, content, created, expires)
VALUES(?, ?, UTC_TIMESTAMP(), DATE_ADD(UTC_TIMESTAMP(), INTERVAL ? DAY))
```

PostgreSQL query:
```
-- name: CreateSnippet :one
INSERT INTO snippets (title, content, created, expires)
VALUES(
    $1,
    $2,
    (now() at time zone 'utc'),
    (now() at time zone 'utc' + interval '$3 day'))
RETURNING *;
```

sqlc generates:
```
type CreateSnippetParams struct {
	Title   string
	Content string
}
```

Here's the snippets model for reference:
```
CREATE TABLE snippets (
    id BIGSERIAL NOT NULL PRIMARY KEY,
    title VARCHAR(100) NOT NULL,
    content TEXT NOT NULL,
    created TIMESTAMP(0) NOT NULL,
    expires TIMESTAMP(0) NOT NULL
);
```

I'm pretty sure this is a user error so apologies in advanced if that's the case!

Cheers,
Jon

**Comment by kyleconroy** [comment]
I believe your query needs to be changed to the follow ```
-- name: CreateSnippet :one
INSERT INTO snippets (title, content, created, expires)
VALUES(
    $1,
    $2,
    (now() at time zone 'utc'),
    (now() at time zone 'utc' + interval $3))
RETURNING *;
```

https://play.sqlc.dev/p/1413a3311a0fa4f1e414c3e97dd2e8ffb033b21cd4683c5f9e7125e0072b017b

**Comment by jonleopard** [comment]
That works! Thank you so much! Lastly, how can I get 'Column3' to be named 'Expires' in the Params struct?

**Comment by d-tsuji** [comment]
> how can I get Column3 to be named Expires in the Params struct?

How about using named parameters like this?

```sql
-- name: CreateSnippet :one
INSERT INTO snippets (title, content, created, expires)
VALUES(
    $1,
    $2,
    (now() at time zone 'utc'),
    (now() at time zone 'utc' + interval @expires::interval))
RETURNING *;
```

The field name is `Expires`. Note that without `::interval`, the field type will be `time.Time`.

```go
type CreateSnippetParams struct {
	Title   string
	Content string
	Expires int64
}
```

https://play.sqlc.dev/p/897a182df6278285651a6db372451e79799a2584806ef514d5bad9a74421a62e

**Comment by jonleopard** [comment]
@d-tsuji For some reason I couldn't understand the syntax in the docs for renaming/type overrides. Your example is super clear and works great though!

Thanks a bunch!

**Comment by jonleopard** [comment]
Managed to figure this one out for anyone wondering #1991
