### ISSUE TITLE
Fails when ':' is included in ENUM name

### ISSUE THREAD

**Issue by maxhawkins** [kyleconroy/sqlc#197]
This enum declaration is valid sql:
```sql
CREATE TYPE enum AS ENUM ('a:');
```

But running it through sqlc produces this error:
```
error generating code: source error: 22:7: expected ';', found ':' (and 10 more errors)
```

**Comment by kyleconroy** [comment]
Enum names are used to create the constant name. In this case sqlc is generating `const EnumA: Enum = "a:"`, which isn't a valid Go identifier. We'll need to either strip ":" or replace it with a different character.

**Comment by maxhawkins** [comment]
So this is a little less abstract, here's the query I'm trying to write:

```sql
CREATE TABLE users ( name TEXT );
CREATE TYPE sort_order AS ENUM ('name:asc', 'name:desc');

-- name ListUsers :many
SELECT *
FROM users
ORDER BY
    CASE WHEN $1::sort_order = 'name:asc'     THEN name       END ASC,
    CASE WHEN $1::sort_order = 'name:desc'    THEN name       END DESC;
```

I changed the enum name to `name_asc` and `name_desc` for now, which works fine.
