### ISSUE TITLE
Go renames don't work in config v2

### ISSUE THREAD

**Issue by josharian** [kyleconroy/sqlc#1977]
### Version

1.15.0

### What happened?

[I'm actually running 1.16.0, but the dropdown is missing that choice.]

I tried porting my config file from v1 to v2. Go renames and overrides stopped working.

To confirm that I didn't just make a config file mistake, I instrumented v2ParseConfig. I can confirm that my requested renames and overrides are present in the config field `conf.SQL[0].Gen.Go` (per the docs), but the downstream code is reading the configs from `conf.Gen.Go`, including later in v2ParseConfig.

### What type of code are you generating?

Go

**Comment by Emyrk** [comment]
My PR should fix this: https://github.com/kyleconroy/sqlc/pull/2001
