### ISSUE TITLE
Type overriding does not work for uuid, causes import conflict

### ISSUE THREAD

**Issue by utkarshod** [kyleconroy/sqlc#1984]
### Discussed in https://github.com/kyleconroy/sqlc/discussions/1983

<div type='discussions-op-text'>

<sup>Originally posted by **utkarshod** December  4, 2022</sup>
I want to override the google uuid but when I try [type overriding](https://docs.sqlc.dev/en/stable/reference/config.html#type-overriding), it does not replace the google uuid but merely adds the new one to the imports of the `models.go`:
```
	"github.com/gofrs/uuid"
	"github.com/google/uuid"
```
This causes the following import error:
```
internal/queries/models.go:13:2: uuid redeclared in this block
	internal/queries/models.go:11:2: other declaration of uuid
```

I've tried `version 1` (as following), `version 2` and column overriding and yet I am unable to get the google uuid to stop being imported. Note: Type overriding works for me for another db type, just not `uuid`.
```version: 1
packages:
  - path: "internal/queries"
    name: "queries"
    engine: "postgresql"
    schema: "data/schema.sql"
    queries: "data/queries.sql"
    emit_methods_with_db_argument: true
    overrides:
      - go_type: "github.com/gofrs/uuid.UUID"
        db_type: "uuid"
```

This seems like a bug to me. Any suggestions / help would be greatly appreciated! </div>

**Comment by mcdoker18** [comment]
Can you provide the reproducible example?

Because the type overriding works https://play.sqlc.dev/p/26d5866a44400ad7b1a183cc8b43e4ecb691e76274fed0f01d7711a386b635e7

If you need use both packages, you can specify package alias:

```yaml
      "go_type": {
            "import": "github.com/gofrs/uuid",
            "package": "gofrsuuid",
            "type": "UUID",
            "pointer": true
          }
```

**Comment by utkarshod** [comment]
@mcdoker18 thanks so much for the response! That helped. 

The issue was that in my schema, I had one `uuid` and one  `uuid NOT NULL`. And the latter was getting assigned the google uuid ([example](https://play.sqlc.dev/p/44e9fb981997bfa6fb5d44d0fc1a9dce2eec9da621e649b48bf1583103919dec)), resulting in a 2 different uuid imports in `models.go`.

But following your suggestion, I overrode both nullable and not nullable uuids like [here](https://play.sqlc.dev/p/2b9720a847cf803b0d2b87f23a000ff0ba10f77c3b307384e782134aa7926d3c).
