### ISSUE TITLE
SELECT from FUNCTION return

### ISSUE THREAD

**Issue by maxhawkins** [kyleconroy/sqlc#199]
```sql
CREATE FUNCTION foo() RETURNS bool AS $$ SELECT true $$ LANGUAGE sql;

-- name: FromFoo :one
SELECT * FROM foo();
```

Fails with the error `empty edit contents`

**Comment by athusrv** [comment]
Any solution for this problem?

**Comment by warent** [comment]
A workaround that I use is
```
select foo();
```
(i.e. drop the `* from` part) which seems to do the same. I'm not 100% sure what the implications/differences are since I'm not a postgres expert.

**Comment by warent** [comment]
I've implemented a partial solution to this in my PR here https://github.com/kyleconroy/sqlc/pull/846

It only works for functions that return table types because that's all I need to suit my needs at the moment.

**Comment by warent** [comment]
FYI for primitive values this seems to work fine if you omit the fields that you're selecting on. i.e.
`SELECT foo()` should compile to a go func that returns a bool
