### ISSUE TITLE
While reverting from pgx/v4 to the default the `batch.go` file is not deleted

### ISSUE THREAD

**Issue by davideimola** [kyleconroy/sqlc#1999]
### Version

Other

### What happened?

I generated the code with `pgx/v4` and a batchexec query.

While rollbacking to the default sql_package and regenerating the code the generated file `batch.go` is not deleted and it causes a compilation error.

### What operating system are you using?

macOS

### What database engines are you using?

PostgreSQL

### What type of code are you generating?

Go

**Comment by kyleconroy** [comment]
sqlc only generates code; it never deletes files on the file system. The reason for this is pretty simple. We have no way of knowing that the `batch.go` file wasn't placed there on purpose by another tool.
