### ISSUE TITLE
Optional WHERE parameters via `$1 IS NULL OR`

### ISSUE THREAD

**Issue by maxhawkins** [kyleconroy/sqlc#200]
```sql
CREATE TABLE users ( name TEXT NOT NULL );

-- name: ListUsers :many
SELECT *
FROM users
WHERE
  ($1 IS NULL OR name = $1);
```

Sometimes I do something like this to optionally query by a field. Since there's no type associated with `$1 IS NULL` sqlc fails: `nodes.ResTarget has nil name`.

I can fix this by re-ordering the WHERE clause:

```sql
SELECT *
FROM users
WHERE
  (name = $1 OR $1 IS NULL);
```

But now the generated type is `string` instead of `sql.NullString`

**Comment by ddnm102** [comment]
Hi!
Related to this issue, how can i generate a pointer type for parameters?

```
-- schema.sql
CREATE TABLE users (
    id BIGSERIAL PRIMARY KEY,
    email TEXT NOT NULL UNIQUE,
    full_name TEXT NOT NULL
);
```

```
-- queries.sql
-- name: UserList :many
SELECT * FROM users
WHERE 
(email = $1 or $1 IS NULL) AND
(full_name = $2 or $2 IS NULL) ;
```
Currently, SQLC generated:
```
type UserListRequest struct {
  Email     string  `protobuf:"bytes,1,opt,name=email,proto3,oneof" json:"email,omitempty"`
  FullName  string  `protobuf:"bytes,2,opt,name=full_name,json=fullName,proto3,oneof" json:"full_name,omitempty"`
}
```
But, Because we want Email, FullName are options (when user do not provide -> will skip it in SQL statement), so, we need:
```
type UserListRequest struct {
  Email     *string  `protobuf:"bytes,1,opt,name=email,proto3,oneof" json:"email,omitempty"`
  FullName  *string  `protobuf:"bytes,2,opt,name=full_name,json=fullName,proto3,oneof" json:"full_name,omitempty"`
}
```

**Comment by ludusrusso** [comment]
You can forse type by casting it with something like `$1::varchar` but I did not find a way to make the input value optional! Did you solved the issue?

**Comment by mrsufgi** [comment]
Seems like a pressing issue, optional parameters is something really common. 

Changing the model (schema) to "nullable" with a default is not a viable option (forcing sql.NullXXX) and I'm not sure how overrides can help, since the input is not a part of the schema, we need a way to create nullable inputs :o: 

I would be happy to submit a PR but I would appritiate some pointers to where to start <3

**Comment by pomkine** [comment]
Hi! Any news on this one?

**Comment by kyleconroy** [comment]
I'm going to split this into two separate issues. The original query in this issue is still causing `sqlc generate` to [fail](https://play.sqlc.dev/p/751fab76184dc6d87b68d535f611a92149d2056aa890c4596c7d1e2f7d223e81).

The other part of this issue deals with marking parameters as nullable. I've created a new issue (#1155) to track this where we can discuss possible solutions.

**Comment by danielbprice** [comment]
This has become a real bummer for me.  I am trying to port some boring "take REST request and turn it into SQL query" code to Go and I would like to use sqlc; the REST API has optional inputs which become clauses on the WHERE clause, just like the above example.  I feel really stuck at this point, and I think I will have to abandon using sqlc in this project as result.  I'm back to writing boilerplate again.  Maybe someone else has a clever workaround I've missed?

**Comment by louis77** [comment]
@danielbprice I'm stuck at exactly the same issue. I found no solution to this and it looks like this is because sqlc completely relies on a 1:1 mapping between the schema definition and the query, which is, more often than not, very not reality. I have about 300 different queries and more than half of them I'm unable to map it with sqlc. So it's time to say hello to good old sqlboiler.

**Comment by imraan-go** [comment]
> @danielbprice I'm stuck at exactly the same issue. I found no solution to this and it looks like this is because sqlc completely relies on a 1:1 mapping between the schema definition and the query, which is, more often than not, not reality. I have about 300 different queries and more than half of them I'm unable to map it with sqlc. So it's time to say hello to good old sqlboiler.

Yep. I had to abandon using this. Just use some orm like gorm or bun.

**Comment by danielbprice** [comment]
@louis77 @imraan-go since I wanted to stick with sqlc for now, I've taken to adding some bool inputs to do what I want.  It's not super convenient but not terrible either:

```
-- name: GetThings :many
SELECT *
FROM things
WHERE
  color = sqlc.arg('Color') AND
  (NOT sqlc.arg('HasCreatedFrom')::bool OR (created >= sqlc.arg('CreatedFrom'))) AND
  (NOT sqlc.arg('HasCreatedTo')::bool OR (created < sqlc.arg('CreatedTo')))
LIMIT sqlc.arg('Limit')
OFFSET sqlc.arg('Offset');
```

This is icky in my personal opinion but it would certainly be pretty easy to rip and replace (for my use case) if this gets fixed.  300 queries is a lot, my sympathies.

**Comment by kyleconroy** [comment]
1.14.0 includes `sqlc.narg` which generates nullable arguments.

```sql
CREATE TABLE users ( name TEXT NOT NULL );

-- name: ListUsers :many
SELECT *
FROM users
WHERE
  (name = sqlc.narg('name') OR sqlc.narg('name') IS NULL);
```

https://play.sqlc.dev/p/b3a469bb92eace4537a8268b12722ff1d445336ad6a77b9068ecba582381f16a

**Comment by akhmadnurmuhammad** [comment]
Hi guys, how about optional where in arg ? any example ?

**Comment by omid9h** [comment]
> 1.14.0 includes `sqlc.narg` which generates nullable arguments.
> 
> ```sql
> CREATE TABLE users ( name TEXT NOT NULL );
> 
> -- name: ListUsers :many
> SELECT *
> FROM users
> WHERE
>   (name = sqlc.narg('name') OR sqlc.narg('name') IS NULL);
> ```
> 
> https://play.sqlc.dev/p/b3a469bb92eace4537a8268b12722ff1d445336ad6a77b9068ecba582381f16a

hey kyle, how can I use this with COALESCE? (e.g. ... LIMIT COALESCE(sqlc.narg('limit_val'), 10)) currently this syntax returns "unsupported reference type: <nil>"

**Comment by omid9h** [comment]
> COALESCE

Hmm, that is weird. my code is like yours but I get the error.
```sql
-- name: ListSample :many
SELECT id,
    title,
    created_at,
    updated_at
FROM sample
WHERE (
        title ILIKE sqlc.narg('title')
        OR sqlc.narg('title') IS NULL
    )
    AND (
        created_at >= sqlc.narg('start_created_at')
        OR sqlc.narg('start_created_at') IS NULL
    )
    AND (
        created_at >= sqlc.narg('end_created_at')
        OR sqlc.narg('end_created_at') IS NULL
    )
ORDER BY created_at DESC OFFSET sqlc.narg('offset_val')
LIMIT COALESCE(sqlc.narg('limit_val'), 100);
```
but both of these lines work:
```sql
LIMIT @limit_val;
```

```sql
LIMIT sqlc.narg('limit_val')@limit_val;
```

sqlc.yaml:
```yaml
version: "2"
sql:
  - engine: "postgresql"
    queries: "db/queries/"
    schema: "db/migrations/"
    gen:
      go:
        package: "db"
        sql_package: "pgx/v5"
        out: "db"
```

sqlc version : v1.19.0

**Comment by danielbprice** [comment]
@omid9h, I tried to replicate your setup on the sqlc playground, and I had no luck getting it fire the error you mentioned.
https://play.sqlc.dev/p/4a9082b92e8aa9a5f1801a14b9282130a9c2ae1d5a5f47da40b7617c03fd65f3

Can you review that and see if I made a mistake?  I had to guess the schema, translate your config to JSON, and tweak it for the filenames of the playground, but your query is the same.  I assume what you are saying is that the code doesn't compile, right?  I'm sorry I can't help you more!  Maybe someone else will know.

**Comment by francisco-bodyguard** [comment]
After some tests, I have been able to make it works with `LIMIT`.

All you have to do is to cast the argument into `int`. So, in your case @omid9h:

```sql
LIMIT COALESCE(sqlc.narg('limit_val')::int, 100);
```

Also works on the example of @danielbprice: https://play.sqlc.dev/p/1bd81d42563767cc41714bd39570eba50ca17adc81bdee07ebab0d9ac8f7566f

**Comment by sergeishilkocardmarket** [comment]
```
SELECT *
FROM users
WHERE
  (name = sqlc.narg('name') OR sqlc.narg('name') IS NULL);
```

now generates go  `name redeclared in this block`, go does not compile
