### ISSUE TITLE
mysql: support for insert of multiple rows

### ISSUE THREAD

**Issue by newhook** [kyleconroy/sqlc#2002]
### Version

1.15.0

### What happened?

Is there a way to insert multiple rows into a MySQL database?

ie: the equivalent of:

```
insert into foo(bar1, bar2, bar3)
values
  (?,?,?),
  (?,?,?),
  (?,?,?)
  ```

**Comment by croconut** [comment]
for an arbitrarily sized array, the mysql query would look like:

``` sql 
insert into table_1
(col_1, col_2)
values
?;

and the final query parameter passed to mysql would look like:
('string', 15), ('second', 16), ('last', 35)

**Comment by kyleconroy** [comment]
There currently isn't a way to do this for an unknown number of rows. Duplicate of #695

**Comment by croconut** [comment]
Thats too bad as its definitely doable, e.g. npm's mysql package (and why mysql doesn't already support arrays, I don't understand).

**Comment by aakarim** [comment]
It looks like #695 is now closed, are there any examples of this working with an INSERT statement?
