### ISSUE TITLE
Python generation for Postgresql uses double quotes for enums. 

### ISSUE THREAD

**Issue by Hendler** [kyleconroy/sqlc#2007]
### Version

1.15.0

### What happened?

Version is 1.16.

When creating an enum, and sql statements, the output of python adds double quotes which fails to execute. 

Example 

```
CREATE TYPE contact_type AS ENUM ('email', 'phone);

CREATE TABLE IF NOT EXISTS  identity (
    ID BIGSERIAL PRIMARY KEY,
    Username VARCHAR(128),
    ContactType contact_type
);

SELECT i.Username, i.ID
    FROM identity as i
    WHERE i.ContactType = 'email';
```

The above changes single quotes to double quotes, which fails to execute. 

### What operating system are you using?

macOS

### What database engines are you using?

PostgreSQL

### What type of code are you generating?

Python

**Comment by kyleconroy** [comment]
Migrated to https://github.com/tabbed/sqlc-gen-python/issues/4
