### ISSUE TITLE
Ability to sync structures with the database

### ISSUE THREAD

**Issue by ashneverdawn** [kyleconroy/sqlc#202]
Would be nice to have the option to have a command to sync DDL statements from sql files to an existing database. sqlc could use the DDL statements in the sql files to determine what tables/columns need to be added/altered, ect.

If concerned about loss of data on deletions and drops, It could just notify of the diffs and ask for confirmation.

**Comment by kyleconroy** [comment]
Thanks for the feature request. For the foreseeable future, sqlc will only be focusing on generating code from SQL queries. I hope to add migration support and database management at some point, but it's not going to be soon.

In the mean time, there are some great tools out there that you can use:
- https://github.com/pressly/goose
- https://github.com/rubenv/sql-migrate
- https://www.liquibase.org/
