### ISSUE TITLE
quote in table column name restrictions

### ISSUE THREAD

**Issue by farwydi** [kyleconroy/sqlc#203]
Hi, I got the error...

Shema:
```sql
CREATE TABLE bad_table
(
    id        UUID                  NOT NULL
        CONSTRAINT pk_melody_artist
            PRIMARY KEY,
    "group"                 VARCHAR(500)
);

-- name: GetTest :one
SELECT *
FROM bad_table 
WHERE id = $1;
```

Result:
```go
const getTest = `-- name: GetTest :one
SELECT id, group
FROM bad_table
WHERE id = $1
`
```

Have error:
`pq: syntax error at or near "group"`

Database: PostgreSQL
OS: Windwos WSL (ubuntu)
Build: https://github.com/kyleconroy/sqlc/commit/b393d65306012c41527c3ed995cb272b6d1db36e

**Comment by kevinburkemeter** [comment]
Group is a reserved keyword in Postgres and you're trying to use it as a column name. Try using double quotes around it - e.g id, "group"

**Comment by kyleconroy** [comment]
> Try using double quotes around it - e.g id, "group"

The column name is added by sqlc from star expansion. I'll add the reserved keywords to make sure the generated columns names are correct.

**Comment by kyleconroy** [comment]
Alright, this should be fixed in the latest version. Please let me know if it's still causing issues.
