### ISSUE TITLE
sqlite: comparison order affects generation of param structs

### ISSUE THREAD

**Issue by pexarkh** [kyleconroy/sqlc#2032]
### Version

1.16.0

### What happened?

You can find a reproducible example in [this repository](https://github.com/pexarkh/sqlc-bug)
A brief explanation of what happened is in README.md

### Relevant log output

```shell
sqlc generated code is here https://github.com/pexarkh/sqlc-bug/blob/main/pkg/database/q.sql.go
```

### Database schema

```sql
https://github.com/pexarkh/sqlc-bug/blob/main/database/schema/s.sql
```

### SQL queries

```sql
https://github.com/pexarkh/sqlc-bug/blob/main/database/queries/q.sql
```

### Configuration

```yaml
https://github.com/pexarkh/sqlc-bug/blob/main/database/sqlc.yaml
```

### What operating system are you using?

macOS

### What type of code are you generating?

Go

**Comment by pexarkh** [comment]
@zaneli thank you so much for fixing it! hope it will go out soon with 1.17
please let me know if you'd like me to test it as well. i'm not sure how yet but i'll try to figure it out :)

**Comment by zaneli** [comment]
@pexarkh 
Thank you. :)
I think this problem will be fixed with my PR, but I am not sure if this is the right way to do it.
Let's wait for the kyleconroy's response.
