### ISSUE TITLE
When select row along a count slqc think those colunms cannot be null but they can if the count is 0

### ISSUE THREAD

**Issue by Canadadry** [kyleconroy/sqlc#2041]
### Version

1.16.0

### What happened?

When a run the query and one count is at 0 a get a scan error. Look at the generated code, I should have NullString instead of string. 

Did I miss something ? Is there any way to help sqlc ? 

### Relevant log output

```shell
sql: Scan error on column index 1, name \"hour\": converting NULL to string is unsupported
```

### Database schema

```sql
-- Example queries for sqlc
CREATE TABLE bs_step (
	id INT AUTO_INCREMENT NOT NULL,
	author_id INT NOT NULL,
	kind VARCHAR(20) NOT NULL,
	date DATETIME NOT NULL,
	INDEX IDX_D44D84E7F675F31B (author_id),
	PRIMARY KEY(id)
) DEFAULT CHARACTER SET UTF8 COLLATE `UTF8_unicode_ci` ENGINE = InnoDB;

CREATE TABLE s_user (
	id INT AUTO_INCREMENT NOT NULL,
	uuid CHAR(36) NOT NULL,
	PRIMARY KEY(id)
) DEFAULT CHARACTER SET UTF8 COLLATE `UTF8_unicode_ci` ENGINE = InnoDB;
```

### SQL queries

```sql
-- name: GetWeeklyStatsByUser :many
select
  COUNT(step.id) AS countStep,
  SUBSTRING(step.date, 12, 2) AS hour,
  SUBSTRING(step.date, 1, 10) AS day
from bs_step as step
inner join s_user as u on u.id = step.author_id
WHERE SUBSTRING(step.date, 1, 10) >= ?
AND u.uuid = ?
order by day DESC, hour DESC;
```

### Configuration

```yaml
{
  "version": "1",
  "packages": [
    {
      "path": "db",
      "engine": "mysql",
      "schema": "query.sql",
      "queries": "query.sql"
    }
  ]
}
```

### Playground URL

https://play.sqlc.dev/p/f209314e220412599b432f0922f3dbe1292dbe8a58b864796c3afb71d9285356

### What operating system are you using?

macOS

### What database engines are you using?

MySQL

### What type of code are you generating?

Go

**Comment by mikemackintosh** [comment]
This is related to your query, not sqlc. Specifically, you have a `COUNT()` which will always return a value, even 0. This will happen when either of your the WHERE criteria's are not met.

For example, you can run the query with a non-existent `uuid`. Result set will be:
```
countStep |  hour | day
-----------------------
              0  |    null | null
```

You can use a group by since you're using a count:
```
select
  COUNT(step.id) AS countStep,
  SUBSTRING(step.date, 12, 2) AS hour,
  SUBSTRING(step.date, 1, 10) AS day
from bs_step as step
inner join s_user as u on u.id = step.author_id
WHERE SUBSTRING(step.date, 1, 10) >= ?
AND u.uuid = ?
GROUP BY step.author_id
order by day DESC, hour DESC;
```

This will resolve the empty result row when theres no matching criteria. Might not be perfect, but should get you on the right path.
