### ISSUE TITLE
bingo get v1.16.0 fails

### ISSUE THREAD

**Issue by myles-mcdonnell** [kyleconroy/sqlc#2043]
### Version

1.16.0

### What happened?

Almost certainly a bingo issue, but thought I should highlight it here too:  

https://github.com/bwplotka/bingo/issues/128

### What operating system are you using?

macOS

### What database engines are you using?

PostgreSQL

### What type of code are you generating?

Go

**Comment by kyleconroy** [comment]
I'm not familiar with bingo, so I'm going to close this for now. I'll follow along on the other issue and see if there's anything I need to change.
