### ISSUE TITLE
Discord link invalid

### ISSUE THREAD

**Issue by anyu** [kyleconroy/sqlc#2052]
### What happened?

https://discord.com/invite/EcXzGe5SEs -- got the following error. Not sure if it's expired or perms are locked down?

![Screenshot 2023-02-07 at 1 44 50 PM](https://user-images.githubusercontent.com/1009227/217337242-1e2f5089-d573-42d6-b310-1815989d0efd.png)

**Comment by zaneli** [comment]
It seems to be working fine.
![Discord - Google Chrome 2023_02_09 1_01_44](https://user-images.githubusercontent.com/379820/217584080-a4f4cba3-9710-4914-84a8-68c569020c8d.png)

**Comment by anyu** [comment]
Ah, it worked via an incognito window for me 👍🏼
