### ISSUE TITLE
Path contains no queries

### ISSUE THREAD

**Issue by voidshard** [kyleconroy/sqlc#206]
So I'm just playing around here making a random foobar repo to try out this badassery .. but I just get
```
 > sqlc compile
Error: path ddl/queries/ contains no queries
```
I .. think I'm following the README but :thinking: I guess ..not?

```
> sqlc version   
v0.0.1
```

```
 > tree
.
├── ddl
│   ├── queries
│   │   └── user.sql
│   └── schema
│       └── 0001_user.sql
├── go.mod
├── go.sum
├── pkg
│   ├── db
│   └── domain
│       └── user.go
└── sqlc.json
```

```
 > cat sqlc.json 
{
  "version": "1",
  "packages": [
      {
      "name": "user",
      "path": "pkg/db",
      "queries": "ddl/queries/",
      "schema": "ddl/schema/"
      }
  ] 
}
```

```
 > cat ddl/queries/user.sql 
-- name: GetUsers :many
SELECT *
FROM users
WHERE id IN $1;
```
^ I'm not crazy right? That's definitely a query inside ddl/queries/ ..?

```
> cat ddl/schema/0001_user.sql
CREATE TYPE status AS ENUM (
  'open',
  'closed'
);

CREATE TABLE users (
  id   varchar(225) PRIMARY KEY,
  name varchar(225) NOT NULL,
  age int NOT NULL DEFAULT 0, 
  status status NOT NULL DEFAULT 'open',
  hobbies text[]
);
```
What am I doing wrong exactly? Err I haven't checked the Create Table query works .. but the error seems to say that there are no queries in the folder .. but .. there are?

**Comment by kyleconroy** [comment]
> but the error seems to say that there are no queries in the folder .. but .. there are?

Indeed! This was a bug in error handling. While your `GetUsers` query looks correct, it actually isn't valid SQL. However, the parse error was being hidden by the incorrect `no queries` error.

The error you should have received is this:

```
ddl/queries/user.sql:1:1: syntax error at or near "$1"
```

If you want to filter users by a set of IDs, you'll need to use [ANY](https://github.com/kyleconroy/sqlc/blob/master/examples/any.md).

```sql
-- name: GetUsers :many
SELECT * FROM users
WHERE id = ANY($1::varchar[]);
```

You'll need to download the most recent version of sqlc to get the fix.

**Comment by voidshard** [comment]
Riiiight ok thanks!
