### ISSUE TITLE
Missing assets in V1.17.0

### ISSUE THREAD

**Issue by Edholm** [kyleconroy/sqlc#2072]
### Version

Other

### What happened?

The assets for the [v1.17.0](https://github.com/kyleconroy/sqlc/releases/tag/v1.17.0) release is missing. The previous releases have included ready-built binaries.

![image](https://user-images.githubusercontent.com/1151328/218755551-3c6189af-d746-403a-95ed-aa37a0cedc75.png)

**Comment by kyleconroy** [comment]
Sorry about that. I cut the release last night and didn't get a chance to build the assets. It's all fixed now.
