### ISSUE TITLE
TINYINT(1) is not a bool

### ISSUE THREAD

**Issue by boxa99** [kyleconroy/sqlc#2077]
sqlc is treating TINYINT(1) as a go bool, which is incorrect. What happens when the integer value in the column is required?

In mysql, a BOOLEAN is a synonym of TINYINT(1), it is still an integer type, able to store between -127 and 127, for a signed type.

This might have changed here?

https://github.com/kyleconroy/sqlc/pull/842

Does this require a code fix, or is there some configuration to treat this column as an integer?

**Comment by boxa99** [comment]
I found a workaround, I suppose this can work, although I do think the reverse should be true, ie it defaults to int8 and we can override to a bool if required. 

`      overrides:
        - column: example.column
          go_type: "int8"              
`

**Comment by mpyw** [comment]
It would be troublesome if `tinyint(4)` were to be treated as a bool, whereas it's not true for `tinyint(1)`. MySQL does not have built-in `bool`, so many people actually use `tinyint(1)` as a synonym. Also, you cannot save disk spaces by choosing `tinyint(1)`; they consume the same amount of storage. 

If you really want to limit the value to one digit, it would be more practical to add a `CHECK` constraint:

```sql
CHECK(value between 0 and 9)
```

It may be correct as a strict behavior to consider `tinyint(1)` as an integer, but I don't see much value in it.

**Comment by kyleconroy** [comment]
I believe the `boolean / tinyint(1)` support for MySQL is correct as-is. Big thank you to @mpyw for the explanation on why that's the case.
