### ISSUE TITLE
Exclude `PrepareContext` method from DBTX interface when `emit_prepared_queries` is false

### ISSUE THREAD

**Issue by Code-Hex** [kyleconroy/sqlc#2094]
### What do you want to change?

I wanted a `DBTX` interface w/o `PrepareContext` when emit_prepared_queries is false in Go.
What do you think?

### What database engines need to be changed?

PostgreSQL

### What programming language backends need to be changed?

Go

**Comment by kyleconroy** [comment]
It's a reasonable request. That said, this would be a backwards-incompatible change to the interface of DBTX. I think the best solution in the short term is to keep the interface the same and just require a dummy `PrepareContext` method. I know that's not ideal, but breaking existing code is a non-starter.
