### ISSUE TITLE
LIMIT parameter type should be sql.NullInt32?

### ISSUE THREAD

**Issue by fwojciec** [kyleconroy/sqlc#210]
First of all - thank you for this extremely useful tool! 

Sqlc uses `int32` type as parameter for `LIMIT` in queries, for example for this query

```sql
-- name: ListAuthors :many
SELECT * FROM authors
ORDER BY name
LIMIT $1 OFFSET $2;
```
sqlc will generate this set of params:
```go
type ListAuthorsParams struct {
	Limit  int32
	Offset int32
}
```

According to [Postgres docs](https://www.postgresql.org/docs/9.3/queries-limit.html) it should be also possible to use `NULL` as the argument to `LIMIT` to effectively omit the `LIMIT` clause.  This is very useful for queries where `LIMIT` is optional.

It's possible to work around this by passing some arbitrary large number as the parameter, but that seems like a hack.

Would it be possible to use something like `sql.NullInt32` instead of `int32` as the parameter for `LIMIT` so that it's possible to dynamically assign `NULL` to `LIMIT` in queries?

**Comment by cmoog** [comment]
One possibility solution is to have the `Limit` be of type `*int32`. Then the generator would add the logic for injecting `"NULL"`. The aws sdk takes a similar approach for nullable parameters.

**Comment by EnchanterIO** [comment]
On a similar note. If a table primary key is defined as BIG INT, why the offset and limit generates int32 params @cmoog ? Shouldn't that generate int64? 

Is there a way to specify this in the query annotations or?

**Comment by EnchanterIO** [comment]
Hi @kyleconroy , do you have any idea how to resolve my above comment and make the sqlc to generate the attributes of type int64 instead of int32 please?

**Comment by kyleconroy** [comment]
@EnchanterIO You can always cast the parameter to the correct type

```
-- name: ListAuthors :many
SELECT * FROM authors
ORDER BY name
LIMIT $1::bigint
OFFSET $2::bigint;
```

**Comment by kyleconroy** [comment]
Changing this to default to a `NullInt32` is a breaking change I'm not willing to make right now. That said, #1155 will address this for all parameters, so I'm going to close this in favor of that issue.

**Comment by EnchanterIO** [comment]
Wou I didn't know about this casting `$1::bigint` THANKS. Will try that tomorrow. That will do for now, I understand breaking changes are only possible in long-term releases. Thanks again @kyleconroy for awesome work on SQLC.

**Comment by GuillaumeDesforges** [comment]
In combination with https://github.com/sqlc-dev/sqlc/issues/1665, it is effectively not possible to use a nullable parameter in LIMIT:
- `LIMIT sqlc.narg(limit)` raises a parse error
- `LIMIT $` makes a non-nullable parameter

What is the recommended way to go around this/
