### ISSUE TITLE
Acquire advisory lock

### ISSUE THREAD

**Issue by kevinburkemeter** [kyleconroy/sqlc#211]
I'm trying to add this to a query file:

```
-- name: AcquireLock :exec
SELECT pg_advisory_xact_lock($1);
```

However, I get the following error:

```
 $ make sql
/Users/kevin/bin/sqlc generate
# package db
db/query/locks.sql:1:1: nodes.ResTarget has nil name
```

It would be nice if this could generate a function call for me.

**Comment by kevinburkemeter** [comment]
I added this to the ManagedTx abstraction, which might be better since this query only works inside of a transaction anyway.

```
func (m *ManagedTx) Lock(ctx context.Context, value int64) error {
	_, err := m.Queries.tx.ExecContext(ctx, `-- ManagedTx.Lock
SELECT pg_advisory_xact_lock($1)`, value)
	return err
}
```

**Comment by kyleconroy** [comment]
It's pretty easy to add support for built-in functions. Right now it's a pretty random collection of functions that are implemented. While you found a work around, there's no reason your original SQL shouldn't work.
