### ISSUE TITLE
Add a flag to disable special treatment for `id` in field renaming

### ISSUE THREAD

**Issue by kshramt** [kyleconroy/sqlc#2113]
### What do you want to change?

Currently, there's a slight inconsistency in the codebase where the `id` is renamed as `ID` instead of `Id`, while `url` is renamed as `Url`. To resolve this issue, I'm looking for a solution that would let me turn off the special treatment for `id`.

To accomplish this, it would be great if I could use a flag, like `rename_id_to_ID: false`, which would allow me to opt-out of the special renaming rule for `id`. While I'm aware that the `go: rename: ` feature exists, using it would mean that I have to maintain a lengthy list of fields that end with `id`. This isn't ideal as such fields are very common.

```
account     -> Account
spotify_url -> SpotifyUrl
app_id      -> AppID

(ref. https://github.com/kyleconroy/sqlc/blob/main/docs/reference/config.md#renaming-fields)
```

### What database engines need to be changed?

None

### What programming language backends need to be changed?

golang

**Comment by kyleconroy** [comment]
This behavior is intentional. The Go authors suggest that short names like `ID` are represented in all caps. 

That said, this can be configured. You can use the rename block to change the names to different casing. Here's an [example](https://play.sqlc.dev/p/fd52ea3d1484b57b15c58588b89c3950510ad86f88fa8ac9f6a04d5d058dffe3)

```json
{
  "version": "1",
  "packages": [
    {
      "path": "db",
      "engine": "postgresql",
      "schema": "query.sql",
      "queries": "query.sql"
    }
  ],
  "rename": {
    "id": "Id"
  }
}
```

**Comment by kshramt** [comment]
Thank you for the example, but I'm afraid it didn't quite meet my expectations.

On https://play.sqlc.dev/p/26b2f7a6fa6a3bbd7547c800048389a98f9140e8bc81fd2bcfc578db1446db3b (a new example), I was hoping that `user_id` would be renamed to `UserId`. However, with the `rename: id: Id`, it gets renamed to `UserID`. While I understand that both `id` and `user_id` can be included in the `rename:` map, I would prefer to avoid this approach as there may be many `*_id` fields to rename. Instead, I would prefer to use a global setting.
