### ISSUE TITLE
Null Enums Don't Emit JSON Tag

### ISSUE THREAD

**Issue by austincollinpena** [kyleconroy/sqlc#2115]
### Version

1.16.0

### What happened?

Generated structs should emit JSON tags. Nullable Enums do not emit json tags.

### Database schema

```sql
CREATE TYPE job_post_location_type AS ENUM('remote', 'in_office', 'hybrid');

CREATE TABLE IF NOT EXISTS enum_sample (
   job_location job_post_location_type
)
```

### Playground URL

https://play.sqlc.dev/p/758ece2eda1dd1d53a8dfa46980f5027bd7124489bb24754c7ffb24480d8bc8c

### What operating system are you using?

Windows

### What database engines are you using?

PostgreSQL

### What type of code are you generating?

Go

**Comment by austincollinpena** [comment]
I'd prefer it uses the standard format specified in the SQLC config file in the `json_tags_case_style` option.

Use Case:
It's a bit of an edge case, but generating Open API schema from structs generates things incorrectly unless they're all tagged (using https://github.com/swaggo/swag)

If you point me in the right direction I can look to make a PR. I really love this library and would enjoy contributing.

**Comment by mikemherron** [comment]
@austincollinpena Is this what you mean?

```go
type NullJobPostLocationType struct {
	JobPostLocationType JobPostLocationType `json:"jobPostLocationType"`
	Valid               bool                `json:"valid"` // Valid is true if JobPostLocationType is not NULL
}
```

If so I have a first pass at a PR working and tested; I can tidy it up tomorrow and put it up for review.

**Comment by austincollinpena** [comment]
@mikemherron Yes exactly, thank you!

**Comment by mikemherron** [comment]
I opened the PR, but it may be better to support this through an additional config option. I've added the details and a proposal on the PR, will wait for maintainer feedback.
