### ISSUE TITLE
"does not exist" errors for simple joins

### ISSUE THREAD

**Issue by kyleconroy** [kyleconroy/sqlc#213]
Hi,
I'm seeing similar errors with a few variations on this join. Is this a related issue, or shall I raise a seperate one?

```
SELECT f, b
FROM foo f
JOIN bar b ON b.id = f.id
WHERE f.id = $1;

query.sql:6:8: column "f" does not exist

SELECT foo, bar
FROM foo
JOIN bar ON bar.id = foo.id
WHERE foo.id = $1;

query.sql:6:8: column "foo" does not exist

SELECT f.id, b.title
FROM foo f
JOIN bar b ON b.id = f.id
WHERE f.id = $1;
                
query.sql:6:8: column "id" does not exist
```

_Originally posted by @tgascoigne in https://github.com/kyleconroy/sqlc/issues/159#issuecomment-568809699_

**Comment by kyleconroy** [comment]
@tgascoigne I'm going to assume that the foo and bar tables look like this

```sql
CREATE TABLE foo (
  id integer primary key,
);

CREATE TABLE bar (
  id integer references foo(id),
  title text
);
```

**Comment by tgascoigne** [comment]
Yep, that's equivalent to what I'm using

**Comment by kyleconroy** [comment]
There are two issues at play. The first is that sqlc doesn't currently support `SELECT foo FROM foo`. This is the reason the first two queries error. Do you have example Go code you use to scan those results?

The third query fails due to incorrect alias support, and should be easier to fix.

**Comment by tgascoigne** [comment]
Thanks for the quick response :)

Unfortunately I don't have much more than the examples provided and the code generated by sqlc - I've just started playing around with it today for potential use in future.

My hope was that I'd get something like the below struct generated, but I'd be happy to have any way to extract all columns from both tables:
```go
type SomeRow struct {
    Foo Foo
    Bar Bar
}
```

In the meantime I've worked around it by explicitly selecting each field I care about, which works perfectly fine:
```sql
SELECT foo.id, bar.title
FROM foo 
JOIN bar ON bar.id = foo.id
WHERE foo.id = $1;
```

**Comment by kyleconroy** [comment]
> but I'd be happy to have any way to extract all columns from both tables

You can get that behavior by using `*`:

```sql
SELECT *
FROM foo 
JOIN bar ON bar.id = foo.id
WHERE foo.id = $1;
```

Selecting the table name (`SELECT foo FROM foo`) returns a single column with a composite type `ROW(id)`. Composite types have poor support in `lib/pq`. The value passed to `Scan` is tuple represented as a string (e.g. `(id)`). I haven't found a library that properly handles these values. `SELECT *` has much better support.

**Comment by tgascoigne** [comment]
Now that you mention it I did try `SELECT *`, but both tables have an `id` field, and sqlc expands the `*` out to something like `SELECT id, title, id` (which postgres rejects due to ambiguity)

**Comment by kyleconroy** [comment]
> which postgres rejects due to ambiguity

🤦‍♂ yeah, `*` expansion should be smart enough to generate columns that do not collide.

**Comment by kyleconroy** [comment]
@tgascoigne This has now be fixed in master. The following two queries should now work

```sql
SELECT f.id, b.title
FROM foo f
JOIN bar b ON b.id = f.id
WHERE f.id = $1;

SELECT *
FROM foo 
JOIN bar ON bar.id = foo.id
WHERE foo.id = $1;
```
