### ISSUE TITLE
regression: "relation "lower" does not exist"

### ISSUE THREAD

**Issue by kevinburkemeter** [kyleconroy/sqlc#214]
On tip, this query:

```
SELECT * FROM company_users WHERE company_slug = $1 AND email = LOWER($2);
```

generates the following error:

```
db/query/company_users.sql:9:1: relation "lower" does not exist
```

This did not generate an error with previous versions of sqlc.

**Comment by kyleconroy** [comment]
Ugh, so sorry this broke. I think it's due to refactored parameter logic.

**Comment by kevinburkemeter** [comment]
Thanks. Still not sure this is quite right - here's the new diff.

```
 type GetUserByEmailParams struct {
        CompanySlug string
-       Email       string
+       Lower       string
 }
```

**Comment by kevinburkemeter** [comment]
I tried to look at the diff to figure out what the right thing to do was but couldn't sort it out, sorry :(

**Comment by kyleconroy** [comment]
@kevinburkemeter please see the comment in #215 

> I know that's not ideal, but I thought it would be better to provide a hot fix.

The `Lower` name is expected behavior right now.

**Comment by kevinburkemeter** [comment]
Ugh, my fault for not reading closely enough. Thanks!!
