### ISSUE TITLE
copyfrom is not compatible with ON CONFLICT

### ISSUE THREAD

**Issue by DarkHeros09** [kyleconroy/sqlc#2165]
### What do you want to change?

is there a way to use copyfrom with ON CONFLICT ?

```sql
-- name: CreateShoppingCartItem :copyfrom
INSERT INTO "shopping_cart_item" (
  shopping_cart_id,
  product_item_id,
  qty
) VALUES (
  $1, $2, $3
) ON CONFLICT (product_item_id)
DO UPDATE SET
qty = EXCLUDED.qty
RETURNING *;
```

Thank you

### What database engines need to be changed?

PostgreSQL

### What programming language backends need to be changed?

Go

**Comment by Jille** [comment]
Sadly PostgreSQL doesn't support this, so there's no way for sqlc to do this.

I've always done this through a temporary table:

```
BEGIN;

CREATE TEMPORARY TABLE shopping_cart_item_staging (LIKE shopping_cart_item) ON COMMIT DROP;

:copyfrom
INSERT INTO "shopping_cart_item_staging" (shopping_cart_id, product_item_id, qty) VALUES ($1, $2, $3);

INSERT INTO shopping_cart_item SELECT * FROM shopping_cart_item_staging ON CONFLICT (product_item_id) DO UPDATE SET qty = EXCLUDED.qty RETURNING *;

COMMIT;
```

Note that sqlc doesn't understand creating tables in a query yet (it thinks it part of the schema definition). So you'd have to manually add a method for creating the table to your `Queries` object.

**Comment by adi-kmt** [comment]
Hey @Jille @DarkHeros09, how do we do it with sqlc v1.26? 
I'm trying to do the same as above but it says `relation "table_temp" does not exist`.
Should I enable something in sqlc yaml?

**Comment by Jille** [comment]
Can you ask on Discord or file a separate issue? You'd need to create that temp table in the same session (or transaction, if you're using ON COMMIT DROP).
