### ISSUE TITLE
Allow `schema` to be a remote database url and read the schema

### ISSUE THREAD

**Issue by yaziciahmet** [kyleconroy/sqlc#2166]
### What do you want to change?

sqlc is a truly a great tool, and I believe it would be even greater if it was possible to parse the schema of a remote database. The schema could be read directly from the database by providing the database url to connect in the `schema` field of the configuration file (or maybe a separate field as `db_url` if that's easier). Or even to avoid file manipulations or remote file storage when doing auto-migrations to a production environment, this could be an environment variable `DATABASE_URL` which is prioritized over `schema`.

The reason I need such thing is that, I have multiple services that use a shared database, so it is easier to manage migrations if I have the migrations as a separate project to avoid duplication. Hence I can't have my schema defined inside the service itself.

### What database engines need to be changed?

PostgreSQL, MySQL

### What programming language backends need to be changed?

Go, Python, Kotlin

**Comment by Jille** [comment]
Would it work to add a step to your CI that uses mysqldump/pg_dump to dump the schema to a file and run sqlc with that?
