### ISSUE TITLE
Kyle, please have a look at #1816

### ISSUE THREAD

**Issue by Jille** [kyleconroy/sqlc#2184]
### What do you want to change?

Hey @kyleconroy 

Maybe you've accidentally muted https://github.com/kyleconroy/sqlc/pull/1816, but please have a look. Many people are eager to see it landed.

-- Jille

### What database engines need to be changed?

MySQL

### What programming language backends need to be changed?

Go

**Comment by kyleconroy** [comment]
The eagle has landed
