### ISSUE TITLE
Support to mock Transactions

### ISSUE THREAD

**Issue by surahman** [kyleconroy/sqlc#2190]
### What do you want to change?

Does anyone know a way to go about this? I am uncertain if this can be implemented... The way things currently work is that the generated code in `WIthTx` returns a newly generated `Queries` struct. This struct contains the transaction interface struct returned from the database driver. This is necessary because each transaction needs to be isolated. It is thus not straightforward to inject a mock to build stubs and listen on.

I prefer to capture transactions in UDFs with UDT parameters but the flexibility of being able to assemble and cleanly mock test transactions on the backend service would be very handy indeed.

### What database engines need to be changed?

PostgreSQL

### What programming language backends need to be changed?

Go

**Comment by kyleconroy** [comment]
The current `WithTx` implementation makes it tricky to support a few different use cases. I'm loathe to make a large, breaking change, but we'll take this into account as we make changes in the future. It sounds like you have a okay workaround for now.

**Comment by tragiclifestories** [comment]
Just to say that one potentially transparent way to achieve this for some simple use cases would be to support throwing `BEGIN` and `COMMIT` etc into the queries.sql file. I have no idea how hard that would be in practice.
