### ISSUE TITLE
Duplicate query names produces cryptic Go error

### ISSUE THREAD

**Issue by CaptainCharlieGreen** [kyleconroy/sqlc#220]
If you accidentally create two queries with the same name the generated go code has an error about an 'ambiguous selector"

```sql
-- name: GetReportByID :one
SELECT * FROM abuse_report
WHERE id = $1;

-- name: GetReportByID :one
SELECT * FROM abuse_report
WHERE id = $1;

```

Produces in db.go:

```go
	if q.getReportByIDStmt, err = db.PrepareContext(ctx, getReportByID); err != nil {
		return nil, fmt.Errorf("error preparing query GetReportByID: %w", err)
	}
	if q.getReportByIDStmt, err = db.PrepareContext(ctx, getReportByID); err != nil {
		return nil, fmt.Errorf("error preparing query GetReportByID: %w", err)
	}
```
which fails to compile:
"ambiguous selector q.getReportByIDStmt"

My expected behavior is sqlc fails generation with an error indicating there are multiple queries with the same name.

**Comment by CaptainCharlieGreen** [comment]
I can try my hand at a PR for this if you'd like.

**Comment by kyleconroy** [comment]
> My expected behavior is sqlc fails generation with an error indicating there are multiple queries with the same name.

That's the behavior I'd expect too.

> I can try my hand at a PR for this if you'd like.

I think I have a good idea on how to fix it. Let me take a pass first.

**Comment by kyleconroy** [comment]
Repeating a duplicate query name will now result in the following error:

```
# package db
query.sql:1:1: duplicate query name: GetReportByID
```

**Comment by kyleconroy** [comment]
@CaptainCharlieGreen this should now be fixed in the latest version of sqlc.
