### ISSUE TITLE
Does sqlc support conditional config?

### ISSUE THREAD

**Issue by Shihansin** [kyleconroy/sqlc#2201]
### What do you want to change?

when you use sqlc config , it will config all the queries  to sql prepared statement , but which what i want , is only part of query i need to config to prepared queries  , how can i do this ?
// 
version: "2"
sql:
  - engine: "postgresql"
    queries: "db/queries"
    schema: "db/migration"
    gen:
      go:
        package: "db"
        out: "db/sqlc"
        emit_json_tags: true
        emit_interface: true
        emit_prepared_queries: true

### What database engines need to be changed?

PostgreSQL

### What programming language backends need to be changed?

Go

**Comment by kyleconroy** [comment]
Prepared statements are currently all-or-nothing. The current design of sqlc would make it a bit awkward to change that, but it's something we'll take into account as we add new features.
