### ISSUE TITLE
Unable to install by go get on windows10

### ISSUE THREAD

**Issue by afoninartem** [kyleconroy/sqlc#2210]
### Version

1.17.2

### What happened?

Hello!
go version go1.20 windows/amd64
I'm trying
 `go install github.com/kyleconroy/sqlc/cmd/sqlc@latest`
but it returns an error:

### Relevant log output

```shell
# github.com/kyleconroy/sqlc/cmd/sqlc
C:\Program Files\Go\pkg\tool\windows_amd64\link.exe: running gcc failed: exit status 1
c:/programdata/chocolatey/lib/mingw/tools/install/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/Users/afoni/go/pkg/mod/github.com/bytecodealliance/wasmtime-go/v5@v5.0.0/build/windows-x86_64/libwasmtime.a(helpers.o):helpers.c:(.text$wasmtime_setjmp+0x26): undefined reference to `_setjmp'
collect2.exe: error: ld returned 1 exit status
```

**Comment by andrewmbenton** [comment]
I'm not an expert on Go's dynamic linking, but I presume this is an issue because of sqlc's dependency on certain packages that require cgo.

I would try to go install with these flags to see if you can generate a statically-linked binary: `-ldflags "-linkmode 'external' -extldflags '-static'"`

**Comment by kyleconroy** [comment]
Closing as a duplicate. Let's track all of these install issues here: https://github.com/kyleconroy/sqlc/issues/2294
