### ISSUE TITLE
Add COMMENT ON support for views

### ISSUE THREAD

**Issue by mdigger** [kyleconroy/sqlc#2241]
### What do you want to change?

Use comment to generate model by **`view`**.

```sql
create view test_view as
    select * from table
    where title is not null;

comment on view test_view is 'Test view';
```

The generated struct should have a comment before it like so:

```go
// Test view
type TestView struct {
	ID   int64
	Name string
	Bio  sql.NullString
}
```

No comment currently shows up.

### What database engines need to be changed?

PostgreSQL

### What programming language backends need to be changed?

Go

**Comment by mdigger** [comment]
```golang
// Test view
type TestView struct {
	ID   int64
	Name string
	Bio  sql.NullString
}
```
How is it done for tables... :)

**Comment by kyleconroy** [comment]
Please take a look at the link I shared, as sqlc does exactly this.

**Comment by mdigger** [comment]
https://play.sqlc.dev/p/47cebd466b443ee4bb73a1986990c5a6a30780c2b2b8903d27e3e51624bbd8df

```golang
// Author table comment
type Author struct {...}

type TestView struct {...}
```

There is no comment on structure `TestView` in `models.go`.

**Comment by kyleconroy** [comment]
Indeed there isn't!
