### ISSUE TITLE
Support for naming hints via sqlc.arg in BETWEEN expressions

### ISSUE THREAD

**Issue by dnwe** [kyleconroy/sqlc#2277]
### What do you want to change?

Currently if you use a `BETWEEN` expression such as `SELECT id, name, date FROM events WHERE date BETWEEN ? AND ?;` then sqlc simply names the struct fields as `Date` and `Date_2` a'la:
```go
type GetEventByDateParams struct {
	Date   sql.NullTime
	Date_2 sql.NullTime
}
```

It would be great if naming hints could be passed to sqlc as-in `LIKE` expressions so you could put `SELECT id, name, date FROM events WHERE date BETWEEN sqlc.arg(from_date) AND sqlc.arg(to_date);` and that would result in the generated struct fields being `FromDate` and `ToDate`. At the moment if you attempt to do that it breaks the parser and the Params struct is omitted entirely ([playground link](https://play.sqlc.dev/p/7ecf294cb7aa0b3ce1025657e091cce22970d3b4f5c4eb2baa578e5083cd4219))

### What database engines need to be changed?

PostgreSQL, MySQL

### What programming language backends need to be changed?

Go

**Comment by Jille** [comment]
Kyle added this to the milestone, and I'd like to have the next release, so I wrote a PR :P

The change was small, but finding where to make it was harder :)

@SnoozeThis https://github.com/kyleconroy/sqlc/pull/2366

**Comment by SnoozeThis** [comment]
(https://snoozeth.is/E8ZK_PmKi-g) I will wait until https://github.com/kyleconroy/sqlc/pull/2366 is merged and then add a comment.

**Comment by Jille** [comment]
I just realized I misread your feature request. I thought you wanted to have better default names than Date and Date_2. However, I made a drive-by fix that fixed reusing the same parameter number for both left and right and that probably fixed your actual request.

I've added a test case for your request to my PR.

**Comment by dnwe** [comment]
@Jille perfect, testing with sqlc from your branch and it is working well, thank you!

As you mention, actually the "better defaults" behaviour actually satisfies the original bug without even needing the sqlc.arg support, but thanks for enabling that too

```go
type GetEventByDateParams struct {
	FromDate time.Time
	ToDate   time.Time
}
```

**Comment by SnoozeThis** [comment]
Resolved.
