### ISSUE TITLE
go install .../sqlc@latest (1.18.0) fails on Windows 11 with "undefined reference to _setjmp"

### ISSUE THREAD

**Issue by pexarkh** [kyleconroy/sqlc#2280]
### Version

Other

### What happened?

I was able to install 1.17.2 previously with `go install`, but installing 1.18.0 produces this error:
```
$go install github.com/kyleconroy/sqlc/cmd/sqlc@latest
# github.com/kyleconroy/sqlc/cmd/sqlc
c:\go\pkg\tool\windows_amd64\link.exe: running gcc failed: exit status 1
c:/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: 
  C:/Users/pxr/go/pkg/mod/github.com/bytecodealliance/wasmtime-go/v8@v8.0.0/build/windows-x86_64/libwasmtime.a(helpers.o): 
 helpers.c:(.text$wasmtime_setjmp+0x26): 
 undefined reference to `_setjmp'
collect2.exe: error: ld returned 1 exit status
```
which is a mystery beyond my comprehension... please kindly advise how to install sqlc 1.18.0 on Windows.

**Comment by pexarkh** [comment]
i've just upgraded gcc (mingw64) to 13.1.0. no change - still can't install sqlc:

```
$go install github.com/kyleconroy/sqlc/cmd/sqlc@latest
# github.com/kyleconroy/sqlc/cmd/sqlc
c:\go\pkg\tool\windows_amd64\link.exe: running gcc failed: exit status 1
0C:/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/Users/pxr/go/pkg/mod/github.com/bytecodealliance/wasmtime-go/v8@v8.0.0/build/windows-x86_64/libwasmtime.a(helpers.o):helpers.c:(.text$wasmtime_setjmp+0x26): undefined reference to `_setjmp'
collect2.exe: error: ld returned 1 exit status
```

**Comment by kyleconroy** [comment]
Tracking here https://github.com/kyleconroy/sqlc/issues/2294

**Comment by Anu-Ra-g** [comment]
@pexarkh Is the CGO_ENABLED set to 1 in the go environment variables?

**Comment by Shaker-Hamdi** [comment]
@pexarkh I'm having the exact same issue, did you manage to solve it?

**Comment by Shaker-Hamdi** [comment]
@Anu-Ra-g I followed your suggestion, and the "gcc" compiler is installed on my machine, but still having the same issue.

**Comment by Shaker-Hamdi** [comment]
OK, for anyone having the same issue, this worked for me ...
- I uninstalled "mingw", it was installed using "Chocolatey" on windows, so I did a `choco uninstall mingw`
- Then I installed "gcc" using the following installer ...
https://jmeubank.github.io/tdm-gcc/articles/2021-05/10.3.0-release
Make sure to download the "tdm64-gcc-10.3.0-2.exe" file (64+32-bit MinGW-w64 edition).
- The installation should add the 64 version to your "system variable" path, if id didn't, then add it yourself "C:\TDM-GCC-64\bin" to your "system variable".
- Make sure to restart your terminal and check for "g++ --version", it should say ...
```
g++.exe (tdm64-1) 10.3.0
Copyright (C) 2020 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

Then the package should install properly
