### ISSUE TITLE
LOWER() function generates named "Lower" parameter in model

### ISSUE THREAD

**Issue by kevinburkemeter** [kyleconroy/sqlc#229]
If I write `SELECT LOWER(email)...` the generated parameter name should be "Email," but is currently "Lower."

Previously discussed in #214 and #215 but I thought it would be good to have a open ticket that we can follow/subscribe to to learn when it gets closed.

**Comment by kyleconroy** [comment]
A workaround until this is fixed is to use an alias

```
SELECT LOWER(email) as email...
```

**Comment by kyleconroy** [comment]
I'm not convinced this is actually a bug. Given the following table:

```sql
CREATE TABLE foo (bar text);
INSERT INTO foo (bar) VALUES ('hello');
```

Queries using `LOWER()` return a column named `lower`.

```sql
select bar, lower(bar) from foo;
  bar  | lower 
-------+-------
 hello | hello
```

**Comment by kyleconroy** [comment]
@kevinburkemeter any thoughts here? I'm pretty confident now that this should be the expected behavior.

**Comment by kevinburkemeter** [comment]
Yeah fine to leave it as is.
