### ISSUE TITLE
Plugin to generate basic CRUD sql

### ISSUE THREAD

**Issue by kaashyapan** [kyleconroy/sqlc#2290]
Following these - https://github.com/kyleconroy/sqlc/pull/1463, [#192](https://github.com/kyleconroy/sqlc/issues/192)

I have created this plugin https://github.com/kaashyapan/sqlc-gen-crud.
The trouble is I will still have to provide a dummy query.sql file to get started. Is there a way to get around it ?

**Comment by kyleconroy** [comment]
There currently isn't sadly. We'll be doing more work on the plugin authoring experience in the common months, but no planned work in the short term.
