### ISSUE TITLE
Distribute via Homebrew

### ISSUE THREAD

**Issue by kyleconroy** [kyleconroy/sqlc#233]
For macOS users, sqlc should be distributed using Homebrew. Ideally the following command should work:

```
brew install sqlc
```

Currently, sqlc does not meet the [inclusion criteria](https://docs.brew.sh/Acceptable-Formulae) for homebrew-core.

> Formulae in the core repository must have a stable version tagged by the upstream project. Tarballs are preferred to Git checkouts, and tarballs should include the version in the filename whenever possible.
> 
> We don’t accept software without a tagged version because they regularly break due to upstream changes and we can’t provide bottles for them.

While MySQL support is experimental, I think the PostgreSQL support is stable enough to tag a version.

**Comment by kyleconroy** [comment]
Once v1.0.0 is tagged, I'll update the sqlc formula in the `hombrew-sqlc` repository: https://github.com/kyleconroy/homebrew-sqlc. 

You'll then be able to install it via:

```
brew install kyleconroy/sqlc/sqlc
```

**Comment by kyleconroy** [comment]
`brew install kyleconroy/sqlc/sqlc` now works. After install, `sqlc version` returns `SNAPSHOT` instead of `v1.0.0`. Once that's fixed I'll close this out.

**Comment by kyleconroy** [comment]
```
$ sqlc version
v1.0.0
```

**Comment by aseng-avant** [comment]
Just tried this and it worked great, but I'm wondering if its possible to update the brew formula to just download the binary instead of depending on `go` and having to build the binary.

I have go installed through `asdf` (language version manager) and this causes brew to install go all over again.

**Comment by kyleconroy** [comment]
@aseng-avant Homebrew (the project) prefers that all packages are built from source. Once it lands in `homebrew-core`, we'll be able to provide bottles, which are pre-built binaries. Those will not require reinstalling Go.
