### ISSUE TITLE
play.sqlc.dev is down

### ISSUE THREAD

**Issue by jlisthood** [kyleconroy/sqlc#2330]
### Version

1.18.0

### What happened?

This site can’t be reachedplay.sqlc.dev’s server IP address could not be found.

**Comment by kyleconroy** [comment]
We're in the middle of migrating domains and DNS settings. Should be cleared up soon.

**Comment by kyleconroy** [comment]
And we're back

**Comment by jlisthood** [comment]
Thank you. Nice touch with the panic label 🤣
