### ISSUE TITLE
import in my project go without install cli

### ISSUE THREAD

**Issue by renanbastos93** [kyleconroy/sqlc#2341]
### What do you want to change?

Hi everyone, 

I would like to use sqlc via code but we can't because the Go pattern doesn't get allow us to import internal packages. Even so, I believe that to export methods we use. I have thinking methods like `sqlc.Generate(opt ...options)`. Does it make sense?

### What programming language backends need to be changed?

Go

**Comment by kyleconroy** [comment]
It's on the list. Going to close this in favor of tracking it here https://github.com/kyleconroy/sqlc/issues/2413
