### ISSUE TITLE
sqlc generate throws a syntax error at "\"

### ISSUE THREAD

**Issue by skoo25** [kyleconroy/sqlc#2359]
### Version

1.18.0

### What happened?

Our Postgres schema includes a connect string (e.g. `\connect db`), and `sqlc generate` fails with an error.

### Relevant log output

```bash
Generating SQLC files...
schema.sql:1:1: syntax error at or near "\"
```

### Database schema

`\connect db`

### What operating system are you using?

Linux

### What database engines are you using?

PostgreSQL

### What type of code are you generating?

Go

**Comment by kyleconroy** [comment]
`\connect db` and other commands like that aren't valid SQL. Instead, they're parsed by `psql`. You'll need to remove them from your .sql files for sqlc to correctly parse them.
