### ISSUE TITLE
Binaries on releases

### ISSUE THREAD

**Issue by myles-mcdonnell** [kyleconroy/sqlc#239]
You might like to attache cross compiled binaries to your releases, a la https://github.com/myles-mcdonnell/blondie/releases or https://github.com/go-swagger/go-swagger/releases it's a fairly common pattern these days.

Thx
M

**Comment by kyleconroy** [comment]
I've gone ahead and added binaries for v0.1.0. I'll make sure to do the same once v1.0.0 is released next week.

**Comment by kyleconroy** [comment]
v1.0.0 has binaries added to the release page
