### ISSUE TITLE
unable to install sqlc on window

### ISSUE THREAD

**Issue by mulukenhailu** [kyleconroy/sqlc#2401]
go version go1.20.5 windows/386
![photo_2023-07-04_13-26-43](https://github.com/kyleconroy/sqlc/assets/108363098/3ca5525a-917f-4a96-a5df-92ef1f1273de)

**Comment by mulukenhailu** [comment]
have any one got this kind of Problem?

**Comment by Jille** [comment]
The actual problem is that you're running on a 32-bit machine and the parser we use for MySQL uses integers higher than 32-bit.

https://github.com/pingcap/tidb/issues/11845 and https://github.com/pingcap/tidb/issues/3227 are earlier issued filed about that in tidb.

**Comment by mulukenhailu** [comment]
thanks, a lot.

**Comment by andrewmbenton** [comment]
Unfortunately we won't have resources to add support for 32-bit systems anytime in the near future, so I'll have to close this.
