### ISSUE TITLE
Link to CI/CD howto busted in release notes for 1.19.0

### ISSUE THREAD

**Issue by jmhodges** [kyleconroy/sqlc#2412]
In the [1.19.0 release notes](https://github.com/kyleconroy/sqlc/releases/tag/v1.19.0), the link to the CI/CD howto 404s. It's  in the line "See our suggested CI/CD setup for more information."

(There's also a small typo of "sqlc/db-preapre" instead of "sqlc/db-prepare" elsewhere that I wouldn't mention but while I'm here, you know?)

**Comment by kyleconroy** [comment]
Thanks, there were actually quite a few broken links. They should all be fixed now.
