### ISSUE TITLE
Boolean filter generation fails for SQLite

### ISSUE THREAD

**Issue by SoMuchForSubtlety** [kyleconroy/sqlc#2424]
### Version

1.18.0

### What happened?

Boolean filter expressions don't seem to get processed correctly. I can get it to work by [changing the query slightly](https://play.sqlc.dev/p/e305662edd60be2539b8e973a31984fba61948f0d36b0b089db8a9dc394a6038), but then I lose type information.

### Database schema

```sql
create table my_table
(
    invalid boolean,
    foo     varchar
);
```

### SQL queries

```sql
-- name: GetData :many
select *
from my_table
where (cast(sqlc.arg(allow_invalid) as boolean) or not invalid);
```

### Playground URL

https://play.sqlc.dev/p/80e82864f4994ee1812495bbdfa2bd351fdfa43f1a15968dc61d192e79b22e28

### What operating system are you using?

Linux

### What database engines are you using?

SQLite

### What type of code are you generating?

Go

**Comment by andrewmbenton** [comment]
Looks like we are at the very least not correctly handling the cast node correctly
