### ISSUE TITLE
pgxpool support?

### ISSUE THREAD

**Issue by mthmcalixto** [kyleconroy/sqlc#2493]
### What do you want to change?

Hello, I was wondering if I can use pgxpool, any examples if so?

### What database engines need to be changed?

PostgreSQL

### What programming language backends need to be changed?

Go

**Comment by andrewmbenton** [comment]
Using pgxpool should just work the same way pgx/v5 works. I think the connection type returned from `pgxpool.Connect()` implements the same interface as `pgx.Connect()` so it should just be a drop-in replacement for pgx in this example from the docs: https://docs.sqlc.dev/en/stable/guides/using-go-and-pgx.html#generated-code-walkthrough
