### ISSUE TITLE
type overrides: use actual package name instead of import name

### ISSUE THREAD

**Issue by kevinburkemeter** [kyleconroy/sqlc#261]
If I have this:

```json
    "overrides": [
      {
          "go_type": "github.com/kevinburke/go-types.PrefixUUID",
          "postgres_type": "uuid"
      }
    ]
```

The generated Go source code is, e.g.

```
Get(ctx context.Context, id go-types.PrefixUUID) (Thing, error)
```

Which is a syntax error. In theory it would be good to determine the package import name "package types" and then use that instead.

**Comment by kyleconroy** [comment]
Fixed partially by #262, closing for now
