### ISSUE TITLE
"UPDATE ... FROM" does not work with CTE

### ISSUE THREAD

**Issue by kevinburkemeter** [kyleconroy/sqlc#267]
If I have

```sql
WITH x AS (
    SELECT * FROM table WHERE ...
)
UPDATE table
SET a = b 
FROM x
```

When I run it, I get:

relation "x" does not exist

This is valid per Postgres: https://www.postgresql.org/docs/11/sql-update.html

> A list of table expressions, allowing columns from other tables to appear in the WHERE condition and the update expressions. This is similar to the list of tables that can be specified in the FROM Clause of a SELECT statement. Note that the target table must not appear in the from_list, unless you intend a self-join (in which case it must appear with an alias in the from_list).

I tried to debug further but didn't have any luck.

**Comment by jtarchie** [comment]
This appears to happen with embedded CTEs in the [update](https://play.sqlc.dev/p/be7c03208310147b69c71cdf2735aede92f54e0ca57d2bead57a01aae5246201).
