### ISSUE TITLE
bail out of parser analysis

### ISSUE THREAD

**Issue by kevinburkemeter** [kyleconroy/sqlc#272]
I am writing some complicated CTE's that currently cause sqlc to panic. It would be good to have a way to just be like "the return type of this is a UUID, don't bother parsing it." Otherwise I'm stuck manually writing a whole big thing.

```
-- name: ComplexThing :one
-- input_types: [string, uuid]
-- output_types: [uuid]
WITH _ AS (SELECT ...) ...
```

**Comment by cmoog** [comment]
This would add significant complexity to the interface with many potential issues on the implementation side. At this point, it seems appropriate to focus on improving the ideal behavior of `sqlc` to properly handling queries of this complexity.

**Comment by kyleconroy** [comment]
> This would add significant complexity to the interface 

I agree that allowing people to manually specify the types in the comments is cumbersome. Instead, we could add an optional `:untyped` argument. For untyped queries, we'd do a much smaller amount of analysis. We'd only support `:exec`, as we can't easily know the output columns if parsing the query fails. Here's what it would look like:

```sql
-- name: DeleteAuthor :exec :untyped
DELETE FROM authors
WHERE id = $1;
```

```go
func (q *Queries) DeleteAuthor(ctx context.Context, arg1 interface{}) (sql.Result, error) {
  return q.db.ExecContext(ctx, deleteAuthor, arg1)
}
```

@kevinburkemeter Would that interface be any use to you?

**Comment by kevinburkemeter** [comment]
Generally with a CTE you are trying to get data out, not modify it, so being able to exec only wouldn't do much. 

The particular CTE that was causing sqlc to choke was trying to update a single row from the database so we need to know which row was updated to have any use.

**Comment by kyleconroy** [comment]
@kevinburkemeter I'm going to go ahead and close this issue, as we've decided for the time being that we don't want to support annotating queries with explicit input and return types. Please open an issue if your CTE query is still causing sqlc to panic.
