### ISSUE TITLE
sqlc parse does not output line numbers

### ISSUE THREAD

**Issue by kyleconroy** [kyleconroy/sqlc#278]
The `parse` sub-command needs a bit of love. It isn't output errors in the same format as `generate`, leading to errors that are difficult to diagnose:

```
$ sqlc parse
Error: syntax error at or near "select"
```

**Comment by euller88** [comment]
Wait, it had a parse command?

**Comment by kyleconroy** [comment]
> had

has! The idea is that it does all the type checking and validation but none of the code generation
