### ISSUE TITLE
Support alternative PostgreSQL drivers

### ISSUE THREAD

**Issue by kyleconroy** [kyleconroy/sqlc#28]
Right now that means [pgx](https://github.com/jackc/pgx). Not sure what other PostgreSQL drivers are out there.

**Comment by djui** [comment]
`pq` is very commonly used.

**Comment by kyleconroy** [comment]
@djui `lib/pq` is the only currently supported driver

**Comment by NaLLiFFuNT** [comment]
any updates here?

**Comment by kyleconroy** [comment]
@NaLLiFFuNT None as of yet. I personally don't use anything other than `lib/pq`, so I need some more information for user's of alternatives. What driver do you need supported? Can you post a code snippet of how you use said driver today?

**Comment by kyleconroy** [comment]
Closing this issue out in favor of #472
