### ISSUE TITLE
Add a Kotlin language backend

### ISSUE THREAD

**Issue by mightyguava** [kyleconroy/sqlc#287]
I saw there's Typescript support in the works (is there a tracking issue?). It'd be neat if it could support Kotlin too. There's something similar for Kotlin called [SQLDelight](https://github.com/cashapp/sqldelight), but it only supports sqlite and was built for Android. JVM support for Java/Kotlin would be really cool.

I might be able to contribute if you are open to this.

**Comment by kyleconroy** [comment]
> I saw there's Typescript support in the works (is there a tracking issue?)

There wasn't, but I just created #296 

> JVM support for Java/Kotlin would be really cool.

Agreed! Do you have some example code that you'd hope sqlc would generate for you?

Java/Kotlin support is far off. We're still working through supporting both MySQL and PostgreSQL for Go. Have you looked at [jOOQ](https://www.jooq.org/)? It may fit your need.

> jOOQ generates Java code from your database and lets you build type safe SQL queries through its fluent API

I'm going to go ahead and close this for now. Once we're ready to add Java/Kotlin, we'll re-open it.

**Comment by mightyguava** [comment]
Yes we use jOOQ. Its code generation is pretty limited, only going as far as introspecting the DB to generate the models. The fluent API makes it similar to [squirrel](https://github.com/Masterminds/squirrel). But it's the SQL => Function code generation that really makes `sqlc` powerful imo.

I think the code (for Kotlin at least), looks quite similar to Go. Here's what I think [createAuthor()](https://github.com/kyleconroy/sqlc/blob/285cfa811def2a11846dae8169e677f4767be931/examples/authors/query.sql.go#L11-L30) could look like.

```kotlin
package com.example.testmodule

import java.sql.Connection
import java.sql.SQLException

data class Author(val id: Int, val name: String, val bio: String?);
data class CreateAuthorParams(val id: Int, val name: String, val bio: String?)

const val createAuthor = """-- name: CreateAuthor :one
INSERT INTO authors (
          name, bio
) VALUES (
  \$1, \$2
)
RETURNING id, name, bio
"""

class Queries(private val conn: Connection) {
  @Throws(SQLException::class)
  fun createAuthor(arg: CreateAuthorParams): Author {
    val stmt = conn.prepareStatement(createAuthor)
    stmt.setString(1, arg.name)
    stmt.setString(2, arg.bio)

    val rs = stmt.executeQuery()
    rs.next()
    val author = Author(rs.getInt(1), rs.getString(2), rs.getString(3))
    if (rs.next()) {
      throw SQLException("expected one row, but got many")
    }
    return author
  }
}
```

SQLDelight has a much fancier take on it, though I'm not sure if sqlc needs to do the same

* [SQL files](https://github.com/cashapp/sqldelight/tree/master/sample/common/src/commonMain/sqldelight/com/example/sqldelight/hockey/data)
* [Generated code](https://github.com/cashapp/sqldelight/blob/b6b36e3254d6ddde321d2aefb3dc2d2a3a9e7045/sqldelight-compiler/integration-tests/src/test/kotlin/com/example) -- the generated queries are in `testmodule/HockeyDbImpl`.

I understand not wanting to take on too much for such a young project. But maybe naively I don't think Kotlin support would be all that more complex than Typescript support. I spend a lot of time in Go and Kotlin, and they are similar in certain aspects. And Kotlin <=> Java is completely interoperable.

Again, if I might be able to convince you this is worthwhile to do soon, I would definitely love to contribute!

**Comment by mightyguava** [comment]
Spent some time building a more complete example: https://gist.github.com/mightyguava/f2b7b0c3d1385df8eac509cc93f8d4f2

**Comment by kyleconroy** [comment]
The first version of this has now landed! I'm going to mark this as complete. I've added a new `kotlin` label for future issues.
