### ISSUE TITLE
[MySQL] No support for BOOL

### ISSUE THREAD

**Issue by inconshreveable** [kyleconroy/sqlc#290]
Mysql doesn't have a native boolean type, but it does correctly parse and alias it to TINYINT. Unfortunately sqlc does not understand that:

```sql
CREATE TABLE account (
	id BIGINT NOT NULL AUTO_INCREMENT,
	allow_x BOOL NOT NULL DEFAULT false,
	PRIMARY KEY (id)
)
```

It reports:

`2020/01/23 17:13:06 unknown MySQL type: bool`

**Comment by cmoog** [comment]
PR above fixes the issue. Nice catch 👍
