### ISSUE TITLE
Overrides are only applied for the last package defined in the configuration file

### ISSUE THREAD

**Issue by inconshreveable** [kyleconroy/sqlc#293]
Given a configuration file with *multiple* packages, only the overrides for the *last package defined* will be overriden. In this example, `bar.a` and `bar.b` will be overridden but `foo.a` will not. If you delete the second package definition, then `bar.a` and `bar.b` will be overridden properly. Seems like somewhere some memory space is being re-used for overrides.

I've run git bisect and narrowed it down to commit 92ad2e33de2991703c8b8924684083ec5341be88 where MySQL support was first added

```json
{
        "version": "1",
        "packages": [
                {
                        ...
                        "overrides": [
                                {
                                    "go_type": "*A",
                                    "column": "foo.a"
                                }
                        ],
                },
                {
                        ...
                        "overrides": [
                                {
                                        "column": "bar.a",
                                        "go_type": "*A"
                                },
                                {
                                        "column": "bar.b",
                                        "go_type": "*B"
                                }
                        ]
                }
        ]
}
```

**Comment by cmoog** [comment]
Nice find. I'll take a look and see if I can narrow it down. Either way, we should add more cases to the `endtoend` tests that cover overrides and renames.

**Comment by cmoog** [comment]
I think I've been able to narrow it down to a different issue: if two packages have the same `Name` field, then the overrides are not processed properly. I haven't been able to replicate what you described above with different `Name` values.

**Comment by cmoog** [comment]
Ok, now I'm seeing that `PackageMap` should probably be scrapped. I had assumed the `Name` field was required but I was mistaken.

**Comment by kyleconroy** [comment]
@cmoog I have a patch that does just that, submitting now
