### ISSUE TITLE
json: way to omit fields

### ISSUE THREAD

**Issue by kevinburkemeter** [kyleconroy/sqlc#298]
I have emit_json_tags set to true but it would be nice to have some way to omit specific tags. In particular, I would not like to expose `auto_id`, the serial incrementing integer field

**Comment by kyleconroy** [comment]
Hmm, the configuration format is currently not set up to allow this type of fine-grained configuration. Any idea on how we could change it?

**Comment by kevinburkemeter** [comment]
I mean probably the answer is just "don't use the same struct for JSON serialization that you use for the database."

**Comment by kevinburkemeter** [comment]
(having thought about this for a few days)

**Comment by mightyguava** [comment]
I have also arrived at the same conclusion no less than 3 times in the past, after starting out with JSON on my database models and fighting the inflexibility 😂

**Comment by kyleconroy** [comment]
@kevinburkemeter Going to mark this as wontfix.

**Comment by dimuls** [comment]
Maybe we can use comments for this:
```
create table myuser (
  id bigserial primary key,
  login text not null,
  password_hash bytea not null -- json:"-"
);
```
For `id` and `login` standard `id` and `login` json tags should be generated, for `password_hash` it should be `-`.
Need some way to hide sensitive fields in REST API. Now one should use wrapping structs with `json:"-"` specified for that type of fields.

**Comment by eazylaykzy** [comment]
@kyleconroy  I was wondering if this will be given consideration, moreover with the comment from @dimuls .

**Comment by kwinso** [comment]
Was this implemented?

**Comment by lucaskbr** [comment]
@kwinso https://github.com/sqlc-dev/sqlc/pull/3117
