### ISSUE TITLE
Question: Documentation for foreign key

### ISSUE THREAD

**Issue by andradei** [kyleconroy/sqlc#304]
I've seen the internal/ code for postgres seems to have support for `REFERENCES`, is there documentation for foreign keys? I'm not sure whether it is supported and what the API would look like.

**Comment by kyleconroy** [comment]
@andradei You'll want to take a look at the [booktest](https://github.com/kyleconroy/sqlc/tree/master/examples/booktest/postgresql) PostgreSQL example. It contains two tables, `books` and `authors`. The `books` table has an `author_id` column that references the `author_id` column on the `authors` table. 

The code that is generated for foreign key references is that same as any column. For example, when [creating a book](https://github.com/kyleconroy/sqlc/blob/master/examples/booktest/postgresql/query.sql.go#L116) you pass the author ID as an int32.

```go
type CreateBookParams struct {
	// other fields omitted ...
	AuthorID  int32
}

func (q *Queries) CreateBook(ctx context.Context, arg CreateBookParams) (Book, error) {
	// function body omitted ...
	return i, err
}
```

Hope that clears things up!

**Comment by andradei** [comment]
I see. It uses literally the value of the foreign key (`INT`, `TEXT`, etc.). It makes sense now, considering the design decision of sqlc. I was asking more in the sense of having generated code that with something like:

```go
type Book struct {
	BookID    int32
	Author *Author // <--------- Having an instance of the actual Author model instead of its id.
	Isbn      string
	Booktype  BookType
	Title     string
	Year      int32
	Available time.Time
	Tags      []string
}
```

And stuff like eager-loading and such. It's perfectly fine that it doesn't have those features. Thanks for the explanation. This is a very cool and simple package.

**Comment by andradei** [comment]
I closed it because your answer what I needed. But feel free to reopen if you want to track the addition of documentation for foreign keys.
