### ISSUE TITLE
enum types break parser when defined in schema

### ISSUE THREAD

**Issue by skariel** [kyleconroy/sqlc#308]
the following code does not work unless removing the `tdd` schema from the `type_user_role`. For e.g. the following code:

```sql
CREATE TYPE tdd.type_user_role AS ENUM ('admin', 'user');

CREATE TABLE tdd.users (
    ts_created timestamp with time zone DEFAULT now() NOT NULL,
    ts_updated timestamp with time zone DEFAULT now() NOT NULL,

    email text PRIMARY KEY,
    display_name text UNIQUE,
    psswd_hash bytea,
    role tdd.type_user_role
);
```

results in:
```
 unknown PostgreSQL type: tdd.type_user_role
```

**Comment by clansofts** [comment]
@skariel try this...
.....
"overrides": [
{
"go_type": "path/to/your/generated/models/db.TypeUserRole",
"db_type": "tdd.type_user_role",
"null": true
}
]

Then re-generate.

**Comment by kyleconroy** [comment]
@clansofts that's a good solution for getting around the bug. Thanks!

@skariel I'm working on a fix for this.

**Comment by skariel** [comment]
@kyleconroy  thanks for the quick fix!
