### ISSUE TITLE
composite types don't work

### ISSUE THREAD

**Issue by skariel** [kyleconroy/sqlc#309]
the following code
```SQL
CREATE TYPE type_foo AS (
    x integer,
    y integer
);

CREATE TABLE tdd.solution (
    solution_id uuid DEFAULT uuid_generate_v4() PRIMARY KEY,
    bar foo
);
```
results in the following error:
```
 unknown PostgreSQL type: type_foo
```

**Comment by clansofts** [comment]
@skariel add overides as below

.....
"overrides": [
    {
      "go_type": "path/to/your/generated/models/db.TypeFoo",
      "db_type": "public.type_foo",
      "null": true
    }
   ]

Then re-generate.
