### ISSUE TITLE
MySQL: expected 'IDENT'

### ISSUE THREAD

**Issue by Frosin** [kyleconroy/sqlc#316]
**Hi, I am trying to generate mySQL schema:**
_CREATE TABLE api_mosaics (
  m_id int(11) NOT NULL AUTO_INCREMENT,
  number varchar(45) DEFAULT NULL,
  destination enum('0','1','2') DEFAULT NULL,
  type tinyint(4) DEFAULT NULL,
  size tinyint(4) DEFAULT NULL,
  slot_count tinyint(4) DEFAULT NULL,
  user_min tinyint(4) DEFAULT NULL,
  user_max tinyint(4) DEFAULT NULL,
  PRIMARY KEY (m_id)
) ENGINE=MyISAM AUTO_INCREMENT=21 DEFAULT CHARSET=utf8;_

**But I get the error:** 

error generating code: source error: 19:2: expected 'IDENT', found 0 (and 2 more errors)

**Comment by kyleconroy** [comment]
The `mysql:beta` engine correctly parses this SQL and generates the correct struct.

```go
// Code generated by sqlc. DO NOT EDIT.

package querytest

import (
	"database/sql"
	"fmt"
)

type Destination string

const (
	Destination0 Destination = "0"
	Destination1 Destination = "1"
	Destination2 Destination = "2"
)

func (e *Destination) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Destination(s)
	case string:
		*e = Destination(s)
	default:
		return fmt.Errorf("unsupported scan type for Destination: %T", src)
	}
	return nil
}

type ApiMosaic struct {
	MID         int32
	Number      sql.NullString
	Destination Destination
	Type        sql.NullBool
	Size        sql.NullBool
	SlotCount   sql.NullBool
	UserMin     sql.NullBool
	UserMax     sql.NullBool
}
```

The tinyint fields are incorrect, but that is being tracked in #666
