### ISSUE TITLE
Mysql:  source error: expected ';'

### ISSUE THREAD

**Issue by Frosin** [kyleconroy/sqlc#317]
CREATE TABLE api_webinars (
  id int(11) NOT NULL AUTO_INCREMENT,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  updated_at timestamp NULL DEFAULT NULL,
  account_id int(11) NOT NULL,
  meta text,
  did varchar(15) NOT NULL,
  `status` enum('READY','ONLINE','OFFLINE','FINISHING','FINISHED') NOT NULL,
  conf_id varchar(255) DEFAULT NULL COMMENT 'Medooze conference id',
  watch_pin int(11) DEFAULT NULL,
  PRIMARY KEY (id)
) ENGINE=InnoDB AUTO_INCREMENT=6436 DEFAULT CHARSET=utf8;

**Error:** 

error generating code: source error: 18:60: expected ';', found status (and 1 more errors)

**Comment by ramonberrutti** [comment]
Having the same problem with Mysql when we have `status` column.

**Comment by kyleconroy** [comment]
The `mysql:beta` engine correctly parses and compiles this SQL.

```go
// Code generated by sqlc. DO NOT EDIT.

package querytest

import (
	"database/sql"
	"fmt"
	"time"
)

type Status string

const (
	StatusREADY     Status = "READY"
	StatusONLINE    Status = "ONLINE"
	StatusOFFLINE   Status = "OFFLINE"
	StatusFINISHING Status = "FINISHING"
	StatusFINISHED  Status = "FINISHED"
)

func (e *Status) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Status(s)
	case string:
		*e = Status(s)
	default:
		return fmt.Errorf("unsupported scan type for Status: %T", src)
	}
	return nil
}

type ApiWebinar struct {
	ID        int32
	CreatedAt time.Time
	UpdatedAt sql.NullTime
	AccountID int32
	Meta      sql.NullString
	Did       string
	Status    Status
	// Medooze conference id
	ConfID   sql.NullString
	WatchPin sql.NullInt32
}
```
