### ISSUE TITLE
Support tsrange and tstzrange

### ISSUE THREAD

**Issue by treuherz** [kyleconroy/sqlc#323]
It'd be great if it was possible for the parser to correctly handle `tsrange` and `tstzrange` types. I understand that the library avoids trying to create its own structs for special types like this, but the issue I'm having is that it is unable to parse SQL containing these types, even if it wouldn't be required to generate any code for them. For example:

```sql
CREATE TABLE spans (
    span_id serial PRIMARY KEY,
    timespan tstzrange
);

-- name: GetOverlappingSpans :many
SELECT lower(timespan) AS start,
       upper(timespan) AS end
 WHERE timespan && tstzrange($1, $2, '[)');
```

produces an error `unknown PostgreSQL type: tstzrange`, even though all the parameter and return types can just be `time.Time`, nothing fancy required.

I haven't run any tests on other range types like `numrange` and `int8range`, I'm afraid.

**Comment by kyleconroy** [comment]
The issue here is that sqlc doesn't know about the [functions](https://www.postgresql.org/docs/current/functions-range.html) that operate on range types. The reason you're seeing `unknown PostgreSQL type: tstzrange` is that sqlc thinks `lower(timespan)` returns a `tstzrange`

**Comment by treuherz** [comment]
Ah, that makes more sense! Is there more general support for function return types that happens to not be implemented for these functions, or is that still in the future?

**Comment by eythor** [comment]
I'm not able to create tables with columns of type tstzrange either, so it isn't just a lack of support for these functions.

**Comment by uta-mori** [comment]
I with I could override this type
[pgtype#Tstzrange · pkg.go.dev](https://pkg.go.dev/github.com/jackc/pgtype#Tstzrange)
