### ISSUE TITLE
Mismatch between latest version and documentation

### ISSUE THREAD

**Issue by Oneymus** [kyleconroy/sqlc#334]
I apologize if this issue is a little amorphous, but I spent a considerable amount of time trying to work this out so I wanted to point it out.

I am planning to use `sqlc` with `golang-migrate`, which the [documentation](https://github.com/kyleconroy/sqlc/blob/master/docs/migrations.md) explicitly calls out. However, the latest release does not contain the code necessary to work with `golang-migrate`; specifically, the `.down.sql` files aren't being ignored in `v0.1.0`.

`master`: https://github.com/kyleconroy/sqlc/blob/master/internal/dinosql/parser.go#L83-L95
`v0.1.0`: https://github.com/kyleconroy/sqlc/blob/v0.1.0/internal/dinosql/parser.go#L81-L89

This leads to the following issue when using `v0.1.0`:
```bash
→ sqlc generate                                                       [0d086f9]
# package pg
state/pg/migrate/000001_basic_user.down.sql:3:1: relation "basic_user_permission" does not exist
state/pg/migrate/000001_basic_user.down.sql:4:1: relation "basic_user" does not exist
```

Obviously, I can clone the repository and build `sqlc` myself, but that won't be sustainable longterm on a large team with varying levels of Go knowledge.

Would it be possible to get another release? Or to update the documentation with some kind of warning?

EDIT: I just noticed that the commit that added the `golang-migrate` bit is relatively new (#320). Apologies if this issue seems premature!

**Comment by kyleconroy** [comment]
Sorry for the confusion! v0.1.0 was tagged mostly as an experiment. v1.0.0 is currently tracked in this [milestone](https://github.com/kyleconroy/sqlc/milestone/1). Until 1.0.0 is out, I'd suggest using tip via https://github.com/kyleconroy/sqlc#downloads.

Longer term, the plan is to have a versioned documentation hosted at https://sqlc.dev.

**Comment by kyleconroy** [comment]
A question for you: if you aren't using the downloads from tip, how are you obtaining sqlc?

**Comment by Oneymus** [comment]
Using basic Go commands: `go install github.com/kyleconroy/sqlc/cmd/sqlc`. Go automatically pulls the latest version.

**Comment by kyleconroy** [comment]
`go install github.com/kyleconroy/sqlc/cmd/sqlc` will now install v1.0.0
