### ISSUE TITLE
version number issue

### ISSUE THREAD

**Issue by kevinburkemeter** [kyleconroy/sqlc#335]
If I run "sqlc version" I get 0.0.1 which disagrees with the version in go.mod (when I vendor sqlc) and/or the Git tags corresponding to tip on master.

**Comment by kyleconroy** [comment]
What version is listed in your `go.mod`? Do you know how Go generates that version number? The plan is to add it to the binary on release via command line flags.

**Comment by kevinburkemeter** [comment]
I think it walks backwards from tip of master trying to find a git tag

```
	github.com/kyleconroy/sqlc v0.1.1-0.20200211203606-93f5a09dc0cc
```

**Comment by kyleconroy** [comment]
I'm planning on setting the version number via ldflags

```
go build -ldflags "-X github.com/kyleconroy/sqlc/internal/cmd.version=abc" -o ~/Downloads/sqlc ./cmd/sqlc/
```
