### ISSUE TITLE
How explicit the SQL needs to be

### ISSUE THREAD

**Issue by euller88** [kyleconroy/sqlc#338]
The following SQL: 
```sql
-- name: UnnestDemo :many
SELECT
  unnest(@ids::integer[]) id,
  unnest(@names::text[]) full_name,
  unnest(@scores::float[]) score,
  unnest(@approveds::boolean[]) approved;
```

Generates the following Go code:
```go
...
type UnnestDemoParams struct {
	Ids       []int32   `json:"ids"`
	Names     []string  `json:"names"`
	Scores    []float64 `json:"scores"`
	Approveds []bool    `json:"approveds"`
}

type UnnestDemoRow struct {
	ID       interface{} `json:"id"`
	FullName interface{} `json:"full_name"`
	Score    interface{} `json:"score"`
	Approved interface{} `json:"approved"`
}
...
```

If we explicitly cast the result of the unnest for the appropriate type, then the Row struct will generate with appropriate types, if we don't, then the struct will be filled with `interface{}`.

I'm all in for making the developer to be always explicit with their code, but I don't know how smart is the parser in order to correlate the field to generate with the type of the array.

**Comment by kyleconroy** [comment]
sqlc attempts to pick types for parameters in queries. This process is called type inference. Right now, as you've discovered, the type inference is limited. Explicit casting gives developers an escape hatch to override types when inference fails.

We have a ton of work to do to make it so casts like these aren't required.

**Comment by kyleconroy** [comment]
@euller88 Since I havent' heard from you, I'm going to close this issue. If you still have questions, please feel free to reopen.
