### ISSUE TITLE
go get/install doesn't work

### ISSUE THREAD

**Issue by dharmjit** [kyleconroy/sqlc#341]
Hi,

currently it not possible to install the tool using go get/install. Below error is thrown
```
package github.com/kyleconroy/sqlc: no Go files in /home/dj/go/src/github.com/kyleconroy/sqlc
```

**Comment by kevinburkemeter** [comment]
It should be checked out anyway.

Try `go get github.com/kyleconroy/sqlc/cmd/sqlc`, I think.

**Comment by dharmjit** [comment]
It worked.

**Comment by kyleconroy** [comment]
I’ll make sure to update the README with correct installation instructions
