### ISSUE TITLE
add instructions for Replay

### ISSUE THREAD

**Issue by kevinburkemeter** [kyleconroy/sqlc#356]
How do I invalidate the saved replays or update them, etc.

(Trying to add IP address and MAC address to one of the tests to ensure that everything works end to end)

**Comment by kyleconroy** [comment]
If you're just updating a single test, run `sqlc` in the test directory that you changed. I suggest building and installing a `sqlc-dev` binary that doesn't overwrite the sqlc you've installed locally.

```
go build -o ~/go/bin/sqlc-dev ./cmd/sqlc
cd internal/endtoend/testdata/name
sqlc-dev generate
```
