### ISSUE TITLE
Error: unknown PostgreSQL type: ltree

### ISSUE THREAD

**Issue by dharmjit** [kyleconroy/sqlc#377]
In DB schema I have ltree extension 
```
CREATE TABLE IF NOT EXISTS groups (
    id SERIAL PRIMARY KEY,
    name VARCHAR NOT NULL,
    fully_qualified_name ltree,
    scopes TEXT [],
    parent_id INTEGER REFERENCES groups (id),
    created_by VARCHAR REFERENCES users (username),
    created_on TIMESTAMP DEFAULT NOW()
);
```

and sqlc generate below error

```
2020/03/05 02:51:09 unknown PostgreSQL type: ltree
```

**Comment by kyleconroy** [comment]
sqlc currently does not have support for the [ltree](https://www.postgresql.org/docs/current/ltree.html) extension.

The error that's reported is just a warning; sqlc will scan the value into an empty interface. What type were you hoping for the ltree column to have?

**Comment by dharmjit** [comment]
I will be using string type inside ltree

**Comment by kyleconroy** [comment]
Okay, that makes adding support quite easy

**Comment by dharmjit** [comment]
Let me know if I can help with a PR.
