### ISSUE TITLE
Float or NUMERIC values seems unsupported?

### ISSUE THREAD

**Issue by blixenkrone** [kyleconroy/sqlc#378]
Consider the schema property types:
```
NUMERIC(6,9) NOT NULL,
NUMERIC(6,9) NOT NULL
```
This is being parsed as a string in the struct type. Is this a bug, or is this the intended value, or is the NUMERIC type seen as a string because of possible large decimals?

Cheers

**Comment by kyleconroy** [comment]
Numeric was added in #228 

> Since the Go standard library does not have a decimal type, lib/pq returns decimals and numerics as strings. You'll need to use a decimal library to properly support these values.

A comment from the original issue #227 suggest that you may want to use the https://github.com/shopspring/decimal package to parse decimal values. You can also use that package via [type-overrides](https://github.com/kyleconroy/sqlc#type-overrides).

Hope that helps!

**Comment by blixenkrone** [comment]
Appreciate it!
