### ISSUE TITLE
Incorrect binary Darmin AMD64 v1.0.0

### ISSUE THREAD

**Issue by myles-mcdonnell** [kyleconroy/sqlc#396]
Can you double check the version 1.0.0 DarwinAMD64 binary published here please: https://github.com/kyleconroy/sqlc/releases/tag/v1.0.0

unless I did something stupid it appears it is not compiled to Darwin AMD64

Thx

**Comment by kyleconroy** [comment]
I can't reproduce this. The following bash commands worked fine on my laptop.

```bash
$ curl -LO https://github.com/kyleconroy/sqlc/releases/download/v1.0.0/sqlc-v1.0.0-darwin-amd64.zip
$ unzip sqlc-v1.0.0-darwin-amd64.zip 
$ ./sqlc version
v1.0.0
```

What version of macOS are you running?
