### ISSUE TITLE
Release new patch version?

### ISSUE THREAD

**Issue by kevinburkemeter** [kyleconroy/sqlc#404]
There have been a lot of commits since version 1.0.1.

**Comment by kyleconroy** [comment]
The next version of sqlc is [1.1.0](https://github.com/kyleconroy/sqlc/milestone/2). It's scheduled to be released on March 17th. I'm planning on sticking to a four week release cycle. Do you think I need to make it three weeks?

**Comment by kevinburkemeter** [comment]
OK that's fine. FWIW, I'm installing sqlc from a `.deb` package in our test environment, and I have a test set up that ensures you ran "make sql" to generate the updated Go files from the sql files. Each time the generated file changes I need to recompile sqlc and re-upload a .deb so the sqlc version in the CI environment generates the correct Go source code.

It's fine, just would be easier to do if there was a different version number.

I suppose this is what e.g. `1.0.1-1`, `1.0.1-2` are for in Debian versioning.

**Comment by kyleconroy** [comment]
Just a reminder, this is happening today

**Comment by kevinburkemeter** [comment]
_ron paul happening gif_

**Comment by kyleconroy** [comment]
v1.1.0 has been released: https://github.com/kyleconroy/sqlc/releases/tag/v1.1.0

v1.2.0 is scheduled for release in three weeks.
