### ISSUE TITLE
PostgreSQL Array type search keywords ANY/ALL not working

### ISSUE THREAD

**Issue by dharmjit** [kyleconroy/sqlc#420]
Hi, I am trying to generate a query for array search which requires the literal to be on left hand side of the expression and I am getting below error

`no column reference found
`

Is this not supported or I am making some mistake.

**Comment by kyleconroy** [comment]
@dharmjit could you include a sample query and table that causes the issue? It's difficult to debug this issues without it.

**Comment by dharmjit** [comment]
Hi @kyleconroy , Below is the table structure and query I want to generate
```
CREATE TABLE IF NOT EXISTS applications (
    application_id VARCHAR NOT NULL PRIMARY KEY,
    application_name VARCHAR NOT NULL,
    application_version VARCHAR NOT NULL,
    application_owner VARCHAR,
    scope VARCHAR NOT NULL,
    created_on TIMESTAMP NOT NULL DEFAULT NOW()
);
```
And I am using query with dynamic filter as below
```
-- name: GetApplicationsView :many
SELECT a.application_id,a.application_name,a.application_owner
FROM applications a LEFT JOIN applications_instances ai ON a.application_id = ai.application_id
WHERE (CASE WHEN @is_product_id::bool THEN @product_id = ANY (ai.products) ELSE TRUE END)
```

**Comment by kyleconroy** [comment]
Thanks for the SQL. I was able to reproduce the result. To get this to work, you need to cast `@product_id` to text. Here's a link to a [playground](https://play.sqlc.dev/p/fa18fcd7620ebdd2e50ead5bd000ad80b6c767c5ba60fcb243fd3c2b51cd51e0) for your example.

```sql
-- name: GetApplicationsView :many
SELECT
  a.application_id,
  a.application_name,
  a.application_owner
FROM applications a
LEFT JOIN applications_instances ai
  ON a.application_id = ai.application_id
WHERE (
  CASE WHEN @is_product_id::bool
       THEN @product_id::text = ANY (ai.products)
       ELSE TRUE 
  END
);
```

The reason you need to add the cast is that sqlc's type inference is still very limited. It doesn't know the type of `any(ai.products)` should be text. I'm working on those improvements, but they won't land for a few more releases.
