### ISSUE TITLE
unknown MySQL type: double

### ISSUE THREAD

**Issue by myles-mcdonnell** [kyleconroy/sqlc#439]
Hi

I'm running sqlc from a local build 9e4a0e77bfe1dbf188c00ee972d326a341d0a5a3

I have reverse engineered a MySQL schema creation script using MySQL workbench and when I run `sqlc generate` I get;

```
unknown MySQL type: double 
```
 ..and..
```
unknown MySQL type: json
```

where ever those datatypes are referenced.  Apologies if this is MySQL noob stuff, I'm not a MySQL user.  I have inherited a MySQL DB that I'm migrating to PG hence why I'm using SQLC to build the migration tool having used SQLC very effectively with PG.

Thx
M

========= ADDENDUM ========

So I changed all the DOUBLE type to FLOAT and the JSON types to VARCHAR in the creation script (which may or may not work for me, I don't need to access all fields) just to move forward.  `sqlc genenerate` doesn't complain about about the schema creation script now but it does refused to parse my queries file:

```
-- name: SelectAllUsers :many
select
    *
from
    users;
```

error is:

```
db/mysql/queries/queries.sql:1:1: failed to parse query leading comment
```

**Comment by kyleconroy** [comment]
I'll look into the first issue, but the second issue is due to your comment prefix. You need to use `/* comment */` syntax:

```sql
/* name: SelectAllUsers :many */
select
    *
from
    users;
```

**Comment by kyleconroy** [comment]
```sql
CREATE TABLE example (jdoc JSON, num DOUBLE);

/* name: ListWebinars :many */
SELECT * FROM example;

```

```go
// Code generated by sqlc. DO NOT EDIT.

package querytest

import (
	"database/sql"
	"encoding/json"
)

type Example struct {
	Jdoc json.RawMessage
	Num  sql.NullFloat64
}
```
