### ISSUE TITLE
MySQL: unable to select TIMESTAMP field

### ISSUE THREAD

**Issue by myles-mcdonnell** [kyleconroy/sqlc#440]
I'm using this MySQL driver `github.com/go-sql-driver/mysql` and this version of SQLC 9e4a0e77bfe1dbf188c00ee972d326a341d0a5a3

When executing a select over field of type TIMESTAMP I get the following

```
panic: sql: Scan error on column index 59, name "{field_name}": unsupported Scan, storing driver.Value type []uint8 into type *time.Time
```

**Comment by JessBellon** [comment]
I had the same problem. The issue is with the mysql driver not sqlc. 
Check out these links: 
* https://stackoverflow.com/questions/29341590/how-to-parse-time-from-database/29343013#29343013
* https://github.com/go-sql-driver/mysql#parsetime
