### ISSUE TITLE
How to declare a param as nullable?

### ISSUE THREAD

**Issue by maxhawkins** [kyleconroy/sqlc#451]
If I have this simple table with some non-nullable columns
```sql
CREATE TABLE users (
  id BIGINT PRIMARY KEY,
  email TEXT NOT NULL,
);
```

When you reference those columns sqlc returns a non-nullable param
```sql
-- name: GetByID
SELECT * FROM users WHERE id = $1

==>
func (q *Queries) GetByID(ctx context.Context, id int64) (User, error)
```

But sometimes you want the param to be nullable:
```sql
SELECT *
FROM foo
WHERE
  id = @user_id_if_set
  OR email = @email_if_set
```

All these params should be nullable so you can set either of them and search either by id or email.

Is it possible to make the type of a parameter nullable for just one query?

**Comment by kyleconroy** [comment]
> Is it possible to make the type of a parameter nullable for just one query?

Not currently. This goes back to #210, in which we discussed that all SQL parameters can be NULL. It's probably too late to change the existing default behavior.

There are a few options we can consider. One would be a global setting `emit_nullable_params`, which would make all parameters null. My guess is that this wouldn't be very helpful, as you're looking for control at the query level.

Another option would be to fix #133 and properly support NULLIF. You could then write

```sql
SELECT *
FROM foo
WHERE
  id = NULLIF(@user_id, '')
  OR email = NULLIF(@email, '')
```

Third, we could add an optional named parameter to the `sqlc.arg` function.

```
SELECT *
FROM foo
WHERE
  id = sqlc.arg('user_id', nullable => true)
  OR email = sqlc.arg('email', nullable => true)
```

I'm not set on the `nullable` argument name. Any suggestions would be welcome.

**Comment by maxhawkins** [comment]
Supporting NULLIF would be a fine intermediary step.

If there was some throwaway condition I could add to the query to indicate nullability that would fix the problem for me, albeit in a hacky way. Adding a NULLIF like this would be a no-op:

```sql
SELECT *
FROM foo
WHERE
  id = NULLIF(@user_id_if_set, NULL)
  OR email = NULLIF(@email_if_set, NULL)
```

The sqlc.arg thing seems like a better solution for the long term.

Would the Ruby-style hash params (`=>`) parse in a standard Postgres parser? Eventually I'd like to run my queries through a pretty-printer on save, so it would be convenient if the syntax was compatible.

**Comment by kyleconroy** [comment]
> Would the Ruby-style hash params (=>) parse in a standard Postgres parser?

Yep! https://www.postgresql.org/docs/current/sql-syntax-calling-funcs.html#SQL-SYNTAX-CALLING-FUNCS-NAMED

**Comment by maxhawkins** [comment]
I learned something today

**Comment by kyleconroy** [comment]
You and I both. I had no idea.
