### ISSUE TITLE
Add a Darwin .tar.gz archive to the release assets

### ISSUE THREAD

**Issue by soroushj** [kyleconroy/sqlc#452]
Currently, release assets include a Linux .tar.gz and a Darwin .zip archive. Adding a Darwin .tar.gz archive will make it easier to write automation scripts, e.g., a script for downloading the correct binary based on the current platform. This can be considered for future releases.

**Comment by kyleconroy** [comment]
I've added `.tar.gz` for the three tagged released (v1.0.0, v1.1.0, v1.2.0). Development releases (https://dl.equinox.io/sqlc/sqlc/devel) also have .tar.gz for Darwin.
