### ISSUE TITLE
Add support for ARM architecture

### ISSUE THREAD

**Issue by aitva** [kyleconroy/sqlc#457]
I built sqlc on an ARM64 laptop and I got this error:

```
# github.com/lfittl/pg_query_go/parser
In file included from go/src/github.com/lfittl/pg_query_go/parser/include/utils/dsa.h:17:0,
                 from go/src/github.com/lfittl/pg_query_go/parser/include/nodes/tidbitmap.h:26,
                 from go/src/github.com/lfittl/pg_query_go/parser/include/access/genam.h:19,
                 from go/src/github.com/lfittl/pg_query_go/parser/include/nodes/execnodes.h:17,
                 from go/src/github.com/lfittl/pg_query_go/parser/include/commands/trigger.h:17,
                 from go/src/github.com/lfittl/pg_query_go/parser/include/plpgsql.h:21,
                 from pg_query_json_plpgsql.h:5,
                 from pg_query_json_plpgsql.c:2:
go/src/github.com/lfittl/pg_query_go/parser/include/port/atomics.h:68:35: fatal error: port/atomics/arch-arm.h: No such file or directory
 #include "port/atomics/arch-arm.h"
                                   ^
compilation terminated.
```

There is an open issue lfittl/pg_query_go#27 for ARM support in *pg_query_go*. Using the fix mentioned and `go mod edit` I was able to build a working version of sqlc.

If you are interested, I can fork *pg_query_go* and fix lfittl/pg_query_go#24, lfittl/pg_query_go#26 and lfittl/pg_query_go#27.

**Comment by kyleconroy** [comment]
> If you are interested

Very interested!

> I can fork pg_query_go and

I'm actually going to need to fork pg_query_go to add support for PostgreSQL 11 and 12. I created my work fork here (https://github.com/kyleconroy/pg_query_go/) and added you as a collaborator. You can do the work there, or just do the work on your own fork and I'll pull it into mine. Up to you.

**Comment by kyleconroy** [comment]
> Sorry for the long post, don't hesitate if you have any questions or suggestions.

Don't apologize, this is awesome! I've been heads down on type-checking internals, so it's super interesting to learn how pg_query_go works.

Right now, I think it's more important to update pg_query_go to Postgres 12. If we do that first, we can then solve a bunch of issues before starting the ARM port.

**Comment by aitva** [comment]
I sent a pull request #779 to update https://github.com/lfittl/pg_query_go to v1.0.1. The release adds ARM header files and the build is passing on my machine.

**Comment by kyleconroy** [comment]
@aitva I believe we're now using the new version of pg_query_go. What do I need to do next?

**Comment by aitva** [comment]
Thank you for the fix! I miss the pull request from dependabot. We can close the issue, `go get` and `go build` are working on arm machines. 🥳
