### ISSUE TITLE
Multiple model fields generated for COALESCE

### ISSUE THREAD

**Issue by myles-mcdonnell** [kyleconroy/sqlc#458]
`sqlc version:  v1.1.1-devel`

DB: Postgres

Given the following statement in a select list:

`COALESCE(ua.firstnames, ti.firstnames) as tenantfirstnames`

This results it 2 fields in the generated Row model:

```
&i.Tenantfirstnames,
&i.Tenantfirstnames_2,
```

which is erroneous and causes execution of the query to fail

**Comment by tv42** [comment]
I just got hit by this one too.

**Comment by tv42** [comment]
It seems you can workaround it by `coalesce(a, b)::text` (adjust type to fit).
