### ISSUE TITLE
Introduction webpage links broken

### ISSUE THREAD

**Issue by Maxiride** [kyleconroy/sqlc#460]
Premise: I stumbled upon this tool only this morning and I've found it **awesome**, I'm speechless that it didn't pop up earlier in my SQL with GO brainstorming for ORMs etc, good job devs and keep going! 💪🚀

---

Anyway, I was browsing and reading to learn and eventually present sqlc to my colleagues and I noticed that the homepage https://sqlc.dev/ has an [introduction](https://conroy.org/introducing-sqlc) link, however in that page many links are broken, namely all the links under the _Packed with power_ section about at the end of the page.

**Comment by kyleconroy** [comment]
Thanks for the report! I've fixed all the broken links.
