### ISSUE TITLE
Unsed import fmt when emitting prepared queries

### ISSUE THREAD

**Issue by gpontesss** [kyleconroy/sqlc#468]
In golang, if you specify at `sql.yaml` you want to emit prepared queries and you don't have any query defined, `db.go` will have fmt as an unsed import. For now, you have to either disable `emit_prepared_queries` or remove the import manually (not ideal for generated code).

**Comment by kyleconroy** [comment]
> you don't have any query defined

sqlc will fail to generate code if it can't find any queries. If this is still an issue, please post a `sqlc.yaml` file and associated SQL files that causes the issue.
