### ISSUE TITLE
Add support for pgx

### ISSUE THREAD

**Issue by kyleconroy** [kyleconroy/sqlc#472]
Get out the trumpets and ready the 21-gun salute, `lib/pq` is deprecated (#470). This means it's time to support it's successor, pgx.

This will be the main tracking issue for pgx. It supersedes #28, as I have no intention of adding support for any additional PostgreSQL drivers beyond pgx.

**Comment by ldelossa** [comment]
We currently use PGX and it's batching mechanism. Would be great if you keep pgx batching in mind while this unfolds.

**Comment by kyleconroy** [comment]
@ldelossa Do you have an example of the batching API? This is the first I've heard of it

**Comment by ldelossa** [comment]
@kyleconroy we wrap it a bit to handle variable sized input: 
https://github.com/quay/claircore/blob/master/pkg/microbatch/microbatch.go

usage:
https://github.com/quay/claircore/blob/master/internal/indexer/postgres/indexpackage.go#L96

**Comment by powersjcb** [comment]
pgx is new to me, so I wanted to spend some time getting the driver working for the example in `examples/booktest/postgresql/`. Here's a quick diff of that: https://github.com/powersjcb/sqlc/pull/1

Some learnings:
- Several fields in `pgtype` do not implement `MarshalJSON`. (`pgtype.Timestamp` `pgtype.VarcharArray` So at first glance, it looks like fields wont be compatible with the `emitjsontags` feature of sqlc.
- Many fields need to be initialized and then have a value Set into them using the following signature `(dst *Timestamp) Set(src interface{}) error`. User application code will need to type check inputs at runtime.  For example`err := Timestamp{}.Set("asdf")` wont fail to compile.

**Comment by maxhawkins** [comment]
Awesome!

It would be cool to support decoding [composite types](https://godoc.org/github.com/jackc/pgx#hdr-Composite_types_and_row_values) at some point. It's pretty tedious to implement `DecodeBinary` since you have to pull out every value from the `pgtype.Record` by hand. Since we know the schema that could be automated and save a lot of time.

**Comment by maxhawkins** [comment]
>     * Several fields in `pgtype` do not implement `MarshalJSON`. (at least `pgtype.Timestamp` and `pgtype.VarcharArray`) So at first glance, it looks like fields wont be compatible with the `emitjsontags` feature of sqlc.

In the booktest example at least, the `available` column uses `timestamptz` whose `pgtype` counterpart `Timestamptz` does support JSON. Regardless I'm not sure it's a problem that raw timestamps don't have a JSON encoding. JSON times always have a zone and Postgres timestamps are ambiguous about what zone they're in so there's no natural conversion.

**Comment by mvrhov** [comment]
Do you really need to support pgtype... There are a lot of times you don't need it.. and pointer to native type is enough. This also means that you can use the same struct through most application and there is no need to convert between db struct and "domain" struct.  The onl conversion is then for viewing purposes.

**Comment by johanbrandhorst** [comment]
I noticed we're still using `pq.Array` for postgres array type (e.g. `TEXT[]` becomes `pq.Array([]string)`). Is it possible for these types to map to the pgx types instead (i.e. `TEXT[]` becomes `pgtype.TextArray`)? I tried using an override and it didn't seem to work in 1.4.0.

**Comment by georgysavva** [comment]
Does this mean that you are planning to support pgx native interface i.e. [pgxpool](https://pkg.go.dev/github.com/jackc/pgx/v4/pgxpool?tab=doc)? 
Or pgx as a driver to `database/sql` i.e. [pgx stdlib](https://pkg.go.dev/github.com/jackc/pgx/v4/stdlib?tab=doc)

**Comment by tv42** [comment]
pgx/stdlib works well already.

**Comment by kyleconroy** [comment]
@georgysavva the plan is to support pgx/stdlib first, and then add support for pgxpool.

**Comment by georgysavva** [comment]
@kyleconroy Thanks for explaining. 
It would be a great improvement to fully support pgx, can't wait for it!

**Comment by Streppel** [comment]
Hey guys! @kyleconroy do we have any updates on this? I've just hit this wall unfortunately

**Comment by Streppel** [comment]
Hey everyone,

so I ended up doing something that worked out fine for me. You can check what's different [in this commit](https://github.com/Streppel/sqlc/commit/c5f31058acdb148dca2ba759bcbc3ec0df2d7756).

![itaintmuch](https://user-images.githubusercontent.com/2300328/103106383-d9f58000-4613-11eb-92b2-ab39d5f0b526.jpeg)

Usage remains equal, except that you need to inform a new parameter at the startup configuration yml file, as in

```yaml
version: "1"
packages:
    sql_library: "pgx/v4"
```

I'm not very fond of this name I've used but couldn't think of anything better at the time. From my restricted testing everything looks fine to me. If you guys find it interesting we can try to merge it.

**Comment by Streppel** [comment]
Hey everyone, just in time for christmas

I ended up doing something that worked out fine for me. You can check what's different [in this commit](https://github.com/Streppel/sqlc/commit/c5f31058acdb148dca2ba759bcbc3ec0df2d7756).

![itaintmuch](https://user-images.githubusercontent.com/2300328/103106383-d9f58000-4613-11eb-92b2-ab39d5f0b526.jpeg)

Usage remains equal, except that you need to inform a new parameter at the startup configuration yml file, as in

```yaml
version: "1"
packages:
    sql_library: "pgx/v4"
```
If this parameter is missing it defaults to the old behavior. 

I'm not very fond of this name I've used but couldn't think of anything better at the time. From my restricted testing everything looks fine to me.

**Comment by Streppel** [comment]
@kyleconroy and others: even though the above fits my use case (which is indeed very simple at this moment) it still is very premature in many aspects to even consider opening a pull request. Despite that, do you think the changes made here are heading in the right direction? If so, we could maybe merge this on a new development branch and continue work over there

**Comment by kevinburkemeter** [comment]
Just following up here - found another data race in lib/pq and it would be great to have a chance to evaluate other drivers, but at the moment we're pretty tied to using sqlc.

**Comment by tv42** [comment]
@kevinburkemeter pgx/stdlib works ok with sqlc.

**Comment by kevinburkemeter** [comment]
working on that. is there a currently supported way to replace `pq.Array`?

**Comment by mvrhov** [comment]
afaik you don't need it for standard types.

**Comment by kevinburkemeter** [comment]
`pq.Array` is part of github.com/lib/pq, a competing SQL driver, not part of the standard library, so it seems unlikely pgx would support it

**Comment by johanbrandhorst** [comment]
`pq.Array` implements the `database/sql/driver.Valuer` and `database/sql.Scanner` interfaces, so it works fine with `pgx` in my testing. It's a bit messy to import both, but it works.

**Comment by johanbrandhorst** [comment]
Did #1037 replace the use of `pq.Array` for postgres arrays? Otherwise I wouldn't consider this issue completely closed.

**Comment by esenmx** [comment]
@johanbrandhorst Is it possible to generate `pgtype.TextArray`? I'm fighting with source codes and sqlc.yaml couldn't find a way yet.

**Comment by johanbrandhorst** [comment]
I don't think is it, yet.

**Comment by johanbrandhorst** [comment]
I created https://github.com/kyleconroy/sqlc/issues/1276 and https://github.com/kyleconroy/sqlc/issues/1275 to track removal of `pq.Array` and support of batching, respectively.
