### ISSUE TITLE
Development on windows is impossibile due to upstream issues

### ISSUE THREAD

**Issue by Maxiride** [kyleconroy/sqlc#476]
Upstream report: https://github.com/lfittl/pg_query_go/issues/25

Just reporting here too that development on windows can't be done due to the sqlc dependency `github.com/lfittl/pg_query_go` which can't be imported and built due to lack of windows support.

This is **not** a sqlc bug but if anyone here has a workaround I'd be happy to hear it since this issue hinders my attempt to work on the package.

**Comment by kyleconroy** [comment]
See a few previous reports about Windows support: #307 #282 

Candidly, I'm not sure that pg_query_go is being actively maintained. We may need to fork it to add Windows support and upgrade it to the most recent release of PostgreSQL.

**Comment by Maxiride** [comment]
> See a few previous reports about Windows support: #307 #282

I'm sorry I didn't notice them. Given that #282 is still open, my issue is a duplicate. Closing it.
