### ISSUE TITLE
Error with PostgreSQL JOIN LATERAL

### ISSUE THREAD

**Issue by mmcloughlin** [kyleconroy/sqlc#482]
The following query produces error `query/changes.sql:x:y: empty edit contents`
```sql
-- name: ChangeSummaries :many
SELECT
    chg.*,
    c.sha AS commit_sha,
    SPLIT_PART(c.message, E'\n', 1)::TEXT AS commit_subject,

    b.*,
    pkg.relative_path,
    mod.path,
    mod.version
FROM
    commit_positions AS p
    INNER JOIN LATERAL (
        SELECT
            *
        FROM
            changes
        WHERE 1=1
            AND commit_index=p.index
            AND ABS(effect_size) > 5
        ORDER BY
            effect_size DESC
        LIMIT
            5
    ) AS chg ON 1=1
    INNER JOIN commits AS c
        ON p.sha=c.sha
    INNER JOIN benchmarks AS b
        ON chg.benchmark_uuid=b.uuid
    INNER JOIN packages AS pkg
        ON b.package_uuid=pkg.uuid
    INNER JOIN modules AS mod
        ON pkg.module_uuid=mod.uuid
WHERE 1=1
    AND p.index BETWEEN 42046 AND 42346
;
```
I highly suspect the problem here is related to `JOIN LATERAL`, but I have not confirmed it.

**Comment by ScottyFillups** [comment]
Any update here?

**Comment by kyleconroy** [comment]
@mmcloughlin I can't reproduce this without the associated database schema. If this is still an issue for you, please include the schema or a smaller query that reproduces the problem.

**Comment by mmcloughlin** [comment]
No worries, I was able to structure the query a different way so it didn't block me. It might take a bit of effort to extract out a minimal reproducer. If you have other tests for lateral join that should be enough. Thanks!
