### ISSUE TITLE
mysql: limit and offset name issue

### ISSUE THREAD

**Issue by digitive** [kyleconroy/sqlc#501]
The following query 
```
/* name: ListAccounts :many */
select * from account limit ?,?;
```
will produce
```
type ListAccountsParams struct {
	Limit   uint32 `json:"limit"`
	Limit_2 uint32 `json:"limit_2"`
}
```
Since mysql takes the first parameter as offset and the second as count limit, the generated var `Limit` should be `Offset` where `Limit_2` should be `Limit`.

**Comment by kyleconroy** [comment]
The `mysql:beta` engine generates the correct parameters names

```go
// Code generated by sqlc. DO NOT EDIT.
// source: query.sql

package querytest

import (
	"context"
	"database/sql"
)

const getAllSomeTable = `-- name: GetAllSomeTable :many
SELECT a
FROM foo
LIMIT ?, ?
`

type GetAllSomeTableParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) GetAllSomeTable(ctx context.Context, arg GetAllSomeTableParams) ([]sql.NullString, error) {
	rows, err := q.db.QueryContext(ctx, getAllSomeTable, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []sql.NullString
	for rows.Next() {
		var a sql.NullString
		if err := rows.Scan(&a); err != nil {
			return nil, err
		}
		items = append(items, a)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
```

**Comment by kaharman** [comment]
Hi @kyleconroy,

It is still a bug. I switch

```rows, err := q.db.QueryContext(ctx, getAllSomeTable, arg.Limit, arg.Offset)```

to 

```rows, err := q.db.QueryContext(ctx, getAllSomeTable, arg.Offset, arg.Limit)```

fix the problem.

Here is the reference https://www.w3schools.com/php/php_mysql_select_limit.asp

MySQL syntax for shorter form for LIMIT OFFSET is ```LIMIT <offset>, <limit>``` not the other way around.
