### ISSUE TITLE
BIGSERIAL does not match postgresql spec

### ISSUE THREAD

**Issue by Bluskript** [kyleconroy/sqlc#503]
When SQLC generates code for postgres, it interprets BIGSERIAL as `int64`, when according to the postgres spec it is actually `uint64`
reference : https://www.postgresql.org/docs/9.1/datatype-numeric.html

**Comment by maxhawkins** [comment]
I believe int64 is actually the correct type here.

`BIGSERIAL` is just a convenient notation for a `NOT NULL BIGINT` column with an auto-incrementing sequnce attached. There's nothing stopping you from adding a row with a negative value on a `BIGSERIAL` column.

For instance, this statement is valid:

```sql
CREATE TABLE foo ( foo_id BIGSERIAL );
INSERT INTO foo ( foo_id ) VALUES ( -1 ) ;
```

**Comment by kyleconroy** [comment]
Thanks @maxhawkins. Sounds like the current behavior is correct.
