### ISSUE TITLE
case for structs

### ISSUE THREAD

**Issue by kevinburkemeter** [kyleconroy/sqlc#522]
I have the following in SQL:

```sql
CREATE TYPE ip_protocol AS enum('tcp', 'ip', 'icmp');
```

Which generates the unglamorous:

```go
type IpProtocol string

const (
	IpProtocolTcp  IpProtocol = "tcp"
	IpProtocolIp   IpProtocol = "ip"
	IpProtocolIcmp IpProtocol = "icmp"
)
```

I'm wondering if there's a way to control the case of the generated constants.

**Comment by kyleconroy** [comment]
Rename support currently doesn't apply to enum constant values. Here's the line that would need to change: https://github.com/kyleconroy/sqlc/blob/master/internal/compiler/result.go#L104
