### ISSUE TITLE
go: json.Marshal of empty rows result encodes to `null` rather than `[]`

### ISSUE THREAD

**Issue by powersjcb** [kyleconroy/sqlc#526]
`json.Marshal` encodes `null` for all empty results rather than `[]`.

# Example
When this function returns an empty list, the result is marshaled to `null`.

https://github.com/powersjcb/monitor/blob/be4992358e6f3589d5095fca88f6f179b4483842/go/src/server/db/metric.sql.go#L37

I was able to resolve this by changing the way the empty results are instantiated.

`var items = []ResultRow` -> `items := make([]ResultRow, 0)`

https://github.com/golang/go/issues/26866
https://apoorvam.github.io/blog/2017/golang-json-marshal-slice-as-empty-array-not-null/

**Comment by powersjcb** [comment]
Should have a PR open for this in a few min.

**Comment by kyleconroy** [comment]
@powersjcb Thanks for the bug report and the pull request.

I've decided to keep the existing behavior. Marshalling a nil slice is documented behavior in the `json/encoding` package. This change could break existing applications that rely on the current behavior. I also like the fact that memory isn't allocated if the query returns zero results.

I hope you understand and I'm sorry you spent time putting together a PR only to have it not merged.

**Comment by kyleconroy** [comment]
Fixed by #551 and #528
