### ISSUE TITLE
Ungraceful error when mysql queries specify :one without a returning value

### ISSUE THREAD

**Issue by inconshreveable** [kyleconroy/sqlc#532]
```
/* name: Insert :one */
INSERT INTO foo (name)
VALUES (?);
```

Expected:
```
query "Insert" specifies parameter ":one" without containing a RETURNING clause
```

Got:
```
error generating code: template: table:237:77: executing "queryCode" at <.Ret.Type>: error calling Type: no type for GoQueryValue:
```

**Comment by aclowkey** [comment]
How can I specify returning values?
I think it fails in mysql parsing phase

**Comment by nitrajka** [comment]
Unfortunately, there is no such thing as `RETURNING` in MySQL. Instead, you have to use one more SELECT after an insert/delete as follows: `select LAST_INSERT_ID()`. I suppose, that after you select this ID, you are able to select the whole entity based on this ID.

**Comment by markschmid** [comment]
Unfortunately, at least with the dolphin parser (1.5.0), ```select LAST_INSERT_ID()``` can't be correctly parsed. I need this ID, but since it is specific to the connection, I can't get it using a different client/connection (e.g. pure ```database/sql```).
Any ideas?

**Comment by markschmid** [comment]
> Any ideas?

OK, one (very "dirty") workaround is obviously: ```select id from <table> order by id desc limit 1```
(```max()``` is currently not available in sqlc either)

Of course, getting the inserted id like this is all but safe.

**Comment by kyleconroy** [comment]
The `mysql:beta` engine now returns a the proper error message:

> # package querytest
> query.sql:3:1: query "Insert" specifies parameter ":one" without containing a RETURNING clause

If you'd like to get the ID of the inserted row, you can use `:execresult` and call the [LastInsertID](https://golang.org/pkg/database/sql/#Result) method on the result.

```sql
/* name: Insert :execresult */
INSERT INTO foo (name)
VALUES (?);
````

```go
// Code generated by sqlc. DO NOT EDIT.
// source: query.sql

package querytest

import (
	"context"
	"database/sql"
)

const insert = `-- name: Insert :execresult
INSERT INTO foo (a)
VALUES (?)
`

func (q *Queries) Insert(ctx context.Context, a sql.NullString) (sql.Result, error) {
	return q.db.ExecContext(ctx, insert, a)
}
```

**Comment by mgyong** [comment]
@kyleconroy Just to confirm, for any mysql code that returns one we basically have to use :execresult  as there is no solution for mysql `":one" without containing a RETURNING clause`
