### ISSUE TITLE
Add support for custom struct tags

### ISSUE THREAD

**Issue by philippta** [kyleconroy/sqlc#534]
When working with structs, struct tags are used to add additional information to a field. This is for example very common when using validation packages. But currently there is no way to add additional struct tags to take advantage of this. 

I think it would be a great idea to add a comment syntax just like the `-- name:NameForQuery` for table columns. 

A possible option to express these custom struct tags would be to write create table statements like this:
```sql
CREATE TABLE user (
  id   BIGSERIAL PRIMARY KEY,

  -- tags:`validate:"min=10,max=0"`
  username text NOT NULL,

  -- tags:`validate:"gt=18"`
  age  integer NOT NULL,

  -- tags:`validate:"url"`
  website text NOT NULL
);
```

or alternatively:
```sql
CREATE TABLE user (
  id   BIGSERIAL PRIMARY KEY,
  username text NOT NULL,     -- tags:`validate:"min=10,max=0"`
  age integer NOT NULL,       -- tags:`validate:"gt=18"`
  website text NOT NULL       -- tags:`validate:"url"`
);
```

**Comment by huangc28** [comment]
Has anyone pickup this enhancement yet?

**Comment by fr3fou** [comment]
Is there a way to achieve this now?
I want to ignore the password field on my user struct, like so
```go
type User struct {
    Password string `json:"-"`
}
```

**Comment by eliaschampi** [comment]
any solution for this issue please?

**Comment by tamoore** [comment]
@kyleconroy Would you be open to a solution that utilised the config overrides?

Something like the following:

```yaml
overrides:
  - column: "chat.id"
    custom_tag_key: "gorm"
    go_type: 
      type: "int"
```

I think this might also need something like `custom_tag_value` for instances like `validate` where consumers want to set a custom value. Otherwise, the default would be whatever the json emit type is set to. 

Further to the above, this wouldn't override json tags, it would be in addition to emitting json tags.

**Comment by preslavrachev** [comment]
@kyleconroy can we hope to see a feature like this in the foreseeable future? In my project, we started using Gorm way back in time, and it has been something we have been considering moving away from (towards sqlc). However, we rely on some 3rd party code that uses Gorm under the hood, so completely running away from it isn't feasible at the moment.

If there were a way to let sqlc generate our Gorm-compatible models, this would be fantastic. It's the one thing that's stopping us from getting all in on sqlc.

The only other alternative is still keep two copies of each model, which isn't that bad, but possibly error-prone.

**Comment by austincollinpena** [comment]
I agree that this seems like a good thing to add to the configuration file.

**Comment by josharian** [comment]
We're facing this right now as well. I'm game to work on it, if we can get to an agreement about the design.

FWIW, I would prefer adding custom struct tags to the config file, using something like:

```yaml
overrides:
  - column: chat.id
    go_struct_tag: 'validate:"required" sometagtype:"some_value"'
```

**Comment by austincollinpena** [comment]
I like that design

**Comment by josharian** [comment]
Implemented in https://github.com/kyleconroy/sqlc/pull/1569 if anyone wants to kick the tires.
