### ISSUE TITLE
Parameter type incorrectly determined

### ISSUE THREAD

**Issue by pconstantinou** [kyleconroy/sqlc#543]
See in the generated code below where $1 is interpreted as a timestamp when it should be interpreted as a number.

The objective of the code is to group time blocks by periods of time. $1 (used twice).

Turns out trunc with a negative will do the trick, but it may help someone else.

```
const countTest = `-- name: CountTest :one
select count(*) from (
			select 
				to_timestamp(floor((extract('epoch' from measurement_timestamp) / 60 / **$1** )) * 60 * **$1**) 
					AT TIME ZONE 'UTC' as measurement_time_period
			from measurement
			group by measurement_time_period
			) as r
`

func (q *Queries) CountTest(ctx context.Context, **measurementTimestamp time.Time**) (int64, error) {
	row := q.db.QueryRowContext(ctx, countTest, measurementTimestamp)
	var count int64
	err := row.Scan(&count)
	return count, err
}
````

**Comment by aitva** [comment]
I have found a similar problem. With the following migrations:

```sql
-- schema/0001_messages.sql
CREATE TABLE messages (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT current_timestamp,
    content TEXT NOT NULL,
    external_id UUID
);
```

```sql
-- schema/0002_update_messages.sql
ALTER TABLE messages ALTER external_id TYPE UUID ARRAY USING ARRAY[external_id];
```
The new parser conclude that the `external_id` field is of type `UUID`.

I have made a small repository to experiment with the problem: https://github.com/aitva/sqlc-parser-bug

**Comment by aitva** [comment]
What I found might not be related to the problem of @pconstantinou. I tried multiple variations of the code in my previous comment and my problem seems to be related to `ARRAY` type  and the `ALTER TABLE`.

I found that the following code works:

```sql
-- schema/0001_messages.sql
CREATE TABLE counter (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    value INT ARRAY NOT NULL
);
```

But this one does not:

```sql
-- schema/0001_messages.sql
CREATE TABLE counter (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    value INT NOT NULL
);
```
```sql
-- schema/0002_update_messages.sql
ALTER TABLE messages ALTER value TYPE INT ARRAY USING ARRAY[value];
```

**Comment by kyleconroy** [comment]
@aitva It's not clear if this is still an issue. Can you please test using the latest version (v1.9.0) of sqlc? If it is, can you open a new issue with the database schema and queries that cause the issue?
