### ISSUE TITLE
undefined: sqlparser.ParenExpr

### ISSUE THREAD

**Issue by mflaxman** [kyleconroy/sqlc#545]
I'm following the instructions on [this youtube video](https://youtu.be/uBPXNREhZZw?t=110) and getting an error at the first step.

```
$ go get github.com/kyleconroy/sqlc/cmd/sqlc
# github.com/kyleconroy/sqlc/internal/mysql
/Users/mflaxman/gocode/src/github.com/kyleconroy/sqlc/internal/mysql/param.go:113:8: undefined: sqlparser.ParenExpr
```

Apologies if I'm doing something incorrectly, I'm new to golang so this easily could be my own fault.

**Comment by kyleconroy** [comment]
sqlc requires Go modules to work correctly. In your case, the go tool is fetching the latest version of a dependency, ignoring the `go.mod` file at the root of the sqlc module.

To fix this, execute the `go get` command in a Go module directory

```
$ go mod init github.com/mflaxman/sqlc .
$ go get github.com/kyleconroy/sqlc/cmd/sqlc
```

If you're just looking to install the sqlc binary, there are easier ways. I'd suggest looking at the snapcraft of homebrew sections in the [Installation](https://github.com/kyleconroy/sqlc#installation) guide.
