### ISSUE TITLE
Function with named parameter produces invalid Golang struct and SQL query

### ISSUE THREAD

**Issue by ryanwmoore** [kyleconroy/sqlc#576]
Using sqlc 1.4.0 + Postgres 11.8. This is a reproduction of the same behavior I saw in a real/non-trivial query.

Given:

```sql
-- name: Demo :one
SELECT uuid_generate_v5('7c4597a0-8cfa-4c19-8da0-b8474a36440d', @param)::uuid as col1
;
```

Produces the following:

```golang
const demo = `-- name: Demo :one
SELECT uuid_generate_v5('7c4597a0-8cfa-4c19-8da0-b8474a36440d', $1)::uuid as col1
`

type DemoParams struct {
	Param interface{}
	Param interface{}
}

// SELECT @other as col2, uuid_generate_v5('7c4597a0-8cfa-4c19-8da0-b8474a36440d', @param::varchar)::uuid as col1
func (q *Queries) Demo(ctx context.Context, arg DemoParams) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, demo, arg.Param, arg.Param)
...
```

The problems that I see are:

1. The Param field is duplicated
2. The generated string query has only 1 parameter, but QueryContext is called with 2

**Comment by kyleconroy** [comment]
Hey, sorry this took so long to get fixed. The latest tip release should now work for you.

**Comment by kyleconroy** [comment]
I just merged the first version of PostgreSQL extension support (#640). This means you no longer have to include the `::uuid` cast in your query. Just make sure to include the necessary `CREATE EXTENSION` call.

```sql
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- name: Demo :one
SELECT uuid_generate_v5('7c4597a0-8cfa-4c19-8da0-b8474a36440d', $1) as col1;
```
