### ISSUE TITLE
Call to PostgreSQL Crypt() in query generates incorrect params

### ISSUE THREAD

**Issue by ttt733** [kyleconroy/sqlc#577]
SQL used:
```
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- name: CreateUser :one
INSERT INTO users (
    name,
    password_hash,
    email,
  ) VALUES (
    $1, CRYPT($2, gen_salt('bf')), $3
  )
  RETURNING *;
```
Go code generated:
```
type CreateUserParams struct {
	Name        string
	Crypt       interface{}
	Crypt       interface{}
	Email       sql.NullString
}
```

Please let me know if I'm misunderstanding something about the way extensions are supposed to work with sqlc. (Obviously in this specific example I can just move the crypto work into the Go code, but I would prefer to do it in the SQL if possible.)

**Comment by ryanwmoore** [comment]
Seems very similar to #576 to me.

**Comment by ttt733** [comment]
You're right - I find it interesting that this one manages to take the name Crypt while your generated code just takes the name Param. I'll close this one since yours came first.

**Comment by kyleconroy** [comment]
Hey, sorry this took so long to get fixed. The latest tip release should now work for you.
