### ISSUE TITLE
int8 and int2, unknown PostgreSQL types

### ISSUE THREAD

**Issue by frederikhors** [kyleconroy/sqlc#578]
_Forgive me in advance: I'm completely new on sqlc._

They gave me this `schema.sql`:

```sql
DROP TABLE IF EXISTS "public"."teams";
CREATE TABLE "public"."teams" (
  "id" int8 NOT NULL DEFAULT nextval('teams_id_seq'::regclass),
  "created_at" timestamptz(6) NOT NULL DEFAULT now(),
  "updated_at" timestamptz(6),
  "account_id" int8 NOT NULL,
  "name" text COLLATE "pg_catalog"."default"
)
;

DROP TABLE IF EXISTS "public"."players";
CREATE TABLE "public"."players" (
  "id" int8 NOT NULL DEFAULT nextval('players_id_seq'::regclass),
  "created_at" timestamptz(6) NOT NULL DEFAULT now(),
  "updated_at" timestamptz(6),
  "account_id" int8 NOT NULL,
  "type" int2,
  "score" int8 NOT NULL,
)
;
```

During generation sqlc writes many times:

```log
unknown PostgreSQL type: int8
unknown PostgreSQL type: int2
unknown PostgreSQL type: int8
unknown PostgreSQL type: int2
```

**Why?**

**Comment by kyleconroy** [comment]
> The type names int2, int4, and int8 are extensions, which are also used by some other SQL database systems.

I didn't know these types needed to be supported, working on a fix now.

**Comment by frederikhors** [comment]
Thanks.

Can you please release in latest on Docker?

**Comment by kyleconroy** [comment]
Major releases of sqlc happen every three weeks. If you're looking to get this bug fix now, you can use the [devel](https://hub.docker.com/layers/kjconroy/sqlc/devel/images/sha256-7ff0a3be4769c9a6765e8609a047a97998d544f973bfe4418beee172bcd9373e?context=repo) tag in the Docker repository.
