### ISSUE TITLE
Postgresql functions

### ISSUE THREAD

**Issue by Jimmy99** [kyleconroy/sqlc#585]
Is it possible to execute a postgresql function using sqlc and if so, what is the recommended approach?

**Comment by kyleconroy** [comment]
You can call functions just like you would in SQL queries. Take a look at this [example](https://play.sqlc.dev/p/e1da691edbdad57468726da0ecab98e623bb786a4b7d7eee8bb24c2bc44f7d7d) which calls the [pg_advisory_unlock](https://www.postgresql.org/docs/current/functions-admin.html#FUNCTIONS-ADVISORY-LOCKS) function.

```sql
-- name: AdvisoryLock :exec
SELECT pg_advisory_unlock($1);
```

```go
// Code generated by sqlc. DO NOT EDIT.
// source: query.sql

package db

import (
	"context"
)

const advisoryLock = `-- name: AdvisoryLock :exec
SELECT pg_advisory_unlock($1)
`

func (q *Queries) AdvisoryLock(ctx context.Context, key int64) error {
	_, err := q.db.ExecContext(ctx, advisoryLock, key)
	return err
}
```

**Comment by joe-getcouragenow** [comment]
cool.

SO then it shoudl be ok with cockroachdb in theory..
