### ISSUE TITLE
Warn on misformatted annotations (example: --name instead of -- name)

### ISSUE THREAD

**Issue by brunoluiz** [kyleconroy/sqlc#591]
Many times, I forget the space on `-- name: XYZ :exec` for example. It would be interesting if there was warning in case there is something that is close to the annotation, but not quite. The `-- name` is the one that I usually get, but I think that might be more cases around the annotation format.

**Comment by carpenter-ryan** [comment]
I just ran into this and agree this change would be very useful. It's confusing for beginners to understand why code isn't being generated and there are no associated errors or warnings.

**Comment by kyleconroy** [comment]
Fixed in https://github.com/kyleconroy/sqlc/pull/859
