### ISSUE TITLE
SQL syntax error from postgres PRIMARY KEY (...) INCLUDE (...)

### ISSUE THREAD

**Issue by tv42** [kyleconroy/sqlc#592]
```
CREATE TABLE foo (
	PRIMARY KEY (a, b) INCLUDE (c),
	a integer,
	b integer,
	c integer
)
```

```
foo.sql:1:1: syntax error at or near "INCLUDE"
```

> The optional `INCLUDE` clause allows a list of columns to be specified which will be included in the non-key portion of the index.

https://www.postgresql.org/docs/current/sql-createtable.html

It seems like sqlc could safely ignore anything inside those `INCLUDE` parens.

**Comment by kyleconroy** [comment]
sqlc relies on https://github.com/lfittl/pg_query_go, which currently uses the PostgreSQL 10 parser. The PRIMARY KEY (...) INCLUDE (...) syntax was introduced in PostgreSQL 11. I've opened up an issue to get pg_query_go updated for PostgreSQL 11: lfittl/pg_query_go#26

Sadly, it looks like pg_query_go is unmaintained at this point, so this sadly won't be fixed soon.
