### ISSUE TITLE
Change variable name

### ISSUE THREAD

**Issue by tcastelly** [kyleconroy/sqlc#600]
Hello,

I look throw examples I did not found.

I have a query like this:
```sql
SELECT $2::smallint - ROUND(AVG((fr.json_row->>'builtYear')::numeric), 2) as avg
```

As generated parameter I have:
```golang
type MyArguments struct {
  ...
  Column2 int16
  ...
}
```

Is it possible to force to change the name?

Thank you for your help.

**Comment by DanielAtwood** [comment]
Does this help? [Renaming struct fields](https://github.com/kyleconroy/sqlc#renaming-struct-fields)

> ### Renaming Struct Fields
> Struct field names are generated from column names using a simple algorithm: split the column name on underscores and capitalize the first letter of each part.
> ```
> account     -> Account
> spotify_url -> SpotifyUrl
> app_id      -> AppID
> ```
>If you're not happy with a field's generated name, use the `rename` dictionary to pick a new name. The keys are column names and the values are the struct field name to use.
>```yaml
>version: "1"
>packages: [...]
>rename:
>  spotify_url: "SpotifyURL"
>```

**Comment by tcastelly** [comment]
Yes, but but for sqlc the column name is "column_2". So I have to configure like this:
```json
  "rename": {
    "column_2": "Date"
  }
```

I'm a bit afraid to have side effect because of this.

**Comment by DanielAtwood** [comment]
Ah I see you want `as avg` to give:
```go
type MyArguments struct {
    Avg int16
}
```
Maybe try looking at this? [Named parameters](https://github.com/kyleconroy/sqlc/blob/master/docs/named_parameters.md).

**Comment by tcastelly** [comment]
Thank you very much! I'm sorry I should have looked better the doc.
