### ISSUE TITLE
SELECT foo.id AS foo_id loses Go type information

### ISSUE THREAD

**Issue by tv42** [kyleconroy/sqlc#606]
I'm trying to use custom Go types for some SQL columns, mapping a sql `int64` to Go `type FooID uint64`.

It seems I can have

`SELECT foo.id FROM ...` and get generated `type FooRow struct { ID FooID }`

or I can have

`SELECT foo.id AS foo_id FROM ...` and get `type FooRow struct { FooID int64 }`

but I cannot get both at the same time. Using the `AS` forgets the association with the Go type, but without the `AS` my struct fields are kinda misleading. Consider `SELECT foo.id, bar.id FROM ...`, can't have two things fighting for the struct field name `ID`.

**Comment by kyleconroy** [comment]
@tv42 Can you provide a complete example for this issue? Since this involves type overrides, can you include a sqlc configuration file, database schema, and example queries.

**Comment by tv42** [comment]
Can you please re-open this? It's still there, as the previous comment shows.

**Comment by kyleconroy** [comment]
@tv42 whoops, sorry about that. Thanks for writing up the full example.

**Comment by not-rusty** [comment]
I've personally tested this one with sqlc v1.13.0 and with [type overrides](https://docs.sqlc.dev/en/stable/reference/config.html#per-column-type-overrides) this can be easily worked around. Could that solve it @tv42 ?

**Comment by tv42** [comment]
> I've personally tested this one with sqlc v1.13.0 and with [type overrides](https://docs.sqlc.dev/en/stable/reference/config.html#per-column-type-overrides) this can be easily worked around. Could that solve it @tv42 ?

Sorry that's too vague to say much.  The reproducing example already uses type overrides to switch from an `int64` to `UserID`, do you think it is somehow wrong?

```
    overrides:
      - column: users.id
        go_type: example.com/sqlc_issues606_reproducer.UserID
```

**Comment by WesleyMiller1998** [comment]
I've also run into this issue. Here is my repro: https://gist.github.com/WesleyMiller1998/7730c3ab8b3183c432075728a4e463bf

It appears that a column override messes with the type generation. I may dig into the issue later and open a PR
