### ISSUE TITLE
MySQL: Handling views

### ISSUE THREAD

**Issue by alecbz** [kyleconroy/sqlc#609]
We create views in some of our migration files, which seems to result in `ddl.TableSpec` being `nil` when processing the file, and thus triggers:

https://github.com/kyleconroy/sqlc/blob/3875006b627183162a8d8bc3e27a1ace5acbad60/internal/mysql/schema.go#L62-L64

is there a way for vitess' sql parser to detect when a table is actually a view, and at the very least just skip generating models for it? Are there other situations in which `ddl.TableSpec` is `nil`?

**Comment by kyleconroy** [comment]
The vitess-based parser is deprecated (#633), so sadly nothing will change on that front. I've added the mysql tag to #193, which encompasses the issue.

**Comment by alecbz** [comment]
Does the dolphin parser at least no-op when it encounters a view? vitess was crashing IIRC.
