### ISSUE TITLE
Query linter...

### ISSUE THREAD

**Issue by kevinburkemeter** [kyleconroy/sqlc#618]
So I created a bunch of tables with `timestamp without time zone`, I think because I figured everything was going to be UTC so I didn't really need to save the timezone information.

However, if you combine that with `now()` in a query and a non-UTC client, you can get results you're not expecting.

I'm wondering if there's a way to enforce use of `now() at time zone 'utc'` in query, or make it an error to do a plain `now()` query.

**Comment by kyleconroy** [comment]
> I'm wondering if there's a way to enforce use of now() at time zone 'utc' in query, or make it an error to do a plain now() query.

There currently isn't a way to enforce this. I'd love to add query linters, but am currently focused on MySQL support and type-checking. Have you looked at https://semgrep.live/? It may be able to do what you need.

**Comment by maxhawkins** [comment]
https://github.com/kristiandupont/schemalint

This project might be of interest.
