### ISSUE TITLE
Deprecate the mysql package in favor of engine/dolphin

### ISSUE THREAD

**Issue by kyleconroy** [kyleconroy/sqlc#633]
The current MySQL support is implemented as a totally separate package. The support in that package is incomplete; many queries that work in PostgreSQL fail for MySQL. When improvements are made to the compiler, code generation, or type-checking, the mysql package doesn't benefit. The replacement package, engine/dolphin, is coming along nicely. It's implemented using the same code as the PostgreSQL and (experimental) SQLite support. 

The roadmap will be as follows:

- v1.5.0
  - mysql: no changes
  - engine/dolphin: available via the `mysql:beta` engine
- v1.6.0
  - mysql: deprecated, available via the `mysql:deprecated` engine
  - engine/dolphin: default when using the `mysql` engine
- v1.7.0
  - mysql: removed

**Comment by DanielAtwood** [comment]
Do you have any idea when v1.5.0 will be ready?

**Comment by kyleconroy** [comment]
I had hoped to release it this week, but I think I need another week to get the engine/dolphin package ready for general use
