### ISSUE TITLE
WithTx implementation

### ISSUE THREAD

**Issue by deelienardy** [kyleconroy/sqlc#644]
Hi, first of all I think this is a great project in Go. So I try to use for my project, but I have a question.
On generated code below, `db` is override by `tx`
Is this on purpose, if yes, why ?
Isn't this make `Queries` can't return to using normal `db` ?
```
func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:         tx,
		tx:         tx,
		insertStmt: q.insertStmt,
	}
}
```

How I implement `sqlc` is like this (using prepared statement)
```
type XStorage struct {
	q *Queries
}
```
if I triggered transaction, after that I can't return to normal DB since it is overwritten by `tx`.

Or my implementation is wrong ?
Should I always creating `Queries` before doing something to DB ?
But wasn't it kill prepared statement initialization (first time at the app running) ?

Note: maybe need a little complex IRL implementation on docs ?

**Comment by kyleconroy** [comment]
> Is this on purpose, if yes, why ?

Overriding db with the the transaction is on purpose. Notice that the unexported db field on *Queries is a DBTX interface, both *sql.DB and *sql.Tx fulfill that interface.

> But wasn't it kill prepared statement initialization (first time at the app running) ?

If you're using prepared statements, you'll want to call `Prepare` once when your app boots up. You then need to call `WithTx` if you're going to do queries in a transaction. Prepared statements must be re-initialized when using a transaction. The return value from `WithTx` should not outlive its transaction. Once the transaction is committed or roll-backed, the value should be garbage collected.

**Comment by deelienardy** [comment]
I see.. I need make another query which short-lived for transaction, before this I think I just need use same query for everything.
For the information, I will close this issue

**Comment by Hades32** [comment]
@kyleconroy if the overriding is on purpose, could you explain why we even need `WithTx`? It looks to me like `query.New(db).WithTx(tx)` is exactly the same as calling `query.New(tx)`...
