### ISSUE TITLE
how to make a dynamic search

### ISSUE THREAD

**Issue by codingnan** [kyleconroy/sqlc#645]
hi.
I have a table which have 10 fields.
I want to use field A to search.
also I want to use field B.
also field A and field B.
and so on.
how to do this?

**Comment by kyleconroy** [comment]
Dynamic search queries are currently difficult to write with sqlc. A few approaches to take are listed in #364, each with their own trade offs. As I said in the last comment on that issue:

> While I think this could work, it's a significant amount of work. Right now I'm focusing my time working on better type checking and inference, and adding SQLite and MySQL support. I don't see this being a priority any time soon. Sorry.

If you need many dynamic queries at runtime, sqlc in its current form may not be the right fit.

**Comment by codingnan** [comment]
this is very important on admin platform. 
there are many table pages on admin platform.
each table page have many filters to search table, witch means it needs dynamic search.
so important.
