### ISSUE TITLE
Mysql: FROM_UNIXTIME()

### ISSUE THREAD

**Issue by markschmid** [kyleconroy/sqlc#655]
The following should be supported:

Schema:
```
create table `test` (
  `ts` datetime
);
```

Query:
```
insert into test (
  ts
) values (
  from_unixtime(?)
);
```

Output new parser:
```2020/08/06 14:23:32 unknown MySQL type: any```

**Comment by kyleconroy** [comment]
While we can add one-off function definitions, the plan is to solve this via https://github.com/kyleconroy/sqlc/issues/657. I have working code (from #550) that generates function definitions for PostgreSQL.

**Comment by kyleconroy** [comment]
Closed in favor of https://github.com/kyleconroy/sqlc/issues/657
