### ISSUE TITLE
Generate list of functions supported by a vanilla MySQL instance

### ISSUE THREAD

**Issue by kyleconroy** [kyleconroy/sqlc#657]
I laid the ground work for this in #550, but it needs significant work. For PostgreSQL, we need to do the following:

* Refactor portions of `sqlc-pg-gen` into a separate package
* Currently only function definitions are extracted. We need to include table and type information

MySQL is a bigger question mark because I don't know how to pull out the necessary information. The first step will be to explore what queries are necessary to get the needed data.

**Comment by eberkund** [comment]
Hey, I am just browsing to see if there is anything within my capabilities and commitment level that I could contribute.

My understanding is that the purpose of importing from a running instance is to basically map all the functions/types to Go types? Then using that mapping information the compiler can substitute for the Go types whenever it sees the functions/types used in SQL? Is this correct?

Awesome project by the way! I have only used it for a hello world project so far, but the paradigm looks refreshingly simple to work in. 👍

**Comment by kyleconroy** [comment]
Replaces https://github.com/kyleconroy/sqlc/issues/630 https://github.com/kyleconroy/sqlc/issues/725 https://github.com/kyleconroy/sqlc/issues/655

**Comment by kyleconroy** [comment]
This is sadly going to be more difficult than I thought. The information schema tables in MySQL do not contain built-in functions and procedures. This means we're going to have to construct that list manually, or via some type of scraping / codegen.
