### ISSUE TITLE
Add support for AUTO_INCREMENT when generating schema for Mysql 

### ISSUE THREAD

**Issue by nitrajka** [kyleconroy/sqlc#660]
In my schema:
```
CREATE TABLE users (
    id INTEGER PRIMARY KEY NOT NULL AUTO_INCREMENT,
...
)
```
I get the following output with command `sqlc generate`:
```
# package mysql
schema.sql:1:1: syntax error at or near "AUTO_INCREMENT"
```

I hope this issue is useful.

**Comment by kyleconroy** [comment]
The `mysql:beta` engine handles this case correctly. Please switch your the `engine` value in your sqlc configuration file to `mysql:beta`. This new engine will be the default MySQL engine in the next release.
