### ISSUE TITLE
mysql tinyint compiles to bool

### ISSUE THREAD

**Issue by xcaptain** [kyleconroy/sqlc#666]
![图片](https://user-images.githubusercontent.com/4054836/90726196-e7ac9900-e2f3-11ea-88e2-f8594949a9ac.png)

As the image shows, I added a `kind` field to the `authors` table, then run `sqlc generate`, in the model, the `kind` field's type becomes `bool`, the expected type should be `int8`

**Comment by markschmid** [comment]
In my understanding, tinyint is a 1byte int whereas int8 is an 8byte datatype. tinyint can hold more than just 2 values, in that regard you are right. I'm using it only for booleans though, so I'm OK in that conversion from MySQL tinyint to Golang bool.

**Comment by markschmid** [comment]
Sorry, complete rubbish from my side (byte/bit). Please disregard :)

**Comment by xcaptain** [comment]
https://github.com/kyleconroy/sqlc/blob/21a6cda2667d18cee40b6847a8558d2961f5d771/internal/mysql/gen.go#L297-L301

May have found the cause, but don't know why convert tinyint to bool

**Comment by kyleconroy** [comment]
This is indeed a bug. I need to do some investigation work around how the MySQL driver handles boolean types.

**Comment by markschmid** [comment]
I've looked into how 1.6.0 handles this. Is it correct that 1.6.0 does not support mysql boolean types?
Intuitively, I'd have expected the following mysql column definitions to be translated to golang data type ```bool```, yet all of them are translated to ```int32```: ```BOOL```, ```BOOLEAN```, ```TINYINT(1)```
