### ISSUE TITLE
Impossible to Insert with a select *

### ISSUE THREAD

**Issue by tcastelly** [kyleconroy/sqlc#670]
Hello,

I'm trying to add multiple rows with arrays as parameters.
I have a query like this:

```sq
INSERT INTO pages_users (user_id, page_id)
SELECT *
FROM UNNEST(sqlc.arg(user_ids)::bigint[], sqlc.arg(page_ids)::VARCHAR(55)[]);
```

This is my error message:
```package postgres
postgres/queries/pages.sql:18:1: empty edit contents
```

But the query seems to be valid, I can execute it on postgres.

Thank you for your help.

**Comment by kyleconroy** [comment]
I get a `unnest(unknown, unknown)` errors instead of `empty edit contents`. https://play.sqlc.dev/p/c080a282d7106d70420c022c7021bece49956ac67c7075c232bc4b14aa0623a1
