### ISSUE TITLE
Unknown PostgreSQL type: timestamp with time zone on version 2 with `max(1)` in select clause

### ISSUE THREAD

**Issue by jschaf** [kyleconroy/sqlc#705]
**sqlc.json**
```json
{
  "version": "2",
  "sql": [
    {
      "engine": "postgresql",
      "schema": [
        "./schema.sql"
      ],
      "queries": [
        "./sqlc_queries.sql"
      ],
      "gen": {
        "go": {
          "package": "sqlc",
          "out": "sqlc"
        }
      }
    }
  ]
}
```

**schema**
```sql
CREATE TABLE foo (
  start_time     int NOT NULL
);
```

**query**
```sql
SELECT start_time, max(1)
FROM foo
GROUP BY start_time;
```

Running `sqlc generate` errors with:

```sh
$ docker run --rm -v /my/code:/src -w /src kjconroy/sqlc generate

2020/09/03 23:21:39 unknown PostgreSQL type: timestamp with time zone
```

What's strange if I remove the `max(1)` column from the query, sqlc works. Also, if I replace `max` with `avg` sqlc succeeds.

**Comment by jskelcy** [comment]
I am also seeing this on version 1.

**Comment by jschaf** [comment]
> It is worth noting however that unlike @jschaf I am using timestamp with time zone, where it appears OP is not.

I was also using timestamp with timezone originally. I reduced the query to not use timezone and observed the same error.

**Comment by kyleconroy** [comment]
@jschaf I can no longer reproduce this using v1.9.0 of sqlc. See [this playground](https://play.sqlc.dev/p/2f319d24ed47394f0add7a08436ffe6d5f4ecfcaf466b87c879da4582cc0750e). The `interface{}` return value isn't great, but it no longer returns a strange error.
