### ISSUE TITLE
sql joins to map to individual table  

### ISSUE THREAD

**Issue by SabariVig** [kyleconroy/sqlc#715]
can we get joins to return struct as with table fields
```
create table users(id int primary key, name varchar);
create table posts(id int primary key, title varchar, user_id int references users(id ));
```

```
--- name: GetPostByUserID :many
select * from posts 
join users 
on user.id = posts.user_id where user.id = $1;
```
```
user,post,err := GetPostByUserID(ctx,1);
```

**Comment by kyleconroy** [comment]
@SabariVig thanks for the question. There's a long discussion here (https://github.com/kyleconroy/sqlc/discussions/363) about how this feature would work. The TL;DR is that we want to do it, but aren't sure exactly how we want the feature to work.

I'm going to close this in favor of using that discussion to track implementation.
