### ISSUE TITLE
PostgreSQL type "cidr" should be mapped to net.IPNet

### ISSUE THREAD

**Issue by encendre** [kyleconroy/sqlc#719]
At the present time it seems that the cidr type is mapped top net.IP.
According to this link https://www.postgresql.org/docs/9.1/datatype-net-types.html the type "cidr" is very indicated for the network, moreover in go we have the type net.IPNet which corresponds exactly to that.

**Comment by kevinburkemeter** [comment]
I tried adding

```
  - go_type: "net.IPNet"
    db_type: "cidr"
```

but sqlc complains:

```
error parsing sqlc.json: Package override `go_type` specifier "net.IPNet" is not the proper format, expected 'package.type', e.g. 'github.com/segmentio/ksuid.KSUID'
make: *** [Makefile:86: src/internal/db/models.go] Error 1
```

**Comment by kevinburkemeter** [comment]
You'd need to change that logic and probably also add a custom Scan() function.
