### ISSUE TITLE
Feature Request: SQL Query result as map, rather than slice/array

### ISSUE THREAD

**Issue by StevenACoffman** [kyleconroy/sqlc#728]
We have queries that returns a large number of rows, which we immediately convert into a map, keyed by one of the returned row's fields.

For both convenience and performance reasons would like the return type of these `:many` query to be a keyed map instead of a slice/array. Is there anyway to hint sqlc to emit a slightly different generated boilerplate to achieve this? Possibly something like having our SQL query `:map` hint that would cause generated results to be returned as as a Go map (keyed by first field) instead of slice.

As a workaround, we can alter our PostgreSQL queries to select into constructed hstore values like this:
```
create table dir (myID text, value_string text);
insert into dir values
('MY_ID', 1),
('ACC', 2);

select hstore(array_agg(MY_ID), array_agg(value_string))
from dir;

         hstore          
-------------------------
 "ACC"=>"2", "MY_ID"=>"1"
(1 row)
```

**Comment by kyleconroy** [comment]
@StevenACoffman thanks for the feature request! I have less time right now to focus on sqlc, so I'm only going to be working on the highest priority issues, which is currently MySQL support. I hope to eventually have a plugin system so that you could write `:map` yourself, but for now I'm going to close this one out.

**Comment by StevenACoffman** [comment]
Entirely understandable. Would you be open to a pull request at this point?

**Comment by ChielTimmermans** [comment]
@kyleconroy is there any possibily for me or @StevenACoffman to write a PR to add this as an enhancement?

**Comment by juanmartin8a** [comment]
#2353
