### ISSUE TITLE
MySql syntax error at or near not

### ISSUE THREAD

**Issue by kristijorgji** [kyleconroy/sqlc#734]
I have the following schema

```
create table categories
(
    id smallint unsigned not null
        primary key,
    name json not null,
    created_at timestamp default CURRENT_TIMESTAMP not null,
    updated_at timestamp default CURRENT_TIMESTAMP not null on update CURRENT_TIMESTAMP
);
```

And when run scql generate get the following error

db/migrations/000001_init_schema.up.sql:8:56: syntax error at or near "not"

I can fix this by removing "not null", but that is not a proper solution
This works without not null

```
create table categories
(
    id smallint unsigned
        primary key,
    name json l,
    created_at timestamp default CURRENT_TIMESTAMP ,
    updated_at timestamp default CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP
);
```

**Comment by kyleconroy** [comment]
Similar to #731, this has been fixed on the main branch. A new release is waiting on #654, which is blocked on a few upstream changes to the MySQL parser.
