### ISSUE TITLE
MySQL support for json field type is missing

### ISSUE THREAD

**Issue by kristijorgji** [kyleconroy/sqlc#735]
having a schema like 

```
create table categories
(
    id smallint unsigned not null
        primary key,
    name json not null,
    created_at timestamp default CURRENT_TIMESTAMP not null,
    updated_at timestamp default CURRENT_TIMESTAMP not null on update CURRENT_TIMESTAMP
);

```

Where the name is type json, will fail with sqlrc generate due to unsupported type json

**Comment by kyleconroy** [comment]
This has been fixed on main as well. You can use a [tip release](https://github.com/kyleconroy/sqlc#tip-releases) until the next version is released. If you do, you'll need to change the engine back to `mysql`.

**Comment by kristijorgji** [comment]
I am not sure if this is fixed for engine "mysq"

I cloned the repository, build it locally with alias sqlc-dev and tried it still get that message "json unkown mysql type"
