### ISSUE TITLE
Add support for `pq` and `sqlx`

### ISSUE THREAD

**Issue by djui** [kyleconroy/sqlc#74]
I tbelieve pq and sqlx are very commonly used. Allowing to choose the dialect/library is a great addition and can keep the implementation flexible/doesn’t contradict its generated code use.

**Comment by kyleconroy** [comment]
In your mind, what does support for this two libraries look like? The code sqlc generates already uses lib//pq for arrays and null timestamps. The `dbtx` interface type that is generated works with any driver that supports the database/sql interface.

**Comment by djui** [comment]
Ah, ok. That's was a misunderstanding/misread from my side then.
