### ISSUE TITLE
Provide an Alpine image

### ISSUE THREAD

**Issue by bquenin** [kyleconroy/sqlc#753]
It would be great to publish an image based on Alpine in addition to the existing image.

You would only need to duplicate your existing `Dockerfile` and replace the `FROM` as follows `FROM golang:alpine AS builder`

If we have this Alpine image, it would be then very easy to include `sqlc` as part of a containerized build process such as:

```
# sqlc
# ---
FROM kyleconroy/sqlc:alpine AS sqlc

# ---
FROM golang:1.15.3-alpine3.12 AS builder
RUN apk --no-cache add make git curl
WORKDIR /build
COPY . .

COPY --from=sqlc /bin/sqlc /bin/sqlc
RUN make build

...
```

**Comment by kyleconroy** [comment]
@bquenin I haven't gotten any other requests for this, so I'm going to go ahead and close this out. I did add multi-arch Docker builds about a month ago.

**Comment by roccoblues** [comment]
I don't think it's currently possible to provide an alpine image. Version 1.15 added a dependency on [wasmtime-go](https://github.com/bytecodealliance/wasmtime-go) which currently [doesn't build](https://github.com/bytecodealliance/wasmtime-go/issues/21) on alpine.

**Comment by kyleconroy** [comment]
We recently added a `nowasm` build tag, so it should be easy enough to use that when building an Alpine image.

**Comment by tspearconquest** [comment]
Hi, is there some way to download the nowasm build using `go install` ?

It's not a problem if not, but we're interested in using that build if it's available, rather than forking this repo to build it ourselves.

**Comment by roccoblues** [comment]
`go install` supports the same `-tags` argument as `go build`. So something like
```
go install -tags=nowasm github.com/kyleconroy/sqlc/cmd/sqlc@latest
```
should work.

**Comment by tspearconquest** [comment]
Thanks!
