### ISSUE TITLE
Enum number naming issue

### ISSUE THREAD

**Issue by blaggacao** [kyleconroy/sqlc#754]
https://play.sqlc.dev/p/146351193180643c810cb10c22a22ff1ef3dc9d0deb8e3cb89c237aea60ee46c
```mysql
/* MYSQL */
CREATE TABLE users (
  enable   ENUM('0','1')
);
```

There are two issues:

- This identifier is not valid go code
- The identifier is not namespaced so will conflict very easily within a shared namespace

```golang
const (
	0 EnableType = "0"
	1 EnableType = "1"
)
```

**Comment by kyleconroy** [comment]
This has been fixed in v1.6.0

https://play.sqlc.dev/p/2430de11a75f1c486f9ec88cc2a29d2039fee1814326cfbdf602caed7acd5580
