### ISSUE TITLE
The use of the "IN" keyword, A.K.A. filtering a column using multiple values

### ISSUE THREAD

**Issue by euller88** [kyleconroy/sqlc#77]
Does this package can generate code that supports the "IN" operator? 

Like in this example, in which this definition:
```sql
-- name: ListAuthorsByIDs :many
SELECT * FROM authors
WHERE id IN (/*mysterious syntax*/);
```
Would generate this code:
```go
func (q *Queries) ListAuthorsByIDs(ctx context.Context, ids ...int64) ([]Author, error) {
	rows, err := q.db.QueryContext(ctx, listAuthors, ...ids)
	 if err != nil {
		return nil, err
	}
	// rest of the function
}
```

**Comment by kyleconroy** [comment]
sqlc has full support for the `IN` operator. For example:

```sql
-- name: ListAuthorsByIDs :many
SELECT * FROM authors
WHERE id IN ($1);
```

will generate the following Go:

```go
func (q *Queries) ListAuthorsByIDs(ctx context.Context, id int64) ([]Author, error) {
	rows, err := q.db.QueryContext(ctx, listAuthors, ...ids)
	 if err != nil {
		return nil, err
	}
	// rest of the function
}
```

However, you want a query that takes in any number of IDs. The `IN` operator takes a set list of items, so won't do what you want. 

The good news is that you can get the behavior you want using arrays and the `ANY` operator. Here's the "mysterious" syntax you need:

```sql
SELECT * FROM authors
WHERE id = ANY($1::bigserial[]);
```

Which will generate

```
func (q *Queries) ListAuthorsByIDs(ctx context.Context, ids []int64) ([]Author, error) {
	rows, err := q.db.QueryContext(ctx, listAuthors, pq.Array(ids))
	 if err != nil {
		return nil, err
	}
	// rest of the function
}
```

sqlc doesn't include support for generate code with variadic functions. It shouldn't be too hard to put the IDs you want to search for into a slice.

**Comment by euller88** [comment]
Nice, thanks for the answer, I wasn't sure that this was possible with sqlc. Do you mind if I make a PR with an example later in the week? I'm sure it will help some people that have the same doubts.

**Comment by kyleconroy** [comment]
I'd gladly accept that PR. Go ahead and create a new markdown file in the `examples` directory.

**Comment by k1nkc** [comment]
@kyleconroy ,
Sorry If I am commenting too late but in sqlc v1.15.0, query:
`DELETE FROM post_medias
WHERE id IN ($1);`

generates:
`func (q *Queries) PostMediaDeleteMany(ctx context.Context, id string) error {
	_, err := q.exec(ctx, q.postMediaDeleteManyStmt, PostMediaDeleteMany, id)
	return err
}`

where id is string instead of slice.

Can you please help me how to update query to accept slice.

**Comment by masb0ymas** [comment]
> sqlc has full support for the `IN` operator. For example:
> 
> ```sql
> -- name: ListAuthorsByIDs :many
> SELECT * FROM authors
> WHERE id IN ($1);
> ```
> 
> will generate the following Go:
> 
> ```go
> func (q *Queries) ListAuthorsByIDs(ctx context.Context, id int64) ([]Author, error) {
> 	rows, err := q.db.QueryContext(ctx, listAuthors, ...ids)
> 	 if err != nil {
> 		return nil, err
> 	}
> 	// rest of the function
> }
> ```
> 
> However, you want a query that takes in any number of IDs. The `IN` operator takes a set list of items, so won't do what you want.
> 
> The good news is that you can get the behavior you want using arrays and the `ANY` operator. Here's the "mysterious" syntax you need:
> 
> ```sql
> SELECT * FROM authors
> WHERE id = ANY($1::bigserial[]);
> ```
> 
> Which will generate
> 
> ```go
> func (q *Queries) ListAuthorsByIDs(ctx context.Context, ids []int64) ([]Author, error) {
> 	rows, err := q.db.QueryContext(ctx, listAuthors, pq.Array(ids))
> 	 if err != nil {
> 		return nil, err
> 	}
> 	// rest of the function
> }
> ```
> 
> sqlc doesn't include support for generate code with variadic functions. It shouldn't be too hard to put the IDs you want to search for into a slice.

For uuid query like this ?
```sql
SELECT * FROM authors
WHERE id = ANY($1::uuid[]);
```
