### ISSUE TITLE
Support for multiple statements per instruction

### ISSUE THREAD

**Issue by philippta** [kyleconroy/sqlc#770]
When working with mysql, it is not possible to query back the values of the inserted row like it's possible with postgres' `RETURNING (...)`instruction.

So the go-to way, to do this at the moment would be to first have an `:execresult` action and then a seperate `:one` for querying by result.LastInsertd().

It would be great, to have a feature which allowes multiple SQL queries per action, e.g.
```sql
/* name: CreateUser :one */
INSERT INTO users (email, password) VALUES (?,?);
SELECT * FROM users WHERE id = LAST_INSERT_ID();
```

I think this also opens up the opportunity to handle complex data insertions, which mutate multiple database tables in one transaction with a single function call.

**Comment by kyleconroy** [comment]
@philippta Thanks for the feature request. 

I won't be added support for multiple SQL queries per command. Instead, you can use a transaction with two queries to get the same result.

```sql
/* name: CreateUser :exec */
INSERT INTO users (email, password) VALUES (?,?);

/* name: SelectUser :one */
SELECT * FROM users WHERE id = LAST_INSERT_ID();
```

You'd use the [generated code](https://play.sqlc.dev/p/e48bab46d3a658b3afc3ffdcbe39e51e58fc6067329e9d554e6645f96b954346) like so:

```go
package main

import (
    "context"
    "database/sql"
)

func (ctx context.Context, tx sql.Tx) error {

    q := New(tx)

    err := q.CreateUser(ctx, CreateAuthorParams{"user@example.com", "secret"})
    if err != nil {
        return err
    }

    user, err := q.SelectUser(ctx)
    return err
}
```

**Comment by bbkane** [comment]
Could you please add this example to https://github.com/kyleconroy/sqlc/blob/master/docs/transactions.md ? It's much clearer to me than the example there. If you'd prefer, I'd also be happy to make a PR with this doc addition.
