### ISSUE TITLE
UNION query not working

### ISSUE THREAD

**Issue by oscartbeaumont** [kyleconroy/sqlc#778]
I am trying to use the SQL `UNION` operator with SQLC and am having some issues. Below is an example query from my `queries.sql` file.
```
-- name: QueryMe :many
SELECT 1 AS one UNION SELECT 2 AS two;
```

When I run `sqlc generate` I get the following output.
```bash
# package db
error generating code: template: table:255:79: executing "queryCode" at <.Ret.Type>: error calling Type: no type for QueryValue:
```

Thanks for any help that can be provided and the awesome project!

**Comment by kyleconroy** [comment]
Closing in favor of https://github.com/kyleconroy/sqlc/issues/568
