### ISSUE TITLE
Not recognizing some types

### ISSUE THREAD

**Issue by euller88** [kyleconroy/sqlc#80]
The tool is unable to properly generate some structs, with the columns of the tables have the following types:

- character of any size, should map to string or array of rune (string is my favorite option);
- real, should map to float32;
- double precision, should map to float64
- numeric and decimal are tricky, so I don't think they should be mapped to any kind of float.

I will try to send a PR this weekend. In the meantime, I will investigate some other types that may be missed by the tool.

**Comment by kyleconroy** [comment]
I think you're right. For internal support, we'll need to use an external package, similar to how you we use `lib/pq` for array support.
