### ISSUE TITLE
Question: getting sqlc to generate sql.NullTime vs time.Time

### ISSUE THREAD

**Issue by jskelcy** [kyleconroy/sqlc#801]
Hello,

I am writing some sqlc queries and I would like to have a timestamp query option be nullable. I am looking around the code the and it would appear that sometimes the generated `Params` types use `sql.NullTime` and sometimes use `time.Time`. As it stands in this query where I want the value to be nullable, it is not. Here is the portion of the query in question:
```
    AND (sqlc.arg(interval_timestamp)::timestamp IS NULL OR interval_timestamp = sqlc.arg(interval_timestamp)::timestamp);
```
this generates:
```
type NameOfFunctionParams struct {
        ...Otherwise unimporant stuff
	IntervalTimestamp      time.Time
}
```
This is an issue because this value will never be `NULL` as the zero type of `time.Time` is the unix epoch and the optional filter that I showed above does not work. I am wondering if there is something I can do to my query to nudge sqlc to generate the desired type?

**Comment by kevinburkemeter** [comment]
I think it has to do with whether the underlying column is nullable - if so sqlc should generate nulltime, if not maybe not, though maybe I'm not remembering correctly.

**Comment by jskelcy** [comment]
To be fair given go's zero value behavior this also works as, assuming that my timestamps never start and the unix epoch:
```
AND (sqlc.arg(interval_timestamp)::timestamp = 'epoch' OR interval_timestamp = sqlc.arg(interval_timestamp)::timestamp);
```

**Comment by jskelcy** [comment]
@kevinburkemeter yeah taking a look at the schema and it seems like that is the ticket. Well, it would be nifty if it could look at the query and figure out if I am doing this check, as this is the kind of the best way to do optional filtering given that sqlc is not really a query build (and that's kind of a good thing!), but not the end of the world.

I'm going to close this out for now as this ticket was not supposed to be a feature request. But Ill open another one for a more focused discussion on the feature.
