### ISSUE TITLE
mysql code generation not working with column names that contain capitalized letters

### ISSUE THREAD

**Issue by kmhagan** [kyleconroy/sqlc#815]
Hello!

It appears that mysql code generation does not support column names with capitalizations.

If I take one of the given examples and replace `id` with `authorId`

`example/authors/mysql/schema.sql`:
```
CREATE TABLE authors (
          authorId   BIGINT PRIMARY KEY AUTO_INCREMENT,
          name text      NOT NULL,
          bio  text
);
```

`example/authors/mysql/queries.sql`:
```
/* name: GetAuthor :one */
SELECT * FROM authors
WHERE authorId = ? LIMIT 1;

/* name: ListAuthors :many */
SELECT * FROM authors
ORDER BY name;

/* name: CreateAuthor :execresult */
INSERT INTO authors (
  name, bio
) VALUES (
  ?, ? 
);

/* name: DeleteAuthor :exec */
DELETE FROM authors
WHERE authorId = ?;
```

The following error is returned:
```
# package authors
mysql/query.sql:1:1: column "authorId" does not exist
mysql/query.sql:16:1: column "authorId" does not exist
```

**Comment by kyleconroy** [comment]
For column names with capital letters, you need to quote the column name in queries. 

```
-- name: GetAuthor :one
SELECT * FROM authors
WHERE "authorId" = ? LIMIT 1;
```

[See example on play.sqlc.dev](https://play.sqlc.dev/p/dde3a893c70e0ce3a8b3b50da079b4dbe2feb4f6a99e268ab2050ead82ae6fea)

**Comment by kmhagan** [comment]
Cool website and thanks for the example!

I don't seem to be able to get it to work for a slightly more advance scenario where the capitalization is in the `INSERT` or `SET` portion of a query (tried with and without quotes)

```
-- Example queries for sqlc
CREATE TABLE authors (
   authorId   BIGINT PRIMARY KEY AUTO_INCREMENT,
   firstName text      NOT NULL,
   bio  text
);

/* name: CreateAuthor :execresult */
INSERT INTO authors (
  "firstName", bio
) VALUES (
  ?, ? 
);
```
[Example](https://play.sqlc.dev/p/3f9de991fc9fb6a6570d32ba4e6abd620e2656eb76c32eb230b67ee977610c75)

**Comment by kyleconroy** [comment]
Sorry, my initial suggestion was incorrect. MySQL uses backticks, not double quotes, for quoting an identifier.

https://play.sqlc.dev/p/b9b6147da509dfe0403c066e4893dc0eb5aacd3dc78d617405560b1172fbef23

Not sure why that doesn't work.

**Comment by kyleconroy** [comment]
It appears that columns names aren't case sensitive in MySQL. https://stackoverflow.com/questions/2009005/are-column-and-table-name-case-sensitive-in-mysql

**Comment by kmhagan** [comment]
Oh interesting I wasn't aware of that, in that case I'll switch to all lowercase in the definitions.

Thanks for the help/clarification

**Comment by kyleconroy** [comment]
> Oh interesting I wasn't aware of that, in that case I'll switch to all lowercase in the definitions.

That's the easiest workaround, but sqlc should be able to handle your queries. I'll let you know when it's fixed.

**Comment by kmhagan** [comment]
Thanks!

Thought I should mention that while switching the queries to lowercase works (even with the schema definition containing capitalization), it leads to harder to read variable names. So hopefully the fix better honors the originally defined column naming capitalization defined in the table

Files created with table columns `author_id` and `first_name` variable naming come out nicely
```
type Author struct {
	AuthorID  int64
	FirstName string
	Bio       sql.NullString
}

type CreateAuthorParams struct {
	FirstName string
	Bio       sql.NullString
}

func (q *Queries) DeleteAuthor(ctx context.Context, authorID int64) error {
	_, err := q.db.ExecContext(ctx, deleteAuthor, authorID)
	return err
}
```

vs 

Files created with table columns `authorID` and `firstName`
```
type Author struct {
	Authorid  int64
	Firstname string
	Bio       sql.NullString
}

type CreateAuthorParams struct {
	Firstname string
	Bio       sql.NullString
}

func (q *Queries) DeleteAuthor(ctx context.Context, authorid int64) error {
	_, err := q.db.ExecContext(ctx, deleteAuthor, authorid)
	return err
}
```

**Comment by kyleconroy** [comment]
I'm now tracking this in https://github.com/kyleconroy/sqlc/issues/953
