### ISSUE TITLE
Adding bazel rules for sqlc

### ISSUE THREAD

**Issue by dmayle** [kyleconroy/sqlc#826]
This is mostly an informational issue about new bazel build rules for sqlc.  The pull request is at:
https://github.com/plezentek/bazel-sqlc/pull/1

That's for if you want to review the code at all.  I've requested code review from the bazel-discuss mailing list, and unless any issues come up, I'll be publishing the rules before the end of the week.

**Comment by kyleconroy** [comment]
Thank you very much! Is there anything else I need to do in the future to make sure the rules continue to work? I haven't used Bazel before in any real setting.

**Comment by dmayle** [comment]
@kyleconroy Normally, no.  I'll maintain them, they really only need to be updated if you add new features.  However, if you could take a look at #825 it would allow me to support Windows as well.

**Comment by kyleconroy** [comment]
Hoping to get #825 fixed this week. Not sure how that helps with Windows support though, the PostgreSQL parser doesn't compile on Windows

**Comment by dmayle** [comment]
@kyleconroy I didn't realize that sqlc itself had Windows limitations.  Bazel requires all tool binaries to start from a sandbox in a specified location.  In order to support sqlc, I had to build a helper program to launch sqlc from the directory where the config file is written, and it's written in bash (because using a compiled program to do this is possible, but much tougher to bootstrap).  This meant the rule could only work for linux and macos, not Windows.

In any case, thank you for fixing #825, I'll update the rule to remove the hack with the next sqlc release.
