### ISSUE TITLE
Can't generate join query, no error when run sqlc

### ISSUE THREAD

**Issue by tinoquang** [kyleconroy/sqlc#836]
Hi, so this is my schema:

create table comics (
    "id" serial UNIQUE,
    "page" VARCHAR(64) not null,
    "name" VARCHAR(128)not null,
    "url" VARCHAR(256) not null unique,
    "img_url" VARCHAR(128) not null,
    "cloud_img_url" VARCHAR(256) not null,
    "latest_chap" VARCHAR(128) not null,
    "chap_url" VARCHAR(128) not null,
    PRIMARY KEY (id, url, img_url)
);
create table users (
    "id" serial UNIQUE,
    "name" VARCHAR(64) not null,
    "psid" VARCHAR(64) not null UNIQUE,
    "appid" VARCHAR(64) not null UNIQUE,
    "profile_pic" VARCHAR(256) not null,
    PRIMARY KEY (psid, appid)
);
create table subscribers (
    "id" serial,
    "user_psid" VARCHAR(64) references users(psid) not null,
    "comic_id" INT references comics(id) not null,
    "created_at" timestamptz NOT NULL DEFAULT (now())
);

Basicly comics and users table has many-to-many relationship, which is in subscribers table. I want to get all comics subscribed by an user using this join query:

--name GetSubscribedComic :one
SELECT comics.id, comics.name
FROM comics
LEFT JOIN subscribers ON comics.id = subscribers.comic_id 
WHERE subscribers.user_psid=$1 AND subscribers.comic_id=$2;

But something maybe wrong with sqlc, it generated sql.go file but doesn't have this query in it. Can you please check it?

**Comment by uta-mori** [comment]
@tinoquang 

It seems to be a difference in the format of query comment

```diff
- --name GetSubscribedComic :one

+ -- name: GetSubscribedComic :one
```

playground: https://play.sqlc.dev/p/ae4eef10d9f546c55183e2652b31c0dc534ac99309c98d623e8c0288a24ecb73

**Comment by tinoquang** [comment]
Oh man! My mistake, appreciated!

**Comment by tinoquang** [comment]
I recommend you should add error when parsing query comment, this is a tricky bug and I've seen no nortification

**Comment by uta-mori** [comment]
It seems that the basic error handling is done.
but the following two typo cases error handling are missing in this.

- without a space after `--`
    - `--name: {queryname} :{cmd}`    
- without `:` after `name`
    - `-- name {queryname} :{cmd}`

https://github.com/kyleconroy/sqlc/blob/master/internal/metadata/meta.go
