### ISSUE TITLE
pq: insert or update on table violates foreign key constraint

### ISSUE THREAD

**Issue by vibhordubey333** [kyleconroy/sqlc#838]
When inserting a null value in "c_operator" field using sql "insert" statement I am able to insert but sqlc doesn't support this operattion I am receiving below error.
`"pq: insert or update on table \"policy_constraints\" violates foreign key constraint \"fk_constraint_operator\""`

  **Solution I tried:** 

`COperator:             sql.NullString{String: constraint.Operator, Valid: true},` 

I tried toggling "VALID" to true, which is able to solve the above mentioned error but if I am providing "c_operator" a valid value then also it is inserting NULL.

Link to playground : https://play.sqlc.dev/p/816b6ec4bf83f57a9adabd38a9fe152af25c1967f3d50d3118002b2bdccf0175

Go Version: go version go1.15.3 windows/amd64

Let me know if any further details are required from my end.

**Comment by kyleconroy** [comment]
I'm going to close this, as it doesn't appear to be an issue with sqlc. Instead, it appears to be an issue your query. The generated code has the correct argument types.

**Comment by AvinFajarF** [comment]
i also have the same problem
