### ISSUE TITLE
is there documentation to write test code for the generated package?

### ISSUE THREAD

**Issue by aphsa** [kyleconroy/sqlc#848]
is there reference documentation on how to go about writing test code for the generated package?

**Comment by alecbz** [comment]
FWIW in our use of sqlc, we haven't written tests for the generated code directly, though our tests that generally exercise the related codepaths end up triggering the sqlc code during test.

In general I think I'd say, given that the code is generated, there's not a whole lot of value in writing tests for it? Any issue that such a test might catch should really be caught by tests for sqlc itself.

If there was value in having tests for the generated code, it would probably make the most sense to also generate those tests? Unless you're imagining tests that couldn't be easily generated?

**Comment by uta-mori** [comment]
@aphsa 

I just saw it recently.

[How to handle DB errors in Golang correctly - DEV Community 👩‍💻👨‍💻](https://dev.to/techschoolguru/how-to-handle-db-errors-in-golang-correctly-11ek)
