### ISSUE TITLE
Is this repo still actively maintained?

### ISSUE THREAD

**Issue by abagshaw** [kyleconroy/sqlc#850]
I'm planning on using this in a production setting, but there appear to be a number of unanswered issues/open PRs from a while ago.

**Comment by kevinburkemeter** [comment]
Yes

**Comment by kyleconroy** [comment]
Yes! I recently started a new job, meaning I have less time to work on sqlc.

That said, sqlc isn't going anywhere as is ready for production use.

Also, please consider sponsoring the project. Thanks!

**Comment by abagshaw** [comment]
@kyleconroy Makes sense, thanks so much for your work - sqlc is really awesome 🙂
