### ISSUE TITLE
Undeclared name "net" when using Postgres' MACADDR

### ISSUE THREAD

**Issue by td0m** [kyleconroy/sqlc#853]
When you use MACADDR Postgres data type it converts it to `net.HardwareAddr`, but it doesn't import `net`.

**Comment by kyleconroy** [comment]
Reproduced in the sqlc Playground here: https://play.sqlc.dev/p/1c9ab2e5ccf8d58df24b8b4c75ff74f0a207f807a6b986f6447e444b4035b030
