### ISSUE TITLE
MySQL `bool` type generates `int32` golang type

### ISSUE THREAD

**Issue by bquenin** [kyleconroy/sqlc#856]
The following MySQL source code:

```
CREATE TABLE example
(
    id         integer      NOT NULL AUTO_INCREMENT PRIMARY KEY,
    successful bool         NOT NULL
);
```

Generated the following model:
```
type Example struct {
	ID         int32     `json:"id"`
	Successful int32     `json:"successful"`
}
```
Actually, all the boolean types (`bool`, `boolean` and `tinyint`) are behaving in this way.

I'm currently using this workaround to force the correct type:
```
version: "1"

packages: [...]
overrides:
- column: "example.successful"
  go_type: "bool"
```

This has already been mentioned by @markschmid in https://github.com/kyleconroy/sqlc/issues/666#issuecomment-732159568_

**Comment by kyleconroy** [comment]
MySQL doesn't have a native boolean type. `BOOL` and `BOOLEAN` map to `tinyint(1)`. We can't map `tinyint(1)` to boolean because you can actually store [values other than 0 and 1](https://stackoverflow.com/a/12840074/6119221) in  a column marked tinyint(1).

The issue is that the MySQL parser we're using parsers `BOOL` and `BOOLEAN` (correctly) as `tinyint(1)` and offers no way to see the original type.

**Comment by kyleconroy** [comment]
> we may want to convert any tinyint(1) column to a BOOL.

This is now done

**Comment by dangelov** [comment]
Using v1.7.0, it seems this issue is still there. I'm not using any overrides.

```sql
CREATE TABLE `images` (
    `is_main`    BOOL NOT NULL DEFAULT FALSE
)
```

```go
type ImageGetRow struct {
	IsMain     int32     `json:"is_main"`
}
```

```bash
$ sqlc version
v1.7.0
```

**Comment by kyleconroy** [comment]
@dangelov I can't reproduce this using v1.7.0

```yaml
# sqlc.yaml
version: "1"
packages:
  - path: "db"
    queries: "query.sql"
    schema: "query.sql"
    engine: "mysql"
```

```sql
-- query.sql
CREATE TABLE `images` (
    `is_main`    BOOL NOT NULL DEFAULT FALSE
);

-- name: ListImages :many
SELECT * FROM images;
```

This outputs the following db/models.go:

```go
// Code generated by sqlc. DO NOT EDIT.

package db

import ()

type Image struct {
	IsMain bool
}
```

**Comment by kyleconroy** [comment]
Ahh, thanks for the in-depth report. It looks like I fixed it for model generation but something is off when generating the methods. Will fix!
