### ISSUE TITLE
Insert N rows

### ISSUE THREAD

**Issue by alexpashkov** [kyleconroy/sqlc#857]
Hello, I am considering using the lib and I've not found how inserting N rows is handled. The query is something like:

```sql
insert into <table> (<col1>, <col2>) values (<col1val1>, <col2val2>), ..., (<col1valN>, <col2valN>);
```

**Comment by kyleconroy** [comment]
Inserting a variable number of rows in current not supported, as it would require dynamically generated SQL. Please see https://github.com/kyleconroy/sqlc/issues/218 and https://github.com/kyleconroy/sqlc/issues/216 for previous discussions.
