### ISSUE TITLE
Error generating code when using EXCEPT

### ISSUE THREAD

**Issue by capnspacehook** [kyleconroy/sqlc#867]
Tried to generate a simple statement using `EXCEPT` and received an error: 

```
# package database
error generating code: template: table:252:79: executing "queryCode" at <.Ret.Type>: error calling Type: no type for GoQueryValue:
```

Reproducible here: https://play.sqlc.dev/p/e534fb7d1488233f3984e8e488530aaeeea5ba692e423aee2a0b35d959c1b56c

**Comment by kyleconroy** [comment]
Fixed in #896
