### ISSUE TITLE
camelCase

### ISSUE THREAD

**Issue by koodimetsa** [kyleconroy/sqlc#878]
Would there a possibility to get camel casing behind a flag? 
This would be great feature in few cases. For example a web-app which uses multiple APIs and some of them return camel case. Would be great if everything would use the same casing.

**Comment by kyleconroy** [comment]
Can you provide a short example of the current output and the output you'd like to see?

**Comment by koodimetsa** [comment]
For example a table of users: 
```
CREATE TABLE users (
	  first_name VARCHAR(50) NOT NULL
);
```
Which now would produce:
```
type User struct {
	FirstName    string    `json:"first_name"`
}
```

But what would be nice to have, is the ability to have json tags with camel case, for example:
```
type User struct {
	FirstName    string    `json:"firstName"`
}
```

So basically an option to say underscores in a table definition should be converted to camel case.

**Comment by imamulakhyar93** [comment]
It's working well if the column name on the table is snake case:
```sql
CREATE TABLE users (
	  first_name VARCHAR(50) NOT NULL
);
```
it produce:
```go
type User struct {
	FirstName    string    `json:"firstName"`
}
```

but when the table column name is in the camelCase:
```sql
CREATE TABLE users (
	  firstName VARCHAR(50) NOT NULL
);
```

it produce:
```go
type User struct {
	FirstName    string    `json:"firstname"`
}
```
I tried to use both `json_tags_case_style: none` and `json_tags_case_style: camel` but those option produce lowercases
