### ISSUE TITLE
Using schemas doesn't generate structs in the models.go file

### ISSUE THREAD

**Issue by euller88** [kyleconroy/sqlc#88]
I'm gonna investigate this issue later, but [this repo](https://github.com/euller88/issue_example) shows exactly the what the title says. I will try to make a PR to solve it, but I can't guarantee when.

**Comment by kyleconroy** [comment]
Thanks for the bug report and the example code. I’m traveling, but will get a chance to look at this tomorrow night.

**Comment by kyleconroy** [comment]
@euller88 In this specific case, how would you feel about the generated struct being `LibraryAuthor` instead of `Author`? Another option would be to create a package for each schema, but that may be too much indirection.

**Comment by euller88** [comment]
I think that `LibraryAuthor` is a better approach. Creating specific packages wouldn't add that much of convenience.

**Comment by kyleconroy** [comment]
Alright, just merged the change that prefixes the schema name. It also fixes a bug where enums from other schemas weren't being generated as well.
