### ISSUE TITLE
Postgres: support enum renaming

### ISSUE THREAD

**Issue by arddor** [kyleconroy/sqlc#894]
It still generates the old enum name after renaming:
```
create type event as enum ('START', 'STOP');
alter type event rename to "new_event";
```

**Comment by kyleconroy** [comment]
Yep, looks like this is the case. Reproduced here: https://play.sqlc.dev/p/84f0f7e2e0174e2ee7893fdf71d6930d3c907f8b4a242bdca96aaf5f13c7ce01
