### ISSUE TITLE
sqlc ignore paramter in LIKE

### ISSUE THREAD

**Issue by yotamN** [kyleconroy/sqlc#895]
It seems that sqlc does not recognize a parameter inside a LIKE string, is there a special syntax for that or is it just not supported?

**Comment by kyleconroy** [comment]
I'm going to need more information before I reproduce your issue. Can you please answer the following questions:

- What version of sqlc are you using?
- What engine are you using (MySQL or PostgreSQL)?
- What OS / arch are you on?

Can you also try to reproduce the issue in the [sqlc playground](https://play.sqlc.dev/)?

**Comment by konradreiche** [comment]
[sqlc Playground](https://play.sqlc.dev/p/220eb282fb55c0530d6986a79a511e69e2fc29c99a21d144d2a26b222aec896a)

While this compiles fine:

```sql
-- name: SearchAuthor :many
SELECT * from authors WHERE name LIKE '%$1%';
```

It does not produce a parametrized method:

```go
func (q *Queries) SearchAuthor(ctx context.Context) ([]Author, error)
```

**Comment by konradreiche** [comment]
One workaround is to define it as:
```
-- name: SearchAuthor :many
SELECT * from authors WHERE name LIKE $1;
```
And specify the `%` as part of the string you are passing to the method.

**Comment by zono-dev** [comment]
Hi. I have had the same problem but it seems occur only when MySQL engine is used.

- What version of sqlc are you using? -> v1.6.0
- What engine are you using (MySQL or PostgreSQL)? -> MySQL
- What OS / arch are you on? -> Linux(Alpine)

Playground: https://play.sqlc.dev/p/1f74d1fa215e49a51bedd8bab968826d5f772e1ffdd4c938ec78694823c033da

MySQL engine seems to ignore argument(s).

```sql
-- Example queries for sqlc
CREATE TABLE authors (
  id   SERIAL PRIMARY KEY,
  name text      NOT NULL,
  bio  text
);

-- name: SearchAuthor :many
SELECT * from authors WHERE name = $1;
```

```Go
// Code generated by sqlc. DO NOT EDIT.
// source: query.sql

package db

import (
	"context"
)

const searchAuthor = `-- name: SearchAuthor :many
SELECT id, name, bio from authors WHERE name = $1
`

func (q *Queries) SearchAuthor(ctx context.Context) ([]Author, error) {
	rows, err := q.db.QueryContext(ctx, searchAuthor)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Author
	for rows.Next() {
		var i Author
		if err := rows.Scan(&i.ID, &i.Name, &i.Bio); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
```

**Comment by fr3fou** [comment]
Has this been fixed? The playground link still generates the wrong code.

**Comment by dytlan** [comment]
- sqlc version : 1.7
- Engine : MySQL

I have the same problem. LIKE is ignored

**Comment by amariucaitheodor** [comment]
-  sqlc version : 1.8
- Engine : PostgreSQL

I have the same problem. LIKE is ignored

**Comment by a8uhnf** [comment]
Is there any possibility to add this feature for MySQL in near future?

**Comment by DuginKim** [comment]
sqlc version : 1.8
Engine : MySQL
LIKE is ignored

**Comment by dee-el** [comment]
this problem occured on me too, just when using MySQL 

```
sqlc version : 1.8
Engine : MySQL
LIKE is ignored
```
