### ISSUE TITLE
Truncate table tool

### ISSUE THREAD

**Issue by kevinburkemeter** [kyleconroy/sqlc#899]
One thing I frequently want/need to do is truncate a test database. Generally this is something along the lines of 

```sql
BEGIN 
SET CONSTRAINTS ALL DEFERRED
DELETE FROM <>;
DELETE FROM <>;
COMMIT;
```

It would be nice to be able to get a list of tables out in order to run this query.

(My initial thought was sqlc should build a dependency graph to delete the tables in the right order and then realized we don't need to do that because you can defer constraint enforcement to the end.)

**Comment by kevinburkemeter** [comment]
Related, I am needing to add info about the pg_tables or information_schema tables in order to get sqlc to compile a query to list all of the tables.

**Comment by kevinburkemeter** [comment]
Ahhh, right, I do need the dependency graph because foreign keys are not deferrable by default so I need to go back and make them all deferrable or delete the tables in the "correct" order which in theory sqlc could infer.

**Comment by kyleconroy** [comment]
I'm working on adding support for all the pg_* tables from the system catalog here #1171.
