### ISSUE TITLE
Unable to install sqlc

### ISSUE THREAD

**Issue by theshid** [kyleconroy/sqlc#903]
I've been trying to install install sqlc without success. I'm using windows and did it with the go get command (go get github.com/kyleconroy/sqlc/cmd/sqlc)

but I'm getting this error:
```
# github.com/kyleconroy/sqlc/internal/engine/dolphin
..\..\go\src\github.com\kyleconroy\sqlc\internal\engine\dolphin\convert.go:318:28: n.OldTable undefined (type *"github.com/pingcap/parser/ast".RenameTableStmt has no field or method OldTable)
..\..\go\src\github.com\kyleconroy\sqlc\internal\engine\dolphin\convert.go:319:29: n.NewTable undefined (type *"github.com/pingcap/parser/ast".RenameTableStmt has no field or method NewTable)
```

**Comment by kyleconroy** [comment]
What version of Go are you using? For `go get` to work, you need to have module support (GOMODULE) enabled.

**Comment by theshid** [comment]
I'm using Go 1.14.1 , so I think that the module support is enabled by default

**Comment by kyleconroy** [comment]
Sorry, you need to be using a version of Go that supports modules.

**Comment by theshid** [comment]
I download the last Go version (1.16) and still got this:
```
C:\Users\Shid>go get github.com/kyleconroy/sqlc/cmd/sqlc
# github.com/lfittl/pg_query_go/parser
In file included from go\pkg\mod\github.com\lfittl\pg_query_go@v1.0.1\parser\include/c.h:1224,
                 from go\pkg\mod\github.com\lfittl\pg_query_go@v1.0.1\parser\include/postgres.h:47,
                 from contrib_pgcrypto_sha1.c:50:
go\pkg\mod\github.com\lfittl\pg_query_go@v1.0.1\parser\include/port.h:17:10: fatal error: netdb.h: No such file or directory
   17 | #include <netdb.h>
      |          ^~~~~~~~~
compilation terminated.
```
I then downloaded the precompiles binaries, it got installed but I checked the version number and I got a weird number:
```
C:\Users\Shid>sqlc version
v0.0.0-20210216223444-2659edf2b250
```

**Comment by kyleconroy** [comment]
Windows support was recently merged; it hasn't landed in a released version yet. `go get` may work once v1.7.0 is released. The version you downloaded is a tip release, built of the main branch, hence the weird version number. That's the only way for you to currently use sqlc until the next release. Sorry!

**Comment by kyleconroy** [comment]
@theshid Can you try again via `go get`? v1.7.0 should now build on Windows.

**Comment by theshid** [comment]
Just tried it and it worked perfectly, thanks a lot!!
