### ISSUE TITLE
Query parameter typing / import generation conflict

### ISSUE THREAD

**Issue by angie-meter** [kyleconroy/sqlc#918]
We have the following `uuid` overrides for nullable vs not:
```
  - go_type: "github.com/gofrs/uuid.UUID"
    db_type: "uuid"
    nullable: false
  - go_type: "github.com/meterup/api/src/internal/dbtypes.NullUUID"
    db_type: "uuid"
    nullable: true
```

With the query:
```
SELECT * FROM locations WHERE quote_request = ANY($1::uuid[]);
```
with `quote_request` being a `nullable` uuid.

The following method header is generated for the query:
```
func (q *Queries) GetLocationsForQuoteRequests(ctx context.Context, dollar_1 []uuid.UUID) ([]Location, error)
```
but only the `github.com/meterup/api/src/internal/dbtypes` import is generated.

**Comment by kyleconroy** [comment]
Reproduced here: https://play.sqlc.dev/p/e90b38e3b56f6d6742dbdcc38d275f7b2bf0216f7f57dc30709a684c0acf1cb0

**Comment by kyleconroy** [comment]
Not sure when this happened, but this has been fixed 

https://play.sqlc.dev/p/fa6b24b95225f3235970f5c1e244a9e73be93d80a392ca79e2775effc7a28325
