### ISSUE TITLE
CASE expressions aren't being parsed/read

### ISSUE THREAD

**Issue by euller88** [kyleconroy/sqlc#92]
Queries using conditional expressions like NULLIF and COALESCE generate proper Go code. Meanwhile, the CASE conditional expression does not. The generated go code doesn't generate an additional field in the result struct, making the Scan fail each time is called. I will try to investigate this issue later on the week and try to provide a fix. The following query can be used to reproduce the observed behavior:
```sql
SELECT
  id,
  CASE 
    WHEN id = $1 THEN true
    ELSE false
  END is_one
FROM
  author;
```

**Comment by euller88** [comment]
Actually, NULLIF also smells bad. When using it in a query, the Go struct is generated with a field with the bool type, instead of a Null* type. The following query:
```sql
SELECT
  NULLIF(id, $1) restricted_id
FROM
  author
```
Will generate the following strange code:
```go
type FuncResult struct {
  RestrictedID bool `json:"restricted_id"`
}
```
When correct type would be `sql.NullInt64`.

**Comment by kyleconroy** [comment]
Yeah, these are indeed two problems. I hope to get a chance to look at them this weekend
