### ISSUE TITLE
MySQL missing update args ON DUPLICATE KEY UPDATE

### ISSUE THREAD

**Issue by koodimetsa** [kyleconroy/sqlc#921]
Generated code is missing args for the update part _on duplicate key update_.
For example:

```
/* name: UpdateDeviceOnlineTime :exec */
INSERT INTO devices_online_status
  (device_id, last_online)
VALUES
    (?, ?)
ON DUPLICATE KEY UPDATE
last_online = ?;
```

generates 
```
func (q *Queries) UpdateDeviceOnlineTime(ctx context.Context, arg UpdateDeviceOnlineTimeParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateDeviceOnlineTime, arg.DeviceID, arg.LastOnline)
}
```
arg.LastOnline should be twice, but is now once.

**Comment by Funzinator** [comment]
Adding a [sample in playground](https://play.sqlc.dev/p/6bdb19d950ff8d6254010c5e97e1e560146894a19157e150d73dac63b62afdcc) for easier reproduction, hoping to bump it up a bit.

In the example, the parameters of the `UPDATE` part are missing (`bio` has to be provided twice as `sql.NullString`).
