### ISSUE TITLE
Type override works for bool but not boolean

### ISSUE THREAD

**Issue by arddor** [kyleconroy/sqlc#922]
It seems that a type override works for [bool](https://play.sqlc.dev/p/afb0133fe98879b80d76ac348562a8fb1d15565f8265859655b6ac19a07ff859) but not if the type is [boolean](https://play.sqlc.dev/p/ea2c86d8057ba40523649a06d277393c269ca7ba1faafc5bcfa71bdb8df10c31). 

Edit: just tried with [pg_catalog.bool](https://play.sqlc.dev/p/c2b440d16747f30c26463d3096036947775ca828e351f436ab55a9ab7c8ca356) and that works as a workaround for now.

**Comment by mvrhov** [comment]
It's basically #814.. se my comment in the middle

**Comment by kyleconroy** [comment]
Going to track all override issues in a single issue: #814
