### ISSUE TITLE
easier handle database retry

### ISSUE THREAD

**Issue by kevinburkemeter** [kyleconroy/sqlc#930]
It would be nice in the event of database instability - for example, if the database restarts and is returning connection refused - for the queries issued by sqlc to automatically retry up until a specified number of times or until the context runs out. 

Bonus points if you can also retry errors on idempotent queries that fail after the query has been sent to the database.

**Comment by kyleconroy** [comment]
While this would be nice to have, it's low priority. Maybe we figure out a generic middleware stack so that retry logic can be implemented outside of sqlc.
