### ISSUE TITLE
unsupported reference type: <nil>

### ISSUE THREAD

**Issue by kevinburkemeter** [kyleconroy/sqlc#932]
I get this now when I run sqlc, but it still completes. It may be related to this query?

```sql
INSERT INTO table (field, boolean_related_to_field) VALUES ($1, $1 IS NULL)
```

**Comment by kevinburkemeter** [comment]
oh no I think it's from this

```sql
... VALUES(COALESCE($1, '{}'))
```

where the underlying column is a `text[]`

**Comment by kevinburkemeter** [comment]
casting to `COALESCE($1::text[], '{}')` fixes it

**Comment by kyleconroy** [comment]
I believe this is fixed: https://play.sqlc.dev/p/92de788da01f59f43bca6ae428788ede4ea26bb7d524e45e19fb29ddcb692890

If not, can you provide a full working example?

**Comment by saward** [comment]
@kyleconroy is this related?  https://play.sqlc.dev/p/a03c062b677a7bbea6cc1d3f3fa7193d566afd99e7a3e6fea4bcf58d0a97f8ba

Using this, I get that error:

```
SELECT name, count(*) AS total FROM authors
WHERE ($1 IS NULL OR name = $1)
GROUP BY name;
```

But specifying the type of $1 removes the error:

```
SELECT name, count(*) AS total FROM first.authors
WHERE ($1::text IS NULL OR name = $1::text)
GROUP BY name;
```

I know that postgres does have trouble determining the type of $1 in cases like this (though I can't recall the circumstances to generate it), so not sure if there's anything to fix here, other than maybe making the error message clearer?
