### ISSUE TITLE
json_tags_case_style config option not found - v1.7.0

### ISSUE THREAD

**Issue by myles-mcdonnell** [kyleconroy/sqlc#946]
`field json_tags_case_style not found in type config.v1PackageSettings`

**Comment by kyleconroy** [comment]
`json_tags_case_style` were added in https://github.com/kyleconroy/sqlc/pull/905, which was merged after v1.7.0 was released. I think you were looking at the latest documentation instead of the docs for v1.7.0 (https://docs.sqlc.dev/en/v1.7.0/reference/config.html)
