### ISSUE TITLE
Migrate to pganalyze/pg_query_go

### ISSUE THREAD

**Issue by johanbrandhorst** [kyleconroy/sqlc#948]
It appears that @lfittl moved the `pg_query_go` repo to a new home in https://github.com/pganalyze/pg_query_go. Since `sqlc` builds much of its postgres capabilities on this library, we should aim to stay up to date with its development. This would also enable support for `postgres` 13 additions.

**Comment by lfittl** [comment]
@johanbrandhorst Thats right - note that the v2 release has considerable differences in the parse tree format (its now auto generated from Protocol Buffers), so be aware that this might be a small undertaking to update.

Happy to provide input if you or @kyleconroy have questions :)
