### ISSUE TITLE
Column matching is case sensitive

### ISSUE THREAD

**Issue by inconshreveable** [kyleconroy/sqlc#953]
### Repro Steps

```
create table foo (id integer);

/* name: q :one */
SELECT * FROM foo where ID = ?;
```

```
sqlc generate
```

### Expected

No error

### Observed

# package mysql
example.sql:1:1: column "ID" does not exist

### Notes

Version: Version v0.0.0-20210319232515-4d28821de6ae

sql columns are case-insensitive per (i believe) the sql standard, or at the very least de facto across every database engine that i've used.

it's easy to work around by renaming the column to have the same casing as used in the DDL

i've only tested this on the mysql engine, it's unknown whether a similar issue exists for other engines.

**Comment by kyleconroy** [comment]
Replaced by https://github.com/kyleconroy/sqlc/issues/1215, which has a playground link and full example.
