### ISSUE TITLE
pq.Array still in use?

### ISSUE THREAD

**Issue by deelienardy** [kyleconroy/sqlc#989]
schema
```
CREATE TABLE "test_table"
(
	"key" VARCHAR(255) NOT NULL PRIMARY KEY,
	"created_at" TIMESTAMP WITH TIME ZONE
);
```
query
```
-- name: FindByIDs :many
SELECT 
    "key", "created_at"
FROM "test_table"
WHERE "key" = ANY($1::varchar[]) 
ORDER BY "created_at" DESC;
```

I have to do some query like above, after i generate the query, i found codegen still use `pq.Array`.
Since #472 already closed, is this intended to still use pq.Array ?

**Comment by kyleconroy** [comment]
@deelienardy Have you set `sql_package` to `pgx/v4`? Can you also provide your sqlc.json or sqlc.yaml file?

**Comment by kyleconroy** [comment]
By default, `pq.Array` will still be generated. If you set `sql_package` to `pgx/v4`, `pq.Array` should not be included in any generated code. If it does, that's an error.
