### ISSUE TITLE
cmd: sqlc init doesn't create an empty sqlc.yaml settings file

### ISSUE THREAD

**Issue by sagar23sj** [kyleconroy/sqlc#991]
After installing sqlc using :
go get github.com/kyleconroy/sqlc/cmd/sqlc

I tried running the following command :
$sqlc init

Expected Output : sqlc.yaml file should have been generated by default as description suggests (Create an empty sqlc.yaml settings file)

Actual Output : Error: open : no such file or directory

sqlc version : v1.7.0

**Comment by ansidev** [comment]
Confirmed bug.
v1.6.0: Working.
v1.7.0: Failed.

**Comment by kyleconroy** [comment]
This has been fixed in v1.8.0
